/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetUnreadNotificationCountStatus200 } from '../../types/GetUnreadNotificationCount'
import { queryOptions } from '@tanstack/react-query'
import { getUnreadNotificationCount } from '../../clients/getUnreadNotificationCount'

export const getUnreadNotificationCountQueryKey = () => [{ url: '/api/v1/notifications/unread-count' }] as const

type GetUnreadNotificationCountQueryKey = ReturnType<typeof getUnreadNotificationCountQueryKey>

export function getUnreadNotificationCountQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getUnreadNotificationCountQueryKey()
  return queryOptions<GetUnreadNotificationCountStatus200, ResponseErrorConfig<Error>, GetUnreadNotificationCountStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getUnreadNotificationCount({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
