/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { MarkAllNotificationsReadStatus200 } from '../../types/MarkAllNotificationsRead'
import { mutationOptions } from '@tanstack/react-query'
import { markAllNotificationsRead } from '../../clients/markAllNotificationsRead'

export const markAllNotificationsReadMutationKey = () => [{ url: '/api/v1/notifications/read-all' }] as const

export function markAllNotificationsReadMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = markAllNotificationsReadMutationKey()
  return mutationOptions<MarkAllNotificationsReadStatus200, ResponseErrorConfig<Error>, undefined, TContext>({
    mutationKey,
    mutationFn: async(_) => {
      const { data } = await markAllNotificationsRead({ ...config, throwOnError: true })
      return data
    },
  })
}
