/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { FindOrCreateDmOptions, FindOrCreateDmStatus200 } from '../../types/FindOrCreateDm'
import { mutationOptions } from '@tanstack/react-query'
import { findOrCreateDm } from '../../clients/findOrCreateDm'

export const findOrCreateDmMutationKey = () => [{ url: '/api/v1/chat/dms' }] as const

export function findOrCreateDmMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = findOrCreateDmMutationKey()
  return mutationOptions<FindOrCreateDmStatus200, ResponseErrorConfig<Error>, FindOrCreateDmOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await findOrCreateDm({ ...config, body, throwOnError: true })
      return data
    },
  })
}
