/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ListMyChannelsOptions, ListMyChannelsStatus200 } from '../../types/ListMyChannels'
import { queryOptions } from '@tanstack/react-query'
import { listMyChannels } from '../../clients/listMyChannels'

export const listMyChannelsQueryKey = ({ query }: Omit<ListMyChannelsOptions, 'headers'> = {}) => [{ url: '/api/v1/chat/channels' }, ...(query ? [query] : [])] as const

type ListMyChannelsQueryKey = ReturnType<typeof listMyChannelsQueryKey>

export function listMyChannelsQueryOptions({ query }: ListMyChannelsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listMyChannelsQueryKey({ query })
  return queryOptions<ListMyChannelsStatus200, ResponseErrorConfig<Error>, ListMyChannelsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listMyChannels({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
