/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { MarkChannelReadOptions, MarkChannelReadStatus200 } from '../../types/MarkChannelRead'
import { mutationOptions } from '@tanstack/react-query'
import { markChannelRead } from '../../clients/markChannelRead'

export const markChannelReadMutationKey = () => [{ url: '/api/v1/chat/channels/:id/read' }] as const

export function markChannelReadMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = markChannelReadMutationKey()
  return mutationOptions<MarkChannelReadStatus200, ResponseErrorConfig<Error>, MarkChannelReadOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await markChannelRead({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
