/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { UpdateChannelOptions, UpdateChannelStatus200 } from '../../types/UpdateChannel'
import { mutationOptions } from '@tanstack/react-query'
import { updateChannel } from '../../clients/updateChannel'

export const updateChannelMutationKey = () => [{ url: '/api/v1/chat/channels/:id' }] as const

export function updateChannelMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateChannelMutationKey()
  return mutationOptions<UpdateChannelStatus200, ResponseErrorConfig<Error>, UpdateChannelOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateChannel({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
