/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { UpdateMessageOptions, UpdateMessageStatus200 } from '../../types/UpdateMessage'
import { mutationOptions } from '@tanstack/react-query'
import { updateMessage } from '../../clients/updateMessage'

export const updateMessageMutationKey = () => [{ url: '/api/v1/chat/messages/:id' }] as const

export function updateMessageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateMessageMutationKey()
  return mutationOptions<UpdateMessageStatus200, ResponseErrorConfig<Error>, UpdateMessageOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateMessage({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
