/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { DeleteWebhookSubscriptionOptions, DeleteWebhookSubscriptionStatus204 } from '../../types/DeleteWebhookSubscription'
import { mutationOptions } from '@tanstack/react-query'
import { deleteWebhookSubscription } from '../../clients/deleteWebhookSubscription'

export const deleteWebhookSubscriptionMutationKey = () => [{ url: '/api/v1/webhooks/subscriptions/:id' }] as const

export function deleteWebhookSubscriptionMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteWebhookSubscriptionMutationKey()
  return mutationOptions<DeleteWebhookSubscriptionStatus204, ResponseErrorConfig<Error>, DeleteWebhookSubscriptionOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteWebhookSubscription({ ...config, path, throwOnError: true })
      return data
    },
  })
}
