/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { TestWebhookSubscriptionOptions, TestWebhookSubscriptionStatus200 } from '../../types/TestWebhookSubscription'
import { mutationOptions } from '@tanstack/react-query'
import { testWebhookSubscription } from '../../clients/testWebhookSubscription'

export const testWebhookSubscriptionMutationKey = () => [{ url: '/api/v1/webhooks/subscriptions/:id/test' }] as const

export function testWebhookSubscriptionMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = testWebhookSubscriptionMutationKey()
  return mutationOptions<TestWebhookSubscriptionStatus200, ResponseErrorConfig<Error>, TestWebhookSubscriptionOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await testWebhookSubscription({ ...config, path, throwOnError: true })
      return data
    },
  })
}
