/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { AddProductImageOptions, AddProductImageStatus200, AddProductImageStatus404 } from '../../types/AddProductImage'
import { mutationOptions } from '@tanstack/react-query'
import { addProductImage } from '../../clients/addProductImage'

export const addProductImageMutationKey = () => [{ url: '/api/v1/catalog/products/:productId/images' }] as const

export function addProductImageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = addProductImageMutationKey()
  return mutationOptions<AddProductImageStatus200, ResponseErrorConfig<AddProductImageStatus404>, AddProductImageOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await addProductImage({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
