/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CreateBrandOptions, CreateBrandStatus200 } from '../../types/CreateBrand'
import { mutationOptions } from '@tanstack/react-query'
import { createBrand } from '../../clients/createBrand'

export const createBrandMutationKey = () => [{ url: '/api/v1/catalog/brands' }] as const

export function createBrandMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createBrandMutationKey()
  return mutationOptions<CreateBrandStatus200, ResponseErrorConfig<Error>, CreateBrandOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createBrand({ ...config, body, throwOnError: true })
      return data
    },
  })
}
