/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { DeleteCategoryOptions, DeleteCategoryStatus200 } from '../../types/DeleteCategory'
import { mutationOptions } from '@tanstack/react-query'
import { deleteCategory } from '../../clients/deleteCategory'

export const deleteCategoryMutationKey = () => [{ url: '/api/v1/catalog/categories/:categoryId' }] as const

export function deleteCategoryMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteCategoryMutationKey()
  return mutationOptions<DeleteCategoryStatus200, ResponseErrorConfig<Error>, DeleteCategoryOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteCategory({ ...config, path, throwOnError: true })
      return data
    },
  })
}
