/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { DeleteBrandOptions, DeleteBrandStatus200 } from '../../types/DeleteBrand'
import { mutationOptions } from '@tanstack/react-query'
import { deleteBrand } from '../../clients/deleteBrand'

export const deleteBrandMutationKey = () => [{ url: '/api/v1/catalog/brands/:brandId' }] as const

export function deleteBrandMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteBrandMutationKey()
  return mutationOptions<DeleteBrandStatus200, ResponseErrorConfig<Error>, DeleteBrandOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteBrand({ ...config, path, throwOnError: true })
      return data
    },
  })
}
