/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetCategoryTreeStatus200 } from '../../types/GetCategoryTree'
import { queryOptions } from '@tanstack/react-query'
import { getCategoryTree } from '../../clients/getCategoryTree'

export const getCategoryTreeQueryKey = () => [{ url: '/api/v1/catalog/categories/tree' }] as const

type GetCategoryTreeQueryKey = ReturnType<typeof getCategoryTreeQueryKey>

export function getCategoryTreeQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getCategoryTreeQueryKey()
  return queryOptions<GetCategoryTreeStatus200, ResponseErrorConfig<Error>, GetCategoryTreeStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getCategoryTree({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
