/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetBrandByIdOptions, GetBrandByIdStatus200 } from '../../types/GetBrandById'
import { queryOptions } from '@tanstack/react-query'
import { getBrandById } from '../../clients/getBrandById'

export const getBrandByIdQueryKey = ({ path }: Omit<GetBrandByIdOptions, 'headers'>) => [{ url: '/api/v1/catalog/brands/:brandId', params: path }] as const

type GetBrandByIdQueryKey = ReturnType<typeof getBrandByIdQueryKey>

export function getBrandByIdQueryOptions({ path }: GetBrandByIdOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getBrandByIdQueryKey({ path })
  return queryOptions<GetBrandByIdStatus200, ResponseErrorConfig<Error>, GetBrandByIdStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getBrandById({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
