/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetProductByIdOptions, GetProductByIdStatus200 } from '../../types/GetProductById'
import { queryOptions } from '@tanstack/react-query'
import { getProductById } from '../../clients/getProductById'

export const getProductByIdQueryKey = ({ path }: Omit<GetProductByIdOptions, 'headers'>) => [{ url: '/api/v1/catalog/products/:productId', params: path }] as const

type GetProductByIdQueryKey = ReturnType<typeof getProductByIdQueryKey>

export function getProductByIdQueryOptions({ path }: GetProductByIdOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getProductByIdQueryKey({ path })
  return queryOptions<GetProductByIdStatus200, ResponseErrorConfig<Error>, GetProductByIdStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getProductById({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
