/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ListTrashedBrandsOptions, ListTrashedBrandsStatus200 } from '../../types/ListTrashedBrands'
import { queryOptions } from '@tanstack/react-query'
import { listTrashedBrands } from '../../clients/listTrashedBrands'

export const listTrashedBrandsQueryKey = ({ query }: Omit<ListTrashedBrandsOptions, 'headers'> = {}) => [{ url: '/api/v1/catalog/brands/trash' }, ...(query ? [query] : [])] as const

type ListTrashedBrandsQueryKey = ReturnType<typeof listTrashedBrandsQueryKey>

export function listTrashedBrandsQueryOptions({ query }: ListTrashedBrandsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listTrashedBrandsQueryKey({ query })
  return queryOptions<ListTrashedBrandsStatus200, ResponseErrorConfig<Error>, ListTrashedBrandsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listTrashedBrands({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
