/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ListTrashedCategoriesOptions, ListTrashedCategoriesStatus200 } from '../../types/ListTrashedCategories'
import { queryOptions } from '@tanstack/react-query'
import { listTrashedCategories } from '../../clients/listTrashedCategories'

export const listTrashedCategoriesQueryKey = ({ query }: Omit<ListTrashedCategoriesOptions, 'headers'> = {}) => [{ url: '/api/v1/catalog/categories/trash' }, ...(query ? [query] : [])] as const

type ListTrashedCategoriesQueryKey = ReturnType<typeof listTrashedCategoriesQueryKey>

export function listTrashedCategoriesQueryOptions({ query }: ListTrashedCategoriesOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listTrashedCategoriesQueryKey({ query })
  return queryOptions<ListTrashedCategoriesStatus200, ResponseErrorConfig<Error>, ListTrashedCategoriesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listTrashedCategories({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
