/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { RemoveProductImageOptions, RemoveProductImageStatus204, RemoveProductImageStatus404 } from '../../types/RemoveProductImage'
import { mutationOptions } from '@tanstack/react-query'
import { removeProductImage } from '../../clients/removeProductImage'

export const removeProductImageMutationKey = () => [{ url: '/api/v1/catalog/products/:productId/images/:imageId' }] as const

export function removeProductImageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = removeProductImageMutationKey()
  return mutationOptions<RemoveProductImageStatus204, ResponseErrorConfig<RemoveProductImageStatus404>, RemoveProductImageOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await removeProductImage({ ...config, path, throwOnError: true })
      return data
    },
  })
}
