/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddMembersBody } from './AddMembersBody'

export type AddChannelMembersPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type AddChannelMembersStatus200 = unknown;

export type AddChannelMembersBody = AddMembersBody;

export type AddChannelMembersOptions = {
    body: AddChannelMembersBody;
    path: AddChannelMembersPath;
    query?: never;
    headers?: never;
};

export type AddChannelMembersResponses = {
    "200": AddChannelMembersStatus200;
};

/**
 * @description Union of all possible responses
*/
export type AddChannelMembersResponse = AddChannelMembersStatus200;
