/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddUsersRequest } from './AddUsersRequest'
import type { AddUsersToGroupResponse } from './AddUsersToGroupResponse'

export type AddUsersToGroupPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    groupId: string;
};

export type AddUsersToGroupStatus200 = AddUsersToGroupResponse;

export type AddUsersToGroupStatus400 = unknown;

export type AddUsersToGroupStatus401 = unknown;

export type AddUsersToGroupStatus403 = unknown;

export type AddUsersToGroupStatus404 = unknown;

export type AddUsersToGroupBody = AddUsersRequest;

export type AddUsersToGroupOptions = {
    body: AddUsersToGroupBody;
    path: AddUsersToGroupPath;
    query?: never;
    headers?: never;
};

export type AddUsersToGroupResponses = {
    "200": AddUsersToGroupStatus200;
    "400": AddUsersToGroupStatus400;
    "401": AddUsersToGroupStatus401;
    "403": AddUsersToGroupStatus403;
    "404": AddUsersToGroupStatus404;
};
