/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type AddUsersToGroupResponse = {
    /**
     * @description
     * Format: `int32`
    */
    addedCount: (number | string);
    alreadyMemberUserIds: string[];
};
