/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdjustProductStockCommand } from './AdjustProductStockCommand'

export type AdjustProductStockPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    productId: string;
};

export type AdjustProductStockStatus200 = unknown;

export type AdjustProductStockBody = AdjustProductStockCommand;

export type AdjustProductStockOptions = {
    body: AdjustProductStockBody;
    path: AdjustProductStockPath;
    query?: never;
    headers?: never;
};

export type AdjustProductStockResponses = {
    "200": AdjustProductStockStatus200;
};

/**
 * @description Union of all possible responses
*/
export type AdjustProductStockResponse = AdjustProductStockStatus200;
