/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type AdjustProductStockCommand = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    productId: string;
    /**
     * @description
     * Format: `int32`
    */
    delta: (number | string);
};
