/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdjustTenantValidityCommand } from './AdjustTenantValidityCommand'
import type { AdjustTenantValidityCommandResponse } from './AdjustTenantValidityCommandResponse'

export type AdjustTenantValidityPath = {
    id: string;
};

export type AdjustTenantValidityStatus200 = AdjustTenantValidityCommandResponse;

export type AdjustTenantValidityStatus400 = unknown;

export type AdjustTenantValidityStatus401 = unknown;

export type AdjustTenantValidityStatus403 = unknown;

export type AdjustTenantValidityBody = AdjustTenantValidityCommand;

export type AdjustTenantValidityOptions = {
    body: AdjustTenantValidityBody;
    path: AdjustTenantValidityPath;
    query?: never;
    headers?: never;
};

export type AdjustTenantValidityResponses = {
    "200": AdjustTenantValidityStatus200;
    "400": AdjustTenantValidityStatus400;
    "401": AdjustTenantValidityStatus401;
    "403": AdjustTenantValidityStatus403;
};

/**
 * @description Union of all possible responses
*/
export type AdjustTenantValidityResponse = (AdjustTenantValidityStatus200 | AdjustTenantValidityStatus400 | AdjustTenantValidityStatus401 | AdjustTenantValidityStatus403);
