/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type AdjustTenantValidityCommandResponse = {
    tenantId: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    validUpto: string;
};
