/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type AdminRevokeSessionPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    userId: string;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    sessionId: string;
};

export type AdminRevokeSessionStatus204 = unknown;

export type AdminRevokeSessionStatus401 = unknown;

export type AdminRevokeSessionStatus403 = unknown;

export type AdminRevokeSessionStatus404 = unknown;

export type AdminRevokeSessionOptions = {
    body?: never;
    path: AdminRevokeSessionPath;
    query?: never;
    headers?: never;
};

export type AdminRevokeSessionResponses = {
    "204": AdminRevokeSessionStatus204;
    "401": AdminRevokeSessionStatus401;
    "403": AdminRevokeSessionStatus403;
    "404": AdminRevokeSessionStatus404;
};

/**
 * @description Union of all possible responses
*/
export type AdminRevokeSessionResponse = (AdminRevokeSessionStatus204 | AdminRevokeSessionStatus401 | AdminRevokeSessionStatus403 | AdminRevokeSessionStatus404);
