/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type AllocatePositionBody = {
    positionId: string;
    /**
     * @description
     * Format: `int32`
    */
    headCount: (number | string) | null;
};
