/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ArchiveChannelPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type ArchiveChannelStatus200 = unknown;

export type ArchiveChannelOptions = {
    body?: never;
    path: ArchiveChannelPath;
    query?: never;
    headers?: never;
};

export type ArchiveChannelResponses = {
    "200": ArchiveChannelStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ArchiveChannelResponse = ArchiveChannelStatus200;
