/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type AssignTicketRequest = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    assigneeUserId: string | null;
};
