/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignSubscriptionCommand } from './AssignSubscriptionCommand'

export type AssignSubscriptionStatus200 = unknown;

export type AssignSubscriptionBody = AssignSubscriptionCommand;

export type AssignSubscriptionOptions = {
    body: AssignSubscriptionBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type AssignSubscriptionResponses = {
    "200": AssignSubscriptionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type AssignSubscriptionResponse = AssignSubscriptionStatus200;
