/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignTicketRequest } from './AssignTicketRequest'

export type AssignTicketPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ticketId: string;
};

export type AssignTicketStatus200 = unknown;

export type AssignTicketBody = AssignTicketRequest;

export type AssignTicketOptions = {
    body: AssignTicketBody;
    path: AssignTicketPath;
    query?: never;
    headers?: never;
};

export type AssignTicketResponses = {
    "200": AssignTicketStatus200;
};

/**
 * @description Union of all possible responses
*/
export type AssignTicketResponse = AssignTicketStatus200;
