/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const auditEventType = {
    None: "None",
    EntityChange: "EntityChange",
    Security: "Security",
    Activity: "Activity",
    Exception: "Exception"
} as const;

export type AuditEventTypeKey = (typeof auditEventType)[keyof typeof auditEventType];
