/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditEventTypeKey } from './AuditEventType'
import type { AuditSeverityKey } from './AuditSeverity'
import type { AuditTag } from './AuditTag'
import type { JsonElement } from './JsonElement'

export type AuditDetailDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    id?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    occurredAtUtc?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    receivedAtUtc?: string;
    eventType?: AuditEventTypeKey;
    severity?: AuditSeverityKey;
    tenantId?: string | null;
    userId?: string | null;
    userName?: string | null;
    traceId?: string | null;
    spanId?: string | null;
    correlationId?: string | null;
    requestId?: string | null;
    source?: string | null;
    tags?: AuditTag;
    payload?: JsonElement;
};
