/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CaptureUsageSnapshotsCommand } from './CaptureUsageSnapshotsCommand'
import type { UsageSnapshotDto } from './UsageSnapshotDto'

export type CaptureUsageSnapshotsStatus200 = UsageSnapshotDto[];

export type CaptureUsageSnapshotsStatus400 = unknown;

export type CaptureUsageSnapshotsStatus401 = unknown;

export type CaptureUsageSnapshotsStatus403 = unknown;

export type CaptureUsageSnapshotsBody = CaptureUsageSnapshotsCommand;

export type CaptureUsageSnapshotsOptions = {
    body: CaptureUsageSnapshotsBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CaptureUsageSnapshotsResponses = {
    "200": CaptureUsageSnapshotsStatus200;
    "400": CaptureUsageSnapshotsStatus400;
    "401": CaptureUsageSnapshotsStatus401;
    "403": CaptureUsageSnapshotsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type CaptureUsageSnapshotsResponse = (CaptureUsageSnapshotsStatus200 | CaptureUsageSnapshotsStatus400 | CaptureUsageSnapshotsStatus401 | CaptureUsageSnapshotsStatus403);
