/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CaptureUsageSnapshotsCommand = {
    tenantId: string;
    /**
     * @description
     * Format: `int32`
    */
    periodYear: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    periodMonth: (number | string);
};
