/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CategoryDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    name: string;
    slug: string;
    description: string | null;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    parentCategoryId: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAtUtc: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    updatedAtUtc: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    deletedOnUtc?: string | null;
    deletedBy?: string | null;
};
