/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChangeVisibilityRequest } from './ChangeVisibilityRequest'
import type { FileAssetDto } from './FileAssetDto'

export type ChangeFileVisibilityPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type ChangeFileVisibilityStatus200 = FileAssetDto;

export type ChangeFileVisibilityStatus401 = unknown;

export type ChangeFileVisibilityStatus403 = unknown;

export type ChangeFileVisibilityStatus404 = unknown;

export type ChangeFileVisibilityBody = ChangeVisibilityRequest;

export type ChangeFileVisibilityOptions = {
    body: ChangeFileVisibilityBody;
    path: ChangeFileVisibilityPath;
    query?: never;
    headers?: never;
};

export type ChangeFileVisibilityResponses = {
    "200": ChangeFileVisibilityStatus200;
    "401": ChangeFileVisibilityStatus401;
    "403": ChangeFileVisibilityStatus403;
    "404": ChangeFileVisibilityStatus404;
};

/**
 * @description Union of all possible responses
*/
export type ChangeFileVisibilityResponse = (ChangeFileVisibilityStatus200 | ChangeFileVisibilityStatus401 | ChangeFileVisibilityStatus403 | ChangeFileVisibilityStatus404);
