/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ConfirmEmailQuery = {
    userId: string;
    code: string;
    tenant: string;
};

export type ConfirmEmailStatus200 = unknown;

export type ConfirmEmailOptions = {
    body?: never;
    path?: never;
    query: ConfirmEmailQuery;
    headers?: never;
};

export type ConfirmEmailResponses = {
    "200": ConfirmEmailStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ConfirmEmailResponse = ConfirmEmailStatus200;
