/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateOrganizationUnitCommand } from './CreateOrganizationUnitCommand'
import type { OrganizationUnitDto } from './OrganizationUnitDto'

export type CreateOrganizationUnitStatus200 = OrganizationUnitDto;

export type CreateOrganizationUnitBody = CreateOrganizationUnitCommand;

export type CreateOrganizationUnitOptions = {
    body: CreateOrganizationUnitBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateOrganizationUnitResponses = {
    "200": CreateOrganizationUnitStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateOrganizationUnitResponse = CreateOrganizationUnitStatus200;
