/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateProductCommand } from './CreateProductCommand'

export type CreateProductStatus200 = unknown;

export type CreateProductBody = CreateProductCommand;

export type CreateProductOptions = {
    body: CreateProductBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateProductResponses = {
    "200": CreateProductStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateProductResponse = CreateProductStatus200;
