/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateCategoryCommand } from './CreateCategoryCommand'

export type CreateCategoryStatus200 = unknown;

export type CreateCategoryBody = CreateCategoryCommand;

export type CreateCategoryOptions = {
    body: CreateCategoryBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateCategoryResponses = {
    "200": CreateCategoryStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateCategoryResponse = CreateCategoryStatus200;
