/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateGroupCommand = {
    name: string;
    description: string | null;
    isDefault: boolean;
    roleIds: string[] | null;
};
