/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TicketPriorityKey } from './TicketPriority'

export type CreateTicketCommand = {
    title: string;
    description?: string | null;
    /**
     * @default 'Medium'
     * @type string | undefined
    */
    priority?: TicketPriorityKey;
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    assignedToUserId?: string | null;
};
