/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateGroupCommand } from './CreateGroupCommand'
import type { GroupDto } from './GroupDto'

export type CreateGroupStatus201 = GroupDto;

export type CreateGroupStatus400 = unknown;

export type CreateGroupStatus401 = unknown;

export type CreateGroupStatus403 = unknown;

export type CreateGroupBody = CreateGroupCommand;

export type CreateGroupOptions = {
    body: CreateGroupBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateGroupResponses = {
    "201": CreateGroupStatus201;
    "400": CreateGroupStatus400;
    "401": CreateGroupStatus401;
    "403": CreateGroupStatus403;
};

/**
 * @description Union of all possible responses
*/
export type CreateGroupResponse = (CreateGroupStatus201 | CreateGroupStatus400 | CreateGroupStatus401 | CreateGroupStatus403);
