/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateTicketCommand } from './CreateTicketCommand'

export type CreateTicketStatus200 = unknown;

export type CreateTicketBody = CreateTicketCommand;

export type CreateTicketOptions = {
    body: CreateTicketBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateTicketResponses = {
    "200": CreateTicketStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateTicketResponse = CreateTicketStatus200;
