/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreatePositionCommand = {
    code: string;
    name: string;
    description?: string | null;
    organizationId?: string | null;
};
