/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateTenantCommand = {
    id: string;
    name: string;
    connectionString: string | null;
    adminEmail: string;
    adminPassword: string;
    issuer: string | null;
    planKey?: string | null;
};
