/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateBrandCommand } from './CreateBrandCommand'

export type CreateBrandStatus200 = unknown;

export type CreateBrandBody = CreateBrandCommand;

export type CreateBrandOptions = {
    body: CreateBrandBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateBrandResponses = {
    "200": CreateBrandStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateBrandResponse = CreateBrandStatus200;
