/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreatePositionCommand } from './CreatePositionCommand'
import type { PositionDto } from './PositionDto'

export type CreatePositionStatus200 = PositionDto;

export type CreatePositionBody = CreatePositionCommand;

export type CreatePositionOptions = {
    body: CreatePositionBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreatePositionResponses = {
    "200": CreatePositionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreatePositionResponse = CreatePositionStatus200;
