/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateChannelCommand } from './CreateChannelCommand'

export type CreateChannelStatus200 = unknown;

export type CreateChannelBody = CreateChannelCommand;

export type CreateChannelOptions = {
    body: CreateChannelBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateChannelResponses = {
    "200": CreateChannelStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateChannelResponse = CreateChannelStatus200;
