/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanIntervalKey } from './PlanInterval'

export type CreatePlanCommand = {
    key: string;
    name: string;
    currency: string;
    /**
     * @description
     * Format: `double`
    */
    monthlyBasePrice: (number | string);
    overageRates?: {
        [key: string]: (number | string);
    } | null;
    interval?: PlanIntervalKey;
    /**
     * @description
     * Format: `double`
    */
    annualPrice?: (number | string) | null;
};
