/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateTenantCommand } from './CreateTenantCommand'
import type { CreateTenantCommandResponse } from './CreateTenantCommandResponse'

export type CreateTenantStatus201 = CreateTenantCommandResponse;

export type CreateTenantStatus400 = unknown;

export type CreateTenantStatus401 = unknown;

export type CreateTenantStatus403 = unknown;

export type CreateTenantBody = CreateTenantCommand;

export type CreateTenantOptions = {
    body: CreateTenantBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateTenantResponses = {
    "201": CreateTenantStatus201;
    "400": CreateTenantStatus400;
    "401": CreateTenantStatus401;
    "403": CreateTenantStatus403;
};

/**
 * @description Union of all possible responses
*/
export type CreateTenantResponse = (CreateTenantStatus201 | CreateTenantStatus400 | CreateTenantStatus401 | CreateTenantStatus403);
