/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RoleDto } from './RoleDto'
import type { UpsertRoleCommand } from './UpsertRoleCommand'

export type CreateOrUpdateRoleStatus200 = RoleDto;

export type CreateOrUpdateRoleStatus401 = unknown;

export type CreateOrUpdateRoleStatus403 = unknown;

export type CreateOrUpdateRoleBody = UpsertRoleCommand;

export type CreateOrUpdateRoleOptions = {
    body: CreateOrUpdateRoleBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateOrUpdateRoleResponses = {
    "200": CreateOrUpdateRoleStatus200;
    "401": CreateOrUpdateRoleStatus401;
    "403": CreateOrUpdateRoleStatus403;
};

/**
 * @description Union of all possible responses
*/
export type CreateOrUpdateRoleResponse = (CreateOrUpdateRoleStatus200 | CreateOrUpdateRoleStatus401 | CreateOrUpdateRoleStatus403);
