/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PositionDto } from './PositionDto'

export type DeletePositionPath = {
    /**
     * @minLength 11
     * @maxLength 11
     * @type string
    */
    positionId: string;
};

export type DeletePositionStatus200 = PositionDto;

export type DeletePositionOptions = {
    body?: never;
    path: DeletePositionPath;
    query?: never;
    headers?: never;
};

export type DeletePositionResponses = {
    "200": DeletePositionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeletePositionResponse = DeletePositionStatus200;
