/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteTicketPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ticketId: string;
};

export type DeleteTicketStatus200 = unknown;

export type DeleteTicketOptions = {
    body?: never;
    path: DeleteTicketPath;
    query?: never;
    headers?: never;
};

export type DeleteTicketResponses = {
    "200": DeleteTicketStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteTicketResponse = DeleteTicketStatus200;
