/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteMessagePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type DeleteMessageStatus200 = unknown;

export type DeleteMessageOptions = {
    body?: never;
    path: DeleteMessagePath;
    query?: never;
    headers?: never;
};

export type DeleteMessageResponses = {
    "200": DeleteMessageStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteMessageResponse = DeleteMessageStatus200;
