/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteFilePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type DeleteFileStatus200 = unknown;

export type DeleteFileOptions = {
    body?: never;
    path: DeleteFilePath;
    query?: never;
    headers?: never;
};

export type DeleteFileResponses = {
    "200": DeleteFileStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DeleteFileResponse = DeleteFileStatus200;
