/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteGroupPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type DeleteGroupStatus204 = unknown;

export type DeleteGroupStatus401 = unknown;

export type DeleteGroupStatus403 = unknown;

export type DeleteGroupOptions = {
    body?: never;
    path: DeleteGroupPath;
    query?: never;
    headers?: never;
};

export type DeleteGroupResponses = {
    "204": DeleteGroupStatus204;
    "401": DeleteGroupStatus401;
    "403": DeleteGroupStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteGroupResponse = (DeleteGroupStatus204 | DeleteGroupStatus401 | DeleteGroupStatus403);
