/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DiscoverChannelsQuery = {
    search?: string;
    /**
     * @description
     * Format: `int32`
    */
    page?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
};

export type DiscoverChannelsStatus200 = unknown;

export type DiscoverChannelsOptions = {
    body?: never;
    path?: never;
    query?: DiscoverChannelsQuery;
    headers?: never;
};

export type DiscoverChannelsResponses = {
    "200": DiscoverChannelsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type DiscoverChannelsResponse = DiscoverChannelsStatus200;
