/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TwoFactorEnrollmentResponse } from './TwoFactorEnrollmentResponse'

export type EnrollTwoFactorStatus200 = TwoFactorEnrollmentResponse;

export type EnrollTwoFactorStatus401 = unknown;

export type EnrollTwoFactorOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type EnrollTwoFactorResponses = {
    "200": EnrollTwoFactorStatus200;
    "401": EnrollTwoFactorStatus401;
};

/**
 * @description Union of all possible responses
*/
export type EnrollTwoFactorResponse = (EnrollTwoFactorStatus200 | EnrollTwoFactorStatus401);
