/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @description Represents a file upload request with filename, content type, and data.
 * @type object
*/
export type FileUploadRequest = {
    fileName?: string;
    contentType?: string;
    data?: (number | string)[];
};
