/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileAssetStatusKey } from './FileAssetStatus'
import type { VisibilityKey } from './Visibility'

export type FileAssetDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    ownerType: string;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ownerId: string | null;
    originalFileName: string;
    contentType: string;
    /**
     * @description
     * Format: `int64`
    */
    sizeBytes: (bigint | string);
    visibility: VisibilityKey;
    status: FileAssetStatusKey;
    /**
     * @description
     * Format: `int32`
    */
    scanStatus: (number | string);
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAtUtc: string;
    publicUrl: string | null;
    /**
     * @default ''
     * @type string | undefined
    */
    createdByUserId?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    deletedOnUtc?: string | null;
    deletedBy?: string | null;
};
