/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditEventTypeKey } from './AuditEventType'
import type { AuditSeverityKey } from './AuditSeverity'
import type { AuditTag } from './AuditTag'
import type { PagedResponseOfAuditSummaryDto } from './PagedResponseOfAuditSummaryDto'

export type GetAuditsQuery = {
    /**
     * @description
     * Format: `int32`
    */
    PageNumber?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    PageSize?: (number | string);
    Sort?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    FromUtc?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    ToUtc?: string;
    TenantId?: string;
    UserId?: string;
    EventType?: AuditEventTypeKey;
    ExcludeEventType?: AuditEventTypeKey;
    Severity?: AuditSeverityKey;
    Tags?: AuditTag;
    Source?: string;
    CorrelationId?: string;
    TraceId?: string;
    Search?: string;
};

export type GetAuditsStatus200 = PagedResponseOfAuditSummaryDto;

export type GetAuditsStatus401 = unknown;

export type GetAuditsStatus403 = unknown;

export type GetAuditsOptions = {
    body?: never;
    path?: never;
    query?: GetAuditsQuery;
    headers?: never;
};

export type GetAuditsResponses = {
    "200": GetAuditsStatus200;
    "401": GetAuditsStatus401;
    "403": GetAuditsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetAuditsResponse = (GetAuditsStatus200 | GetAuditsStatus401 | GetAuditsStatus403);
