/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditSummaryAggregateDto } from './AuditSummaryAggregateDto'

export type GetAuditSummaryQuery = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    FromUtc?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    ToUtc?: string;
    TenantId?: string;
};

export type GetAuditSummaryStatus200 = AuditSummaryAggregateDto;

export type GetAuditSummaryStatus401 = unknown;

export type GetAuditSummaryStatus403 = unknown;

export type GetAuditSummaryOptions = {
    body?: never;
    path?: never;
    query?: GetAuditSummaryQuery;
    headers?: never;
};

export type GetAuditSummaryResponses = {
    "200": GetAuditSummaryStatus200;
    "401": GetAuditSummaryStatus401;
    "403": GetAuditSummaryStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetAuditSummaryResponse = (GetAuditSummaryStatus200 | GetAuditSummaryStatus401 | GetAuditSummaryStatus403);
