/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OrganizationUnitDto } from './OrganizationUnitDto'

export type GetAllOrganizationsStatus200 = OrganizationUnitDto[];

export type GetAllOrganizationsOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetAllOrganizationsResponses = {
    "200": GetAllOrganizationsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetAllOrganizationsResponse = GetAllOrganizationsStatus200;
