/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditSummaryDto } from './AuditSummaryDto'

export type GetAuditsByTracePath = {
    traceId: string;
};

export type GetAuditsByTraceQuery = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    fromUtc?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    toUtc?: string;
};

export type GetAuditsByTraceStatus200 = AuditSummaryDto[];

export type GetAuditsByTraceStatus401 = unknown;

export type GetAuditsByTraceStatus403 = unknown;

export type GetAuditsByTraceOptions = {
    body?: never;
    path: GetAuditsByTracePath;
    query?: GetAuditsByTraceQuery;
    headers?: never;
};

export type GetAuditsByTraceResponses = {
    "200": GetAuditsByTraceStatus200;
    "401": GetAuditsByTraceStatus401;
    "403": GetAuditsByTraceStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetAuditsByTraceResponse = (GetAuditsByTraceStatus200 | GetAuditsByTraceStatus401 | GetAuditsByTraceStatus403);
