/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditDetailDto } from './AuditDetailDto'

export type GetAuditByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetAuditByIdStatus200 = AuditDetailDto;

export type GetAuditByIdStatus401 = unknown;

export type GetAuditByIdStatus403 = unknown;

export type GetAuditByIdStatus404 = unknown;

export type GetAuditByIdOptions = {
    body?: never;
    path: GetAuditByIdPath;
    query?: never;
    headers?: never;
};

export type GetAuditByIdResponses = {
    "200": GetAuditByIdStatus200;
    "401": GetAuditByIdStatus401;
    "403": GetAuditByIdStatus403;
    "404": GetAuditByIdStatus404;
};

/**
 * @description Union of all possible responses
*/
export type GetAuditByIdResponse = (GetAuditByIdStatus200 | GetAuditByIdStatus401 | GetAuditByIdStatus403 | GetAuditByIdStatus404);
