/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditSummaryDto } from './AuditSummaryDto'

export type GetAuditsByCorrelationPath = {
    correlationId: string;
};

export type GetAuditsByCorrelationQuery = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    fromUtc?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    toUtc?: string;
};

export type GetAuditsByCorrelationStatus200 = AuditSummaryDto[];

export type GetAuditsByCorrelationStatus401 = unknown;

export type GetAuditsByCorrelationStatus403 = unknown;

export type GetAuditsByCorrelationOptions = {
    body?: never;
    path: GetAuditsByCorrelationPath;
    query?: GetAuditsByCorrelationQuery;
    headers?: never;
};

export type GetAuditsByCorrelationResponses = {
    "200": GetAuditsByCorrelationStatus200;
    "401": GetAuditsByCorrelationStatus401;
    "403": GetAuditsByCorrelationStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetAuditsByCorrelationResponse = (GetAuditsByCorrelationStatus200 | GetAuditsByCorrelationStatus401 | GetAuditsByCorrelationStatus403);
