/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BrandDto } from './BrandDto'

export type GetBrandByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    brandId: string;
};

export type GetBrandByIdStatus200 = BrandDto;

export type GetBrandByIdOptions = {
    body?: never;
    path: GetBrandByIdPath;
    query?: never;
    headers?: never;
};

export type GetBrandByIdResponses = {
    "200": GetBrandByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetBrandByIdResponse = GetBrandByIdStatus200;
