/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BillingPlanDto } from './BillingPlanDto'

export type GetBillingPlansQuery = {
    includeInactive: boolean;
};

export type GetBillingPlansStatus200 = BillingPlanDto[];

export type GetBillingPlansOptions = {
    body?: never;
    path?: never;
    query: GetBillingPlansQuery;
    headers?: never;
};

export type GetBillingPlansResponses = {
    "200": GetBillingPlansStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetBillingPlansResponse = GetBillingPlansStatus200;
