/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserDto } from './UserDto'

export type GetCurrentUserProfileStatus200 = UserDto;

export type GetCurrentUserProfileStatus401 = unknown;

export type GetCurrentUserProfileOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetCurrentUserProfileResponses = {
    "200": GetCurrentUserProfileStatus200;
    "401": GetCurrentUserProfileStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetCurrentUserProfileResponse = (GetCurrentUserProfileStatus200 | GetCurrentUserProfileStatus401);
