/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetChannelByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetChannelByIdStatus200 = unknown;

export type GetChannelByIdOptions = {
    body?: never;
    path: GetChannelByIdPath;
    query?: never;
    headers?: never;
};

export type GetChannelByIdResponses = {
    "200": GetChannelByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetChannelByIdResponse = GetChannelByIdStatus200;
