/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoryDto } from './CategoryDto'

export type GetCategoryByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    categoryId: string;
};

export type GetCategoryByIdStatus200 = CategoryDto;

export type GetCategoryByIdOptions = {
    body?: never;
    path: GetCategoryByIdPath;
    query?: never;
    headers?: never;
};

export type GetCategoryByIdResponses = {
    "200": GetCategoryByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetCategoryByIdResponse = GetCategoryByIdStatus200;
