/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuditSeverityKey } from './AuditSeverity'
import type { AuditSummaryDto } from './AuditSummaryDto'
import type { ExceptionAreaKey } from './ExceptionArea'

export type GetExceptionAuditsQuery = {
    Area?: ExceptionAreaKey | null;
    Severity?: AuditSeverityKey;
    ExceptionType?: string;
    RouteOrLocation?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    FromUtc?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    ToUtc?: string;
};

export type GetExceptionAuditsStatus200 = AuditSummaryDto[];

export type GetExceptionAuditsStatus401 = unknown;

export type GetExceptionAuditsStatus403 = unknown;

export type GetExceptionAuditsOptions = {
    body?: never;
    path?: never;
    query?: GetExceptionAuditsQuery;
    headers?: never;
};

export type GetExceptionAuditsResponses = {
    "200": GetExceptionAuditsStatus200;
    "401": GetExceptionAuditsStatus401;
    "403": GetExceptionAuditsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetExceptionAuditsResponse = (GetExceptionAuditsStatus200 | GetExceptionAuditsStatus401 | GetExceptionAuditsStatus403);
