/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetFileMetadataPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetFileMetadataStatus200 = unknown;

export type GetFileMetadataOptions = {
    body?: never;
    path: GetFileMetadataPath;
    query?: never;
    headers?: never;
};

export type GetFileMetadataResponses = {
    "200": GetFileMetadataStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetFileMetadataResponse = GetFileMetadataStatus200;
