/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetFileDownloadUrlPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetFileDownloadUrlQuery = {
    inline?: boolean;
};

export type GetFileDownloadUrlStatus200 = unknown;

export type GetFileDownloadUrlOptions = {
    body?: never;
    path: GetFileDownloadUrlPath;
    query?: GetFileDownloadUrlQuery;
    headers?: never;
};

export type GetFileDownloadUrlResponses = {
    "200": GetFileDownloadUrlStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetFileDownloadUrlResponse = GetFileDownloadUrlStatus200;
