/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InvoiceDto } from './InvoiceDto'

export type GetInvoiceByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    invoiceId: string;
};

export type GetInvoiceByIdStatus200 = InvoiceDto;

export type GetInvoiceByIdOptions = {
    body?: never;
    path: GetInvoiceByIdPath;
    query?: never;
    headers?: never;
};

export type GetInvoiceByIdResponses = {
    "200": GetInvoiceByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetInvoiceByIdResponse = GetInvoiceByIdStatus200;
