/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserSessionDto } from './UserSessionDto'

export type GetMySessionsStatus200 = UserSessionDto[];

export type GetMySessionsStatus401 = unknown;

export type GetMySessionsStatus403 = unknown;

export type GetMySessionsOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetMySessionsResponses = {
    "200": GetMySessionsStatus200;
    "401": GetMySessionsStatus401;
    "403": GetMySessionsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetMySessionsResponse = (GetMySessionsStatus200 | GetMySessionsStatus401 | GetMySessionsStatus403);
