/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubscriptionDto } from './SubscriptionDto'

export type GetMySubscriptionStatus200 = SubscriptionDto;

export type GetMySubscriptionOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetMySubscriptionResponses = {
    "200": GetMySubscriptionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetMySubscriptionResponse = GetMySubscriptionStatus200;
