/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PositionDto } from './PositionDto'

export type GetPositionByIdPath = {
    /**
     * @minLength 11
     * @maxLength 11
     * @type string
    */
    positionId: string;
};

export type GetPositionByIdStatus200 = PositionDto;

export type GetPositionByIdOptions = {
    body?: never;
    path: GetPositionByIdPath;
    query?: never;
    headers?: never;
};

export type GetPositionByIdResponses = {
    "200": GetPositionByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetPositionByIdResponse = GetPositionByIdStatus200;
