/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProductDto } from './ProductDto'

export type GetProductByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    productId: string;
};

export type GetProductByIdStatus200 = ProductDto;

export type GetProductByIdOptions = {
    body?: never;
    path: GetProductByIdPath;
    query?: never;
    headers?: never;
};

export type GetProductByIdResponses = {
    "200": GetProductByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetProductByIdResponse = GetProductByIdStatus200;
