/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RoleDto } from './RoleDto'

export type GetRolePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetRoleStatus200 = RoleDto;

export type GetRoleStatus401 = unknown;

export type GetRoleStatus403 = unknown;

export type GetRoleStatus404 = unknown;

export type GetRoleOptions = {
    body?: never;
    path: GetRolePath;
    query?: never;
    headers?: never;
};

export type GetRoleResponses = {
    "200": GetRoleStatus200;
    "401": GetRoleStatus401;
    "403": GetRoleStatus403;
    "404": GetRoleStatus404;
};

/**
 * @description Union of all possible responses
*/
export type GetRoleResponse = (GetRoleStatus200 | GetRoleStatus401 | GetRoleStatus403 | GetRoleStatus404);
