/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubscriptionDto } from './SubscriptionDto'

export type GetSubscriptionQuery = {
    tenantId?: string;
};

export type GetSubscriptionStatus200 = SubscriptionDto;

export type GetSubscriptionOptions = {
    body?: never;
    path?: never;
    query?: GetSubscriptionQuery;
    headers?: never;
};

export type GetSubscriptionResponses = {
    "200": GetSubscriptionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetSubscriptionResponse = GetSubscriptionStatus200;
