/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedResponseOfUserSessionDto } from './PagedResponseOfUserSessionDto'

export type GetTenantSessionsQuery = {
    includeInactive?: boolean;
    search?: string;
    /**
     * @description
     * Format: `int32`
    */
    pageNumber?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
};

export type GetTenantSessionsStatus200 = PagedResponseOfUserSessionDto;

export type GetTenantSessionsStatus401 = unknown;

export type GetTenantSessionsStatus403 = unknown;

export type GetTenantSessionsOptions = {
    body?: never;
    path?: never;
    query?: GetTenantSessionsQuery;
    headers?: never;
};

export type GetTenantSessionsResponses = {
    "200": GetTenantSessionsStatus200;
    "401": GetTenantSessionsStatus401;
    "403": GetTenantSessionsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetTenantSessionsResponse = (GetTenantSessionsStatus200 | GetTenantSessionsStatus401 | GetTenantSessionsStatus403);
