/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TenantStatusDto } from './TenantStatusDto'

export type GetTenantStatusPath = {
    id: string;
};

export type GetTenantStatusStatus200 = TenantStatusDto;

export type GetTenantStatusStatus401 = unknown;

export type GetTenantStatusStatus403 = unknown;

export type GetTenantStatusStatus404 = unknown;

export type GetTenantStatusOptions = {
    body?: never;
    path: GetTenantStatusPath;
    query?: never;
    headers?: never;
};

export type GetTenantStatusResponses = {
    "200": GetTenantStatusStatus200;
    "401": GetTenantStatusStatus401;
    "403": GetTenantStatusStatus403;
    "404": GetTenantStatusStatus404;
};

/**
 * @description Union of all possible responses
*/
export type GetTenantStatusResponse = (GetTenantStatusStatus200 | GetTenantStatusStatus401 | GetTenantStatusStatus403 | GetTenantStatusStatus404);
