/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TenantMigrationStatusDto } from './TenantMigrationStatusDto'

export type GetTenantMigrationsStatus200 = TenantMigrationStatusDto[];

export type GetTenantMigrationsStatus401 = unknown;

export type GetTenantMigrationsStatus403 = unknown;

export type GetTenantMigrationsOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetTenantMigrationsResponses = {
    "200": GetTenantMigrationsStatus200;
    "401": GetTenantMigrationsStatus401;
    "403": GetTenantMigrationsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetTenantMigrationsResponse = (GetTenantMigrationsStatus200 | GetTenantMigrationsStatus401 | GetTenantMigrationsStatus403);
