/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetTicketByIdPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ticketId: string;
};

export type GetTicketByIdStatus200 = unknown;

export type GetTicketByIdOptions = {
    body?: never;
    path: GetTicketByIdPath;
    query?: never;
    headers?: never;
};

export type GetTicketByIdResponses = {
    "200": GetTicketByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetTicketByIdResponse = GetTicketByIdStatus200;
