/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GroupDto } from './GroupDto'

export type GetUserGroupsPath = {
    userId: string;
};

export type GetUserGroupsStatus200 = GroupDto[];

export type GetUserGroupsStatus401 = unknown;

export type GetUserGroupsStatus403 = unknown;

export type GetUserGroupsOptions = {
    body?: never;
    path: GetUserGroupsPath;
    query?: never;
    headers?: never;
};

export type GetUserGroupsResponses = {
    "200": GetUserGroupsStatus200;
    "401": GetUserGroupsStatus401;
    "403": GetUserGroupsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetUserGroupsResponse = (GetUserGroupsStatus200 | GetUserGroupsStatus401 | GetUserGroupsStatus403);
