/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserDto } from './UserDto'

export type GetUserPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetUserStatus200 = UserDto;

export type GetUserStatus401 = unknown;

export type GetUserStatus403 = unknown;

export type GetUserStatus404 = unknown;

export type GetUserOptions = {
    body?: never;
    path: GetUserPath;
    query?: never;
    headers?: never;
};

export type GetUserResponses = {
    "200": GetUserStatus200;
    "401": GetUserStatus401;
    "403": GetUserStatus403;
    "404": GetUserStatus404;
};

/**
 * @description Union of all possible responses
*/
export type GetUserResponse = (GetUserStatus200 | GetUserStatus401 | GetUserStatus403 | GetUserStatus404);
