/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserRoleDto } from './UserRoleDto'

export type GetUserRolesPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type GetUserRolesStatus200 = UserRoleDto[];

export type GetUserRolesStatus401 = unknown;

export type GetUserRolesStatus403 = unknown;

export type GetUserRolesStatus404 = unknown;

export type GetUserRolesOptions = {
    body?: never;
    path: GetUserRolesPath;
    query?: never;
    headers?: never;
};

export type GetUserRolesResponses = {
    "200": GetUserRolesStatus200;
    "401": GetUserRolesStatus401;
    "403": GetUserRolesStatus403;
    "404": GetUserRolesStatus404;
};

/**
 * @description Union of all possible responses
*/
export type GetUserRolesResponse = (GetUserRolesStatus200 | GetUserRolesStatus401 | GetUserRolesStatus403 | GetUserRolesStatus404);
