/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedResponseOfWebhookDeliveryDto } from './PagedResponseOfWebhookDeliveryDto'

export type GetWebhookDeliveriesPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    subscriptionId: string;
};

export type GetWebhookDeliveriesQuery = {
    /**
     * @description
     * Format: `int32`
    */
    pageNumber: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize: (number | string);
};

export type GetWebhookDeliveriesStatus200 = PagedResponseOfWebhookDeliveryDto;

export type GetWebhookDeliveriesOptions = {
    body?: never;
    path: GetWebhookDeliveriesPath;
    query: GetWebhookDeliveriesQuery;
    headers?: never;
};

export type GetWebhookDeliveriesResponses = {
    "200": GetWebhookDeliveriesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetWebhookDeliveriesResponse = GetWebhookDeliveriesStatus200;
