/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedResponseOfWebhookSubscriptionDto } from './PagedResponseOfWebhookSubscriptionDto'

export type GetWebhookSubscriptionsQuery = {
    /**
     * @description
     * Format: `int32`
    */
    pageNumber: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize: (number | string);
};

export type GetWebhookSubscriptionsStatus200 = PagedResponseOfWebhookSubscriptionDto;

export type GetWebhookSubscriptionsOptions = {
    body?: never;
    path?: never;
    query: GetWebhookSubscriptionsQuery;
    headers?: never;
};

export type GetWebhookSubscriptionsResponses = {
    "200": GetWebhookSubscriptionsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetWebhookSubscriptionsResponse = GetWebhookSubscriptionsStatus200;
