/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthEntry } from './HealthEntry'

export type HealthResult = {
    status: string;
    results: HealthEntry[];
};
