/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const invoiceLineItemKind = {
    BaseFee: "BaseFee",
    Overage: "Overage",
    Adjustment: "Adjustment"
} as const;

export type InvoiceLineItemKindKey = (typeof invoiceLineItemKind)[keyof typeof invoiceLineItemKind];
