/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InvoiceLineItemKindKey } from './InvoiceLineItemKind'
import type { QuotaResourceKey } from './QuotaResource'

export type InvoiceLineItemDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    kind: InvoiceLineItemKindKey;
    resource: (null | QuotaResourceKey);
    description: string;
    /**
     * @description
     * Format: `double`
    */
    quantity: (number | string);
    /**
     * @description
     * Format: `double`
    */
    unitPrice: (number | string);
    /**
     * @description
     * Format: `double`
    */
    amount: (number | string);
};
