/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type IssueInvoicePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    invoiceId: string;
};

export type IssueInvoiceStatus200 = unknown;

export type IssueInvoiceBody = (null | IssueInvoiceBody) | undefined;

export type IssueInvoiceOptions = {
    body: IssueInvoiceBody;
    path: IssueInvoicePath;
    query?: never;
    headers?: never;
};

export type IssueInvoiceResponses = {
    "200": IssueInvoiceStatus200;
};

/**
 * @description Union of all possible responses
*/
export type IssueInvoiceResponse = IssueInvoiceStatus200;
