/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GenerateTokenCommand } from './GenerateTokenCommand'
import type { TokenResponse } from './TokenResponse'

export type IssueJwtTokensHeaders = {
    /**
     * @default 'root'
     * @type string
    */
    tenant: string;
    "X-FSH-App"?: string;
};

export type IssueJwtTokensStatus200 = TokenResponse;

export type IssueJwtTokensStatus400 = unknown;

export type IssueJwtTokensStatus401 = unknown;

export type IssueJwtTokensStatus403 = unknown;

export type IssueJwtTokensStatus500 = unknown;

export type IssueJwtTokensBody = GenerateTokenCommand;

export type IssueJwtTokensOptions = {
    body: IssueJwtTokensBody;
    path?: never;
    query?: never;
    headers: IssueJwtTokensHeaders;
};

export type IssueJwtTokensResponses = {
    "200": IssueJwtTokensStatus200;
    "400": IssueJwtTokensStatus400;
    "401": IssueJwtTokensStatus401;
    "403": IssueJwtTokensStatus403;
    "500": IssueJwtTokensStatus500;
};

/**
 * @description Union of all possible responses
*/
export type IssueJwtTokensResponse = (IssueJwtTokensStatus200 | IssueJwtTokensStatus400 | IssueJwtTokensStatus401 | IssueJwtTokensStatus403 | IssueJwtTokensStatus500);
