/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListChannelMessagesPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type ListChannelMessagesQuery = {
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    before?: string;
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
};

export type ListChannelMessagesStatus200 = unknown;

export type ListChannelMessagesOptions = {
    body?: never;
    path: ListChannelMessagesPath;
    query?: ListChannelMessagesQuery;
    headers?: never;
};

export type ListChannelMessagesResponses = {
    "200": ListChannelMessagesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListChannelMessagesResponse = ListChannelMessagesStatus200;
