/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListPinnedMessagesPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type ListPinnedMessagesStatus200 = unknown;

export type ListPinnedMessagesOptions = {
    body?: never;
    path: ListPinnedMessagesPath;
    query?: never;
    headers?: never;
};

export type ListPinnedMessagesResponses = {
    "200": ListPinnedMessagesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListPinnedMessagesResponse = ListPinnedMessagesStatus200;
