/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListTrashedCategoriesQuery = {
    /**
     * @description
     * Format: `int32`
    */
    pageNumber?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
};

export type ListTrashedCategoriesStatus200 = unknown;

export type ListTrashedCategoriesOptions = {
    body?: never;
    path?: never;
    query?: ListTrashedCategoriesQuery;
    headers?: never;
};

export type ListTrashedCategoriesResponses = {
    "200": ListTrashedCategoriesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListTrashedCategoriesResponse = ListTrashedCategoriesStatus200;
