/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListNotificationsQuery = {
    unreadOnly?: boolean;
    /**
     * @description
     * Format: `int32`
    */
    page?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
};

export type ListNotificationsStatus200 = unknown;

export type ListNotificationsOptions = {
    body?: never;
    path?: never;
    query?: ListNotificationsQuery;
    headers?: never;
};

export type ListNotificationsResponses = {
    "200": ListNotificationsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListNotificationsResponse = ListNotificationsStatus200;
