/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListTicketCommentsPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ticketId: string;
};

export type ListTicketCommentsStatus200 = unknown;

export type ListTicketCommentsOptions = {
    body?: never;
    path: ListTicketCommentsPath;
    query?: never;
    headers?: never;
};

export type ListTicketCommentsResponses = {
    "200": ListTicketCommentsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListTicketCommentsResponse = ListTicketCommentsStatus200;
