/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ListMyFilesQuery = {
    /**
     * @description
     * Format: `int32`
    */
    page?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
};

export type ListMyFilesStatus200 = unknown;

export type ListMyFilesOptions = {
    body?: never;
    path?: never;
    query?: ListMyFilesQuery;
    headers?: never;
};

export type ListMyFilesResponses = {
    "200": ListMyFilesStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListMyFilesResponse = ListMyFilesStatus200;
