/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GroupDto } from './GroupDto'

export type ListGroupsQuery = {
    search?: string;
};

export type ListGroupsStatus200 = GroupDto[];

export type ListGroupsOptions = {
    body?: never;
    path?: never;
    query?: ListGroupsQuery;
    headers?: never;
};

export type ListGroupsResponses = {
    "200": ListGroupsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ListGroupsResponse = ListGroupsStatus200;
