/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthResult } from './HealthResult'

export type LivenessStatus200 = HealthResult;

export type LivenessOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type LivenessResponses = {
    "200": LivenessStatus200;
};

/**
 * @description Union of all possible responses
*/
export type LivenessResponse = LivenessStatus200;
