/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type MarkChannelReadBody = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    messageId: string;
};
