/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type MarkAllNotificationsReadStatus200 = unknown;

export type MarkAllNotificationsReadOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type MarkAllNotificationsReadResponses = {
    "200": MarkAllNotificationsReadStatus200;
};

/**
 * @description Union of all possible responses
*/
export type MarkAllNotificationsReadResponse = MarkAllNotificationsReadStatus200;
