/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProductDto } from './ProductDto'

export type PagedResponseOfProductDto = {
    items?: ProductDto[];
    /**
     * @description
     * Format: `int32`
    */
    pageNumber?: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize?: (number | string);
    /**
     * @description
     * Format: `int64`
    */
    totalCount?: (bigint | string);
    /**
     * @description
     * Format: `int32`
    */
    totalPages?: (number | string);
    hasNext?: boolean;
    hasPrevious?: boolean;
};
