/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type PaletteDto = {
    primary?: string;
    secondary?: string;
    tertiary?: string;
    background?: string;
    surface?: string;
    error?: string;
    warning?: string;
    success?: string;
    info?: string;
};
