/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type PinMessagePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type PinMessageStatus200 = unknown;

export type PinMessageOptions = {
    body?: never;
    path: PinMessagePath;
    query?: never;
    headers?: never;
};

export type PinMessageResponses = {
    "200": PinMessageStatus200;
};

/**
 * @description Union of all possible responses
*/
export type PinMessageResponse = PinMessageStatus200;
