/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AllocatePositionBody } from './AllocatePositionBody'
import type { OrganizationUnitPositionAllocationDto } from './OrganizationUnitPositionAllocationDto'

export type PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsPath = {
    /**
     * @minLength 11
     * @maxLength 11
     * @type string
    */
    organizationUnitId: string;
};

export type PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200 = OrganizationUnitPositionAllocationDto;

export type PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsBody = AllocatePositionBody;

export type PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsOptions = {
    body: PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsBody;
    path: PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsPath;
    query?: never;
    headers?: never;
};

export type PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponses = {
    "200": PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponse = PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200;
