/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OrganizationUnitPositionAllocationDto } from './OrganizationUnitPositionAllocationDto'

export type PostApiV1OrganizationsPositionAllocationsAllocationidEndPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    allocationId: string;
};

export type PostApiV1OrganizationsPositionAllocationsAllocationidEndStatus200 = OrganizationUnitPositionAllocationDto;

export type PostApiV1OrganizationsPositionAllocationsAllocationidEndOptions = {
    body?: never;
    path: PostApiV1OrganizationsPositionAllocationsAllocationidEndPath;
    query?: never;
    headers?: never;
};

export type PostApiV1OrganizationsPositionAllocationsAllocationidEndResponses = {
    "200": PostApiV1OrganizationsPositionAllocationsAllocationidEndStatus200;
};

/**
 * @description Union of all possible responses
*/
export type PostApiV1OrganizationsPositionAllocationsAllocationidEndResponse = PostApiV1OrganizationsPositionAllocationsAllocationidEndStatus200;
