/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChangePositionAllocationBody } from './ChangePositionAllocationBody'
import type { OrganizationUnitPositionAllocationDto } from './OrganizationUnitPositionAllocationDto'

export type PostApiV1OrganizationsPositionAllocationsAllocationidChangePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    allocationId: string;
};

export type PostApiV1OrganizationsPositionAllocationsAllocationidChangeStatus200 = OrganizationUnitPositionAllocationDto;

export type PostApiV1OrganizationsPositionAllocationsAllocationidChangeBody = ChangePositionAllocationBody;

export type PostApiV1OrganizationsPositionAllocationsAllocationidChangeOptions = {
    body: PostApiV1OrganizationsPositionAllocationsAllocationidChangeBody;
    path: PostApiV1OrganizationsPositionAllocationsAllocationidChangePath;
    query?: never;
    headers?: never;
};

export type PostApiV1OrganizationsPositionAllocationsAllocationidChangeResponses = {
    "200": PostApiV1OrganizationsPositionAllocationsAllocationidChangeStatus200;
};

/**
 * @description Union of all possible responses
*/
export type PostApiV1OrganizationsPositionAllocationsAllocationidChangeResponse = PostApiV1OrganizationsPositionAllocationsAllocationidChangeStatus200;
