/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ProductImageDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    fileAssetId: string | null;
    url: string;
    isThumbnail: boolean;
    /**
     * @description
     * Format: `int32`
    */
    sortOrder: (number | string);
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAtUtc: string;
};
