/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const quotaResource = {
    ApiCalls: "ApiCalls",
    StorageBytes: "StorageBytes",
    Users: "Users",
    ActiveFeatureFlags: "ActiveFeatureFlags"
} as const;

export type QuotaResourceKey = (typeof quotaResource)[keyof typeof quotaResource];
