/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthResult } from './HealthResult'

export type ReadinessStatus200 = HealthResult;

export type ReadinessStatus503 = HealthResult;

export type ReadinessOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type ReadinessResponses = {
    "200": ReadinessStatus200;
    "503": ReadinessStatus503;
};

/**
 * @description Union of all possible responses
*/
export type ReadinessResponse = (ReadinessStatus200 | ReadinessStatus503);
