/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RefreshTokenCommandResponse = {
    token: string;
    refreshToken: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    refreshTokenExpiryTime: string;
};
