/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RemoveProductImagePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    productId: string;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    imageId: string;
};

export type RemoveProductImageStatus204 = unknown;

export type RemoveProductImageStatus404 = unknown;

export type RemoveProductImageOptions = {
    body?: never;
    path: RemoveProductImagePath;
    query?: never;
    headers?: never;
};

export type RemoveProductImageResponses = {
    "204": RemoveProductImageStatus204;
    "404": RemoveProductImageStatus404;
};

/**
 * @description Union of all possible responses
*/
export type RemoveProductImageResponse = (RemoveProductImageStatus204 | RemoveProductImageStatus404);
