/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RemoveReactionPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    emoji: string;
};

export type RemoveReactionStatus200 = unknown;

export type RemoveReactionOptions = {
    body?: never;
    path: RemoveReactionPath;
    query?: never;
    headers?: never;
};

export type RemoveReactionResponses = {
    "200": RemoveReactionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type RemoveReactionResponse = RemoveReactionStatus200;
