/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RemoveUserFromGroupPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    groupId: string;
    userId: string;
};

export type RemoveUserFromGroupStatus204 = unknown;

export type RemoveUserFromGroupStatus401 = unknown;

export type RemoveUserFromGroupStatus403 = unknown;

export type RemoveUserFromGroupOptions = {
    body?: never;
    path: RemoveUserFromGroupPath;
    query?: never;
    headers?: never;
};

export type RemoveUserFromGroupResponses = {
    "204": RemoveUserFromGroupStatus204;
    "401": RemoveUserFromGroupStatus401;
    "403": RemoveUserFromGroupStatus403;
};

/**
 * @description Union of all possible responses
*/
export type RemoveUserFromGroupResponse = (RemoveUserFromGroupStatus204 | RemoveUserFromGroupStatus401 | RemoveUserFromGroupStatus403);
