/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ReopenTicketPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ticketId: string;
};

export type ReopenTicketStatus200 = unknown;

export type ReopenTicketOptions = {
    body?: never;
    path: ReopenTicketPath;
    query?: never;
    headers?: never;
};

export type ReopenTicketResponses = {
    "200": ReopenTicketStatus200;
};

/**
 * @description Union of all possible responses
*/
export type ReopenTicketResponse = ReopenTicketStatus200;
