/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestUploadUrlCommand } from './RequestUploadUrlCommand'

export type RequestFileUploadUrlStatus200 = unknown;

export type RequestFileUploadUrlBody = RequestUploadUrlCommand;

export type RequestFileUploadUrlOptions = {
    body: RequestFileUploadUrlBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type RequestFileUploadUrlResponses = {
    "200": RequestFileUploadUrlStatus200;
};

/**
 * @description Union of all possible responses
*/
export type RequestFileUploadUrlResponse = RequestFileUploadUrlStatus200;
