/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type ResendConfirmationEmailPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type ResendConfirmationEmailStatus204 = unknown;

export type ResendConfirmationEmailStatus401 = unknown;

export type ResendConfirmationEmailStatus403 = unknown;

export type ResendConfirmationEmailStatus404 = unknown;

export type ResendConfirmationEmailOptions = {
    body?: never;
    path: ResendConfirmationEmailPath;
    query?: never;
    headers?: never;
};

export type ResendConfirmationEmailResponses = {
    "204": ResendConfirmationEmailStatus204;
    "401": ResendConfirmationEmailStatus401;
    "403": ResendConfirmationEmailStatus403;
    "404": ResendConfirmationEmailStatus404;
};

/**
 * @description Union of all possible responses
*/
export type ResendConfirmationEmailResponse = (ResendConfirmationEmailStatus204 | ResendConfirmationEmailStatus401 | ResendConfirmationEmailStatus403 | ResendConfirmationEmailStatus404);
