/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RestoreBrandPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    brandId: string;
};

export type RestoreBrandStatus200 = unknown;

export type RestoreBrandOptions = {
    body?: never;
    path: RestoreBrandPath;
    query?: never;
    headers?: never;
};

export type RestoreBrandResponses = {
    "200": RestoreBrandStatus200;
};

/**
 * @description Union of all possible responses
*/
export type RestoreBrandResponse = RestoreBrandStatus200;
