/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RestoreTicketPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    ticketId: string;
};

export type RestoreTicketStatus200 = unknown;

export type RestoreTicketOptions = {
    body?: never;
    path: RestoreTicketPath;
    query?: never;
    headers?: never;
};

export type RestoreTicketResponses = {
    "200": RestoreTicketStatus200;
};

/**
 * @description Union of all possible responses
*/
export type RestoreTicketResponse = RestoreTicketStatus200;
