/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RestoreCategoryPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    categoryId: string;
};

export type RestoreCategoryStatus200 = unknown;

export type RestoreCategoryOptions = {
    body?: never;
    path: RestoreCategoryPath;
    query?: never;
    headers?: never;
};

export type RestoreCategoryResponses = {
    "200": RestoreCategoryStatus200;
};

/**
 * @description Union of all possible responses
*/
export type RestoreCategoryResponse = RestoreCategoryStatus200;
