/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RestoreChannelPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type RestoreChannelStatus200 = unknown;

export type RestoreChannelOptions = {
    body?: never;
    path: RestoreChannelPath;
    query?: never;
    headers?: never;
};

export type RestoreChannelResponses = {
    "200": RestoreChannelStatus200;
};

/**
 * @description Union of all possible responses
*/
export type RestoreChannelResponse = RestoreChannelStatus200;
