/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type RevokeAllSessionsCommand = {
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    exceptSessionId?: string | null;
};
