/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedResponseOfProductDto } from './PagedResponseOfProductDto'

export type SearchProductsQuery = {
    search?: string;
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    brandId?: string;
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    categoryId?: string;
    isActive?: boolean;
    /**
     * @description
     * Format: `int32`
    */
    pageNumber: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize: (number | string);
    sortBy?: string;
    sortDir?: string;
};

export type SearchProductsStatus200 = PagedResponseOfProductDto;

export type SearchProductsOptions = {
    body?: never;
    path?: never;
    query: SearchProductsQuery;
    headers?: never;
};

export type SearchProductsResponses = {
    "200": SearchProductsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type SearchProductsResponse = SearchProductsStatus200;
