/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedResponseOfBrandDto } from './PagedResponseOfBrandDto'

export type SearchBrandsQuery = {
    search?: string;
    /**
     * @description
     * Format: `int32`
    */
    pageNumber: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    pageSize: (number | string);
    sortBy?: string;
    sortDir?: string;
};

export type SearchBrandsStatus200 = PagedResponseOfBrandDto;

export type SearchBrandsOptions = {
    body?: never;
    path?: never;
    query: SearchBrandsQuery;
    headers?: never;
};

export type SearchBrandsResponses = {
    "200": SearchBrandsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type SearchBrandsResponse = SearchBrandsStatus200;
