/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const securityAction = {
    None: "None",
    LoginSucceeded: "LoginSucceeded",
    LoginFailed: "LoginFailed",
    TokenIssued: "TokenIssued",
    TokenRevoked: "TokenRevoked",
    PasswordChanged: "PasswordChanged",
    RoleAssigned: "RoleAssigned",
    RoleRevoked: "RoleRevoked",
    PermissionDenied: "PermissionDenied",
    PolicyFailed: "PolicyFailed",
    ImpersonationStarted: "ImpersonationStarted",
    ImpersonationEnded: "ImpersonationEnded"
} as const;

export type SecurityActionKey = (typeof securityAction)[keyof typeof securityAction];
