/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegisterUserCommand } from './RegisterUserCommand'
import type { RegisterUserResponse } from './RegisterUserResponse'

export type SelfRegisterUserHeaders = {
    tenant: string;
};

export type SelfRegisterUserStatus201 = RegisterUserResponse;

export type SelfRegisterUserStatus400 = unknown;

export type SelfRegisterUserBody = RegisterUserCommand;

export type SelfRegisterUserOptions = {
    body: SelfRegisterUserBody;
    path?: never;
    query?: never;
    headers: SelfRegisterUserHeaders;
};

export type SelfRegisterUserResponses = {
    "201": SelfRegisterUserStatus201;
    "400": SelfRegisterUserStatus400;
};

/**
 * @description Union of all possible responses
*/
export type SelfRegisterUserResponse = (SelfRegisterUserStatus201 | SelfRegisterUserStatus400);
