/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type SendMessagePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type SendMessageStatus200 = unknown;

export type SendMessageBody = SendMessageBody;

export type SendMessageOptions = {
    body: SendMessageBody;
    path: SendMessagePath;
    query?: never;
    headers?: never;
};

export type SendMessageResponses = {
    "200": SendMessageStatus200;
};

/**
 * @description Union of all possible responses
*/
export type SendMessageResponse = SendMessageStatus200;
