/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type SendMessageAttachmentInput = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    fileAssetId: string | null;
    url: string;
    contentType: string;
    fileName: string;
    /**
     * @description
     * Format: `int64`
    */
    sizeBytes: (bigint | string);
};
