/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SendMessageAttachmentInput } from './SendMessageAttachmentInput'

export type SendMessageBody = {
    body: string | null;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    parentMessageId: string | null;
    attachments: SendMessageAttachmentInput[] | null;
};
