/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SetProfileImageCommand } from './SetProfileImageCommand'

export type SetProfileImageStatus204 = unknown;

export type SetProfileImageStatus400 = unknown;

export type SetProfileImageStatus401 = unknown;

export type SetProfileImageBody = SetProfileImageCommand;

export type SetProfileImageOptions = {
    body: SetProfileImageBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type SetProfileImageResponses = {
    "204": SetProfileImageStatus204;
    "400": SetProfileImageStatus400;
    "401": SetProfileImageStatus401;
};

/**
 * @description Union of all possible responses
*/
export type SetProfileImageResponse = (SetProfileImageStatus204 | SetProfileImageStatus400 | SetProfileImageStatus401);
