/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubscriptionStatusKey } from './SubscriptionStatus'

export type SubscriptionDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    tenantId: string;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    planId: string;
    planKey: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    startUtc: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    endUtc: string | null;
    status: SubscriptionStatusKey;
};
