/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TenantProvisioningStepDto } from './TenantProvisioningStepDto'

export type TenantProvisioningStatusDto = {
    tenantId: string;
    status: string;
    correlationId: string;
    currentStep: string | null;
    error: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdUtc: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    startedUtc: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    completedUtc: string | null;
    steps: TenantProvisioningStepDto[];
};
