/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type TenantMigrationStatusDto = {
    tenantId?: string;
    name?: string;
    isActive?: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    validUpto?: string | null;
    hasPendingMigrations?: boolean;
    provider?: string | null;
    lastAppliedMigration?: string | null;
    pendingMigrations?: string[];
    error?: string | null;
};
