/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type TenantStatusDto = {
    id?: string;
    name?: string;
    isActive?: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    validUpto?: string;
    hasConnectionString?: boolean;
    adminEmail?: string;
    issuer?: string | null;
    plan?: string | null;
    expiryState?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    graceEndsUtc?: string;
};
