/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type TenantLifecycleResultDto = {
    tenantId?: string;
    isActive?: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    validUpto?: string | null;
    message?: string;
};
