/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BrandAssetsDto } from './BrandAssetsDto'
import type { LayoutDto } from './LayoutDto'
import type { PaletteDto } from './PaletteDto'
import type { TypographyDto } from './TypographyDto'

export type TenantThemeDto = {
    lightPalette?: PaletteDto;
    darkPalette?: PaletteDto;
    brandAssets?: BrandAssetsDto;
    typography?: TypographyDto;
    layout?: LayoutDto;
    isDefault?: boolean;
};
