/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AnonymousTypeOfboolean } from './AnonymousTypeOfboolean'

export type TestWebhookSubscriptionPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type TestWebhookSubscriptionStatus200 = AnonymousTypeOfboolean;

export type TestWebhookSubscriptionOptions = {
    body?: never;
    path: TestWebhookSubscriptionPath;
    query?: never;
    headers?: never;
};

export type TestWebhookSubscriptionResponses = {
    "200": TestWebhookSubscriptionStatus200;
};

/**
 * @description Union of all possible responses
*/
export type TestWebhookSubscriptionResponse = TestWebhookSubscriptionStatus200;
