/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const ticketPriority = {
    Low: "Low",
    Medium: "Medium",
    High: "High",
    Critical: "Critical"
} as const;

export type TicketPriorityKey = (typeof ticketPriority)[keyof typeof ticketPriority];
