/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const ticketStatus = {
    Open: "Open",
    InProgress: "InProgress",
    Resolved: "Resolved",
    Closed: "Closed"
} as const;

export type TicketStatusKey = (typeof ticketStatus)[keyof typeof ticketStatus];
