/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ToggleUserStatusCommand } from './ToggleUserStatusCommand'

export type ToggleUserStatusPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type ToggleUserStatusStatus204 = unknown;

export type ToggleUserStatusStatus400 = unknown;

export type ToggleUserStatusStatus401 = unknown;

export type ToggleUserStatusStatus403 = unknown;

export type ToggleUserStatusBody = ToggleUserStatusCommand;

export type ToggleUserStatusOptions = {
    body: ToggleUserStatusBody;
    path: ToggleUserStatusPath;
    query?: never;
    headers?: never;
};

export type ToggleUserStatusResponses = {
    "204": ToggleUserStatusStatus204;
    "400": ToggleUserStatusStatus400;
    "401": ToggleUserStatusStatus401;
    "403": ToggleUserStatusStatus403;
};

/**
 * @description Union of all possible responses
*/
export type ToggleUserStatusResponse = (ToggleUserStatusStatus204 | ToggleUserStatusStatus400 | ToggleUserStatusStatus401 | ToggleUserStatusStatus403);
