/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type TypographyDto = {
    fontFamily?: string;
    headingFontFamily?: string;
    /**
     * @description
     * Format: `double`
    */
    fontSizeBase?: (number | string);
    /**
     * @description
     * Format: `double`
    */
    lineHeightBase?: (number | string);
};
