/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdatePermissionsCommand } from './UpdatePermissionsCommand'

export type UpdateRolePermissionsPath = {
    id: string;
};

export type UpdateRolePermissionsStatus200 = string;

export type UpdateRolePermissionsStatus400 = unknown;

export type UpdateRolePermissionsStatus401 = unknown;

export type UpdateRolePermissionsStatus403 = unknown;

export type UpdateRolePermissionsStatus404 = unknown;

export type UpdateRolePermissionsBody = UpdatePermissionsCommand;

export type UpdateRolePermissionsOptions = {
    body: UpdateRolePermissionsBody;
    path: UpdateRolePermissionsPath;
    query?: never;
    headers?: never;
};

export type UpdateRolePermissionsResponses = {
    "200": UpdateRolePermissionsStatus200;
    "400": UpdateRolePermissionsStatus400;
    "401": UpdateRolePermissionsStatus401;
    "403": UpdateRolePermissionsStatus403;
    "404": UpdateRolePermissionsStatus404;
};

/**
 * @description Union of all possible responses
*/
export type UpdateRolePermissionsResponse = (UpdateRolePermissionsStatus200 | UpdateRolePermissionsStatus400 | UpdateRolePermissionsStatus401 | UpdateRolePermissionsStatus403 | UpdateRolePermissionsStatus404);
