/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateBrandCommand = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    brandId: string;
    name: string;
    description?: string | null;
    logoUrl?: string | null;
};
