/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EditMessageBody } from './EditMessageBody'

export type UpdateMessagePath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type UpdateMessageStatus200 = unknown;

export type UpdateMessageBody = EditMessageBody;

export type UpdateMessageOptions = {
    body: UpdateMessageBody;
    path: UpdateMessagePath;
    query?: never;
    headers?: never;
};

export type UpdateMessageResponses = {
    "200": UpdateMessageStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateMessageResponse = UpdateMessageStatus200;
