/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GroupDto } from './GroupDto'
import type { UpdateGroupRequest } from './UpdateGroupRequest'

export type UpdateGroupPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type UpdateGroupStatus200 = GroupDto;

export type UpdateGroupStatus400 = unknown;

export type UpdateGroupStatus401 = unknown;

export type UpdateGroupStatus403 = unknown;

export type UpdateGroupStatus404 = unknown;

export type UpdateGroupBody = UpdateGroupRequest;

export type UpdateGroupOptions = {
    body: UpdateGroupBody;
    path: UpdateGroupPath;
    query?: never;
    headers?: never;
};

export type UpdateGroupResponses = {
    "200": UpdateGroupStatus200;
    "400": UpdateGroupStatus400;
    "401": UpdateGroupStatus401;
    "403": UpdateGroupStatus403;
    "404": UpdateGroupStatus404;
};

/**
 * @description Union of all possible responses
*/
export type UpdateGroupResponse = (UpdateGroupStatus200 | UpdateGroupStatus400 | UpdateGroupStatus401 | UpdateGroupStatus403 | UpdateGroupStatus404);
