/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateProductCommand = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    productId: string;
    name: string;
    description: string | null;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    brandId: string;
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    categoryId: string;
    isActive: boolean;
};
