/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TenantThemeDto } from './TenantThemeDto'

export type UpdateTenantThemeStatus204 = unknown;

export type UpdateTenantThemeStatus400 = unknown;

export type UpdateTenantThemeStatus401 = unknown;

export type UpdateTenantThemeStatus403 = unknown;

export type UpdateTenantThemeBody = TenantThemeDto;

export type UpdateTenantThemeOptions = {
    body: UpdateTenantThemeBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type UpdateTenantThemeResponses = {
    "204": UpdateTenantThemeStatus204;
    "400": UpdateTenantThemeStatus400;
    "401": UpdateTenantThemeStatus401;
    "403": UpdateTenantThemeStatus403;
};

/**
 * @description Union of all possible responses
*/
export type UpdateTenantThemeResponse = (UpdateTenantThemeStatus204 | UpdateTenantThemeStatus400 | UpdateTenantThemeStatus401 | UpdateTenantThemeStatus403);
