/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanIntervalKey } from './PlanInterval'

export type UpdatePlanCommand = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    planId: string;
    name: string;
    /**
     * @description
     * Format: `double`
    */
    monthlyBasePrice: (number | string);
    overageRates?: {
        [key: string]: (number | string);
    } | null;
    interval?: PlanIntervalKey;
    /**
     * @description
     * Format: `double`
    */
    annualPrice?: (number | string) | null;
};
