/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandCommand } from './UpdateBrandCommand'

export type UpdateBrandPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    brandId: string;
};

export type UpdateBrandStatus200 = unknown;

export type UpdateBrandBody = UpdateBrandCommand;

export type UpdateBrandOptions = {
    body: UpdateBrandBody;
    path: UpdateBrandPath;
    query?: never;
    headers?: never;
};

export type UpdateBrandResponses = {
    "200": UpdateBrandStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateBrandResponse = UpdateBrandStatus200;
