/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UpdateChannelPath = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
};

export type UpdateChannelStatus200 = unknown;

export type UpdateChannelBody = UpdateChannelBody;

export type UpdateChannelOptions = {
    body: UpdateChannelBody;
    path: UpdateChannelPath;
    query?: never;
    headers?: never;
};

export type UpdateChannelResponses = {
    "200": UpdateChannelStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdateChannelResponse = UpdateChannelStatus200;
