/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuotaResourceKey } from './QuotaResource'

export type UsageSnapshotDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string
    */
    id: string;
    tenantId: string;
    /**
     * @description
     * Format: `int32`
    */
    periodYear: (number | string);
    /**
     * @description
     * Format: `int32`
    */
    periodMonth: (number | string);
    resource: QuotaResourceKey | null;
    /**
     * @description
     * Format: `int64`
    */
    usedUnits: (bigint | string);
    /**
     * @description
     * Format: `int64`
    */
    limitUnits: (bigint | string);
    /**
     * @description
     * Format: `int64`
    */
    overage: (bigint | string);
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    capturedAtUtc: string;
};
