/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UserRoleDto = {
    roleId?: string | null;
    roleName?: string | null;
    description?: string | null;
    enabled?: boolean;
};
