/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UserSessionDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    id?: string;
    userId?: string | null;
    userName?: string | null;
    userEmail?: string | null;
    ipAddress?: string | null;
    deviceType?: string | null;
    browser?: string | null;
    browserVersion?: string | null;
    operatingSystem?: string | null;
    osVersion?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    lastActivityAt?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    expiresAt?: string;
    isActive?: boolean;
    isCurrentSession?: boolean;
};
