/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type UserDto = {
    id?: string | null;
    userName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    isActive?: boolean;
    emailConfirmed?: boolean;
    phoneNumber?: string | null;
    imageUrl?: string | null;
    twoFactorEnabled?: boolean;
};
