/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type WebhookSubscriptionDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    id?: string;
    url?: string;
    events?: string[];
    isActive?: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    createdAtUtc?: string;
};
