/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type WebhookDeliveryDto = {
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    id?: string;
    /**
     * @description
     * Format: `uuid`
     * @type string | undefined
    */
    subscriptionId?: string;
    eventType?: string;
    /**
     * @description
     * Format: `int32`
    */
    httpStatusCode?: (number | string);
    success?: boolean;
    /**
     * @description
     * Format: `int32`
    */
    attemptCount?: (number | string);
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    attemptedAtUtc?: string;
    errorMessage?: string | null;
};
