/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AddProductImageOptions, AddProductImageResponses } from '../types/AddProductImage'
import { client } from '../.kubb/client'

/**
 * @summary Attach an image to a product
 * {@link /api/v1/catalog/products/:productId/images}
 */
export function addProductImage<ThrowOnError extends boolean = true>(options: Options<AddProductImageOptions, ThrowOnError>): Promise<RequestResult<AddProductImageResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/catalog/products/{productId}/images', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AddProductImageResponses, ThrowOnError>>
}
