/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AddTicketCommentOptions, AddTicketCommentResponses } from '../types/AddTicketComment'
import { client } from '../.kubb/client'

/**
 * @summary Add a comment to a ticket
 * {@link /api/v1/tickets/:ticketId/comments}
 */
export function addTicketComment<ThrowOnError extends boolean = true>(options: Options<AddTicketCommentOptions, ThrowOnError>): Promise<RequestResult<AddTicketCommentResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tickets/{ticketId}/comments', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AddTicketCommentResponses, ThrowOnError>>
}
