/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AdjustTenantValidityOptions, AdjustTenantValidityResponses } from '../types/AdjustTenantValidity'
import { client } from '../.kubb/client'

/**
 * @description Set a tenant's validity to an explicit date with no invoice or renewal event — for comps, support extensions, or immediate expiry.
 * @summary Adjust tenant validity (operator override)
 * {@link /api/v1/tenants/:id/adjust-validity}
 */
export function adjustTenantValidity<ThrowOnError extends boolean = true>(options: Options<AdjustTenantValidityOptions, ThrowOnError>): Promise<RequestResult<AdjustTenantValidityResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tenants/{id}/adjust-validity', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AdjustTenantValidityResponses, ThrowOnError>>
}
