/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AdjustProductStockOptions, AdjustProductStockResponses } from '../types/AdjustProductStock'
import { client } from '../.kubb/client'

/**
 * @summary Adjust product stock by a delta (+/-)
 * {@link /api/v1/catalog/products/:productId/stock}
 */
export function adjustProductStock<ThrowOnError extends boolean = true>(options: Options<AdjustProductStockOptions, ThrowOnError>): Promise<RequestResult<AdjustProductStockResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/api/v1/catalog/products/{productId}/stock', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AdjustProductStockResponses, ThrowOnError>>
}
