/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AdminConfirmEmailOptions, AdminConfirmEmailResponses } from '../types/AdminConfirmEmail'
import { client } from '../.kubb/client'

/**
 * @description Marks another user's email address as confirmed without a confirmation token.
 * @summary Confirm a user's email (admin)
 * {@link /api/v1/identity/users/:id/confirm-email}
 */
export function adminConfirmEmail<ThrowOnError extends boolean = true>(options: Options<AdminConfirmEmailOptions, ThrowOnError>): Promise<RequestResult<AdminConfirmEmailResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/users/{id}/confirm-email', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AdminConfirmEmailResponses, ThrowOnError>>
}
