/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AdminRevokeAllSessionsOptions, AdminRevokeAllSessionsResponses } from '../types/AdminRevokeAllSessions'
import { client } from '../.kubb/client'

/**
 * @description Revoke all sessions for a specific user. Requires admin permission.
 * @summary Revoke all user's sessions (Admin)
 * {@link /api/v1/identity/users/:userId/sessions/revoke-all}
 */
export function adminRevokeAllSessions<ThrowOnError extends boolean = true>(options: Options<AdminRevokeAllSessionsOptions, ThrowOnError>): Promise<RequestResult<AdminRevokeAllSessionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/users/{userId}/sessions/revoke-all', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AdminRevokeAllSessionsResponses, ThrowOnError>>
}
