/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ArchiveChannelOptions, ArchiveChannelResponses } from '../types/ArchiveChannel'
import { client } from '../.kubb/client'

/**
 * @summary Soft-archive a channel (channel admin only)
 * {@link /api/v1/chat/channels/:id}
 */
export function archiveChannel<ThrowOnError extends boolean = true>(options: Options<ArchiveChannelOptions, ThrowOnError>): Promise<RequestResult<ArchiveChannelResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/chat/channels/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ArchiveChannelResponses, ThrowOnError>>
}
