/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AssignSubscriptionOptions, AssignSubscriptionResponses } from '../types/AssignSubscription'
import { client } from '../.kubb/client'

/**
 * @summary Assign a plan to a tenant
 * {@link /api/v1/billing/subscriptions}
 */
export function assignSubscription<ThrowOnError extends boolean = true>(options: Options<AssignSubscriptionOptions, ThrowOnError>): Promise<RequestResult<AssignSubscriptionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/billing/subscriptions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AssignSubscriptionResponses, ThrowOnError>>
}
