/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { AssignTicketOptions, AssignTicketResponses } from '../types/AssignTicket'
import { client } from '../.kubb/client'

/**
 * @summary Assign or reassign a ticket
 * {@link /api/v1/tickets/:ticketId/assign}
 */
export function assignTicket<ThrowOnError extends boolean = true>(options: Options<AssignTicketOptions, ThrowOnError>): Promise<RequestResult<AssignTicketResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tickets/{ticketId}/assign', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<AssignTicketResponses, ThrowOnError>>
}
