/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CaptureUsageSnapshotsOptions, CaptureUsageSnapshotsResponses } from '../types/CaptureUsageSnapshots'
import { client } from '../.kubb/client'

/**
 * @description Ops endpoint wrapping IUsageReporter.CaptureForPeriodAsync. Idempotent: re-running for the same (tenant, period) returns existing snapshots unchanged. Used for retroactive billing, debugging, and re-runs after fixes.
 * @summary Manually capture usage snapshots for a tenant + period
 * {@link /api/v1/billing/usage/snapshots/capture}
 */
export function captureUsageSnapshots<ThrowOnError extends boolean = true>(options: Options<CaptureUsageSnapshotsOptions, ThrowOnError>): Promise<RequestResult<CaptureUsageSnapshotsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/billing/usage/snapshots/capture', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CaptureUsageSnapshotsResponses, ThrowOnError>>
}
