/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ChangePasswordOptions, ChangePasswordResponses } from '../types/ChangePassword'
import { client } from '../.kubb/client'

/**
 * @description Change the current user's password.
 * @summary Change password
 * {@link /api/v1/identity/change-password}
 */
export function changePassword<ThrowOnError extends boolean = true>(options: Options<ChangePasswordOptions, ThrowOnError>): Promise<RequestResult<ChangePasswordResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/change-password', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ChangePasswordResponses, ThrowOnError>>
}
