/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ChangeFileVisibilityOptions, ChangeFileVisibilityResponses } from '../types/ChangeFileVisibility'
import { client } from '../.kubb/client'

/**
 * @description Authenticated upload permission gates the HTTP surface; per-file authorization is delegated to the OwnerType's IFileAccessPolicy (uploader-only by default).
 * @summary Flip a file's visibility (Public ↔ Private)
 * {@link /api/v1/files/:id/visibility}
 */
export function changeFileVisibility<ThrowOnError extends boolean = true>(options: Options<ChangeFileVisibilityOptions, ThrowOnError>): Promise<RequestResult<ChangeFileVisibilityResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PATCH', url: '/api/v1/files/{id}/visibility', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ChangeFileVisibilityResponses, ThrowOnError>>
}
