/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CloseTicketOptions, CloseTicketResponses } from '../types/CloseTicket'
import { client } from '../.kubb/client'

/**
 * @summary Close a resolved ticket
 * {@link /api/v1/tickets/:ticketId/close}
 */
export function closeTicket<ThrowOnError extends boolean = true>(options: Options<CloseTicketOptions, ThrowOnError>): Promise<RequestResult<CloseTicketResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tickets/{ticketId}/close', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CloseTicketResponses, ThrowOnError>>
}
