/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateGroupOptions, CreateGroupResponses } from '../types/CreateGroup'
import { client } from '../.kubb/client'

/**
 * @description Create a new group with optional role assignments.
 * @summary Create a new group
 * {@link /api/v1/identity/groups}
 */
export function createGroup<ThrowOnError extends boolean = true>(options: Options<CreateGroupOptions, ThrowOnError>): Promise<RequestResult<CreateGroupResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/groups', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateGroupResponses, ThrowOnError>>
}
