/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateWebhookSubscriptionOptions, CreateWebhookSubscriptionResponses } from '../types/CreateWebhookSubscription'
import { client } from '../.kubb/client'

/**
 * @summary Create a webhook subscription
 * {@link /api/v1/webhooks/subscriptions}
 */
export function createWebhookSubscription<ThrowOnError extends boolean = true>(options: Options<CreateWebhookSubscriptionOptions, ThrowOnError>): Promise<RequestResult<CreateWebhookSubscriptionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/webhooks/subscriptions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateWebhookSubscriptionResponses, ThrowOnError>>
}
