/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateCategoryOptions, CreateCategoryResponses } from '../types/CreateCategory'
import { client } from '../.kubb/client'

/**
 * @summary Create a category
 * {@link /api/v1/catalog/categories}
 */
export function createCategory<ThrowOnError extends boolean = true>(options: Options<CreateCategoryOptions, ThrowOnError>): Promise<RequestResult<CreateCategoryResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/catalog/categories', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateCategoryResponses, ThrowOnError>>
}
