/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateProductOptions, CreateProductResponses } from '../types/CreateProduct'
import { client } from '../.kubb/client'

/**
 * @summary Create a product
 * {@link /api/v1/catalog/products}
 */
export function createProduct<ThrowOnError extends boolean = true>(options: Options<CreateProductOptions, ThrowOnError>): Promise<RequestResult<CreateProductResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/catalog/products', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateProductResponses, ThrowOnError>>
}
