/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateBrandOptions, CreateBrandResponses } from '../types/CreateBrand'
import { client } from '../.kubb/client'

/**
 * @summary Create a brand
 * {@link /api/v1/catalog/brands}
 */
export function createBrand<ThrowOnError extends boolean = true>(options: Options<CreateBrandOptions, ThrowOnError>): Promise<RequestResult<CreateBrandResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/catalog/brands', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateBrandResponses, ThrowOnError>>
}
