/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateChannelOptions, CreateChannelResponses } from '../types/CreateChannel'
import { client } from '../.kubb/client'

/**
 * @summary Create a new named chat channel
 * {@link /api/v1/chat/channels}
 */
export function createChannel<ThrowOnError extends boolean = true>(options: Options<CreateChannelOptions, ThrowOnError>): Promise<RequestResult<CreateChannelResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/chat/channels', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateChannelResponses, ThrowOnError>>
}
