/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreatePositionOptions, CreatePositionResponses } from '../types/CreatePosition'
import { client } from '../.kubb/client'

/**
 * @summary Creates a new position.
 * {@link /api/v1/organizations/positions}
 */
export function createPosition<ThrowOnError extends boolean = true>(options: Options<CreatePositionOptions, ThrowOnError>): Promise<RequestResult<CreatePositionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/organizations/positions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreatePositionResponses, ThrowOnError>>
}
