/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateTicketOptions, CreateTicketResponses } from '../types/CreateTicket'
import { client } from '../.kubb/client'

/**
 * @summary Create a ticket
 * {@link /api/v1/tickets}
 */
export function createTicket<ThrowOnError extends boolean = true>(options: Options<CreateTicketOptions, ThrowOnError>): Promise<RequestResult<CreateTicketResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tickets', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateTicketResponses, ThrowOnError>>
}
