/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { CreateBillingPlanOptions, CreateBillingPlanResponses } from '../types/CreateBillingPlan'
import { client } from '../.kubb/client'

/**
 * @summary Create a new billing plan
 * {@link /api/v1/billing/plans}
 */
export function createBillingPlan<ThrowOnError extends boolean = true>(options: Options<CreateBillingPlanOptions, ThrowOnError>): Promise<RequestResult<CreateBillingPlanResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/billing/plans', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<CreateBillingPlanResponses, ThrowOnError>>
}
