/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteCategoryOptions, DeleteCategoryResponses } from '../types/DeleteCategory'
import { client } from '../.kubb/client'

/**
 * @summary Delete a category
 * {@link /api/v1/catalog/categories/:categoryId}
 */
export function deleteCategory<ThrowOnError extends boolean = true>(options: Options<DeleteCategoryOptions, ThrowOnError>): Promise<RequestResult<DeleteCategoryResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/catalog/categories/{categoryId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteCategoryResponses, ThrowOnError>>
}
