/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteMessageOptions, DeleteMessageResponses } from '../types/DeleteMessage'
import { client } from '../.kubb/client'

/**
 * @summary Delete a message — author can delete own; moderators can delete any
 * {@link /api/v1/chat/messages/:id}
 */
export function deleteMessage<ThrowOnError extends boolean = true>(options: Options<DeleteMessageOptions, ThrowOnError>): Promise<RequestResult<DeleteMessageResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/chat/messages/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteMessageResponses, ThrowOnError>>
}
