/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteUserOptions, DeleteUserResponses } from '../types/DeleteUser'
import { client } from '../.kubb/client'

/**
 * @description Delete a user by unique identifier.
 * @summary Delete user
 * {@link /api/v1/identity/users/:id}
 */
export function deleteUser<ThrowOnError extends boolean = true>(options: Options<DeleteUserOptions, ThrowOnError>): Promise<RequestResult<DeleteUserResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/identity/users/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteUserResponses, ThrowOnError>>
}
