/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteRoleOptions, DeleteRoleResponses } from '../types/DeleteRole'
import { client } from '../.kubb/client'

/**
 * @description Remove an existing role by its unique identifier.
 * @summary Delete role by ID
 * {@link /api/v1/identity/roles/:id}
 */
export function deleteRole<ThrowOnError extends boolean = true>(options: Options<DeleteRoleOptions, ThrowOnError>): Promise<RequestResult<DeleteRoleResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/identity/roles/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteRoleResponses, ThrowOnError>>
}
