/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteTicketOptions, DeleteTicketResponses } from '../types/DeleteTicket'
import { client } from '../.kubb/client'

/**
 * @summary Soft-delete a ticket (restorable from trash)
 * {@link /api/v1/tickets/:ticketId}
 */
export function deleteTicket<ThrowOnError extends boolean = true>(options: Options<DeleteTicketOptions, ThrowOnError>): Promise<RequestResult<DeleteTicketResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/tickets/{ticketId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteTicketResponses, ThrowOnError>>
}
