/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteWebhookSubscriptionOptions, DeleteWebhookSubscriptionResponses } from '../types/DeleteWebhookSubscription'
import { client } from '../.kubb/client'

/**
 * @summary Delete a webhook subscription
 * {@link /api/v1/webhooks/subscriptions/:id}
 */
export function deleteWebhookSubscription<ThrowOnError extends boolean = true>(options: Options<DeleteWebhookSubscriptionOptions, ThrowOnError>): Promise<RequestResult<DeleteWebhookSubscriptionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/webhooks/subscriptions/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteWebhookSubscriptionResponses, ThrowOnError>>
}
