/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteBrandOptions, DeleteBrandResponses } from '../types/DeleteBrand'
import { client } from '../.kubb/client'

/**
 * @summary Delete a brand
 * {@link /api/v1/catalog/brands/:brandId}
 */
export function deleteBrand<ThrowOnError extends boolean = true>(options: Options<DeleteBrandOptions, ThrowOnError>): Promise<RequestResult<DeleteBrandResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/catalog/brands/{brandId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteBrandResponses, ThrowOnError>>
}
