/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteFileOptions, DeleteFileResponses } from '../types/DeleteFile'
import { client } from '../.kubb/client'

/**
 * @summary Soft-delete a file; bytes purged after retention window
 * {@link /api/v1/files/:id}
 */
export function deleteFile<ThrowOnError extends boolean = true>(options: Options<DeleteFileOptions, ThrowOnError>): Promise<RequestResult<DeleteFileResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/files/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteFileResponses, ThrowOnError>>
}
