/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DeleteGroupOptions, DeleteGroupResponses } from '../types/DeleteGroup'
import { client } from '../.kubb/client'

/**
 * @description Soft delete a group. System groups cannot be deleted.
 * @summary Delete a group
 * {@link /api/v1/identity/groups/:id}
 */
export function deleteGroup<ThrowOnError extends boolean = true>(options: Options<DeleteGroupOptions, ThrowOnError>): Promise<RequestResult<DeleteGroupResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/identity/groups/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DeleteGroupResponses, ThrowOnError>>
}
