/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { DisableTwoFactorOptions, DisableTwoFactorResponses } from '../types/DisableTwoFactor'
import { client } from '../.kubb/client'

/**
 * @description Turns off 2FA after confirming the current password. Also rotates the authenticator secret so a re-enroll starts fresh.
 * @summary Disable TOTP for the current user
 * {@link /api/v1/identity/2fa/disable}
 */
export function disableTwoFactor<ThrowOnError extends boolean = true>(options: Options<DisableTwoFactorOptions, ThrowOnError>): Promise<RequestResult<DisableTwoFactorResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/2fa/disable', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<DisableTwoFactorResponses, ThrowOnError>>
}
