/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { EndImpersonationOptions, EndImpersonationResponses } from '../types/EndImpersonation'
import { client } from '../.kubb/client'

/**
 * @description Returns a fresh access + refresh token for the original actor based on the act_sub/act_tenant claims embedded in the impersonation token. Callable by any authenticated impersonation session.
 * @summary End user impersonation
 * {@link /api/v1/identity/impersonation/end}
 */
export function endImpersonation<ThrowOnError extends boolean = true>(options: Options<EndImpersonationOptions, ThrowOnError> = {}): Promise<RequestResult<EndImpersonationResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/impersonation/end', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<EndImpersonationResponses, ThrowOnError>>
}
