/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { EnrollTwoFactorOptions, EnrollTwoFactorResponses } from '../types/EnrollTwoFactor'
import { client } from '../.kubb/client'

/**
 * @description Generates (or rotates) the current user's authenticator shared secret and returns it plus an otpauth:// URI for QR rendering. 2FA is NOT enabled until the caller confirms with /2fa/verify.
 * @summary Begin TOTP enrollment
 * {@link /api/v1/identity/2fa/enroll}
 */
export function enrollTwoFactor<ThrowOnError extends boolean = true>(options: Options<EnrollTwoFactorOptions, ThrowOnError> = {}): Promise<RequestResult<EnrollTwoFactorResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/2fa/enroll', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<EnrollTwoFactorResponses, ThrowOnError>>
}
