/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetOptions, GetResponses } from '../types/Get'
import { client } from '../.kubb/client'

/**
 * {@link /}
 */
export function get<ThrowOnError extends boolean = true>(options: Options<GetOptions, ThrowOnError> = {}): Promise<RequestResult<GetResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetResponses, ThrowOnError>>
}
