/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetAuditsByCorrelationOptions, GetAuditsByCorrelationResponses } from '../types/GetAuditsByCorrelation'
import { client } from '../.kubb/client'

/**
 * @description Retrieve audit events associated with a given correlation id.
 * @summary Get audit events by correlation id
 * {@link /api/v1/audits/by-correlation/:correlationId}
 */
export function getAuditsByCorrelation<ThrowOnError extends boolean = true>(options: Options<GetAuditsByCorrelationOptions, ThrowOnError>): Promise<RequestResult<GetAuditsByCorrelationResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/audits/by-correlation/{correlationId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetAuditsByCorrelationResponses, ThrowOnError>>
}
