/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetAllPositionsOptions, GetAllPositionsResponses } from '../types/GetAllPositions'
import { client } from '../.kubb/client'

/**
 * @summary Get all positions from specified organization.
 * {@link /api/v1/organizations/:organizationId/positions}
 */
export function getAllPositions<ThrowOnError extends boolean = true>(options: Options<GetAllPositionsOptions, ThrowOnError>): Promise<RequestResult<GetAllPositionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/organizations/{organizationId}/positions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetAllPositionsResponses, ThrowOnError>>
}
