/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetAuditsByTraceOptions, GetAuditsByTraceResponses } from '../types/GetAuditsByTrace'
import { client } from '../.kubb/client'

/**
 * @description Retrieve audit events associated with a given trace id.
 * @summary Get audit events by trace id
 * {@link /api/v1/audits/by-trace/:traceId}
 */
export function getAuditsByTrace<ThrowOnError extends boolean = true>(options: Options<GetAuditsByTraceOptions, ThrowOnError>): Promise<RequestResult<GetAuditsByTraceResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/audits/by-trace/{traceId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetAuditsByTraceResponses, ThrowOnError>>
}
