/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetAllDefaultOrganizationUnitOptions, GetAllDefaultOrganizationUnitResponses } from '../types/GetAllDefaultOrganizationUnit'
import { client } from '../.kubb/client'

/**
 * @summary Get all default organization unit from default organization.
 * {@link /api/v1/organizations/units}
 */
export function getAllDefaultOrganizationUnit<ThrowOnError extends boolean = true>(options: Options<GetAllDefaultOrganizationUnitOptions, ThrowOnError> = {}): Promise<RequestResult<GetAllDefaultOrganizationUnitResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/organizations/units', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetAllDefaultOrganizationUnitResponses, ThrowOnError>>
}
