/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetAuditsOptions, GetAuditsResponses } from '../types/GetAudits'
import { client } from '../.kubb/client'

/**
 * @description Retrieve audit events with pagination and filters.
 * @summary List and search audit events
 * {@link /api/v1/audits}
 */
export function getAudits<ThrowOnError extends boolean = true>(options: Options<GetAuditsOptions, ThrowOnError> = {}): Promise<RequestResult<GetAuditsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/audits', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetAuditsResponses, ThrowOnError>>
}
