/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetBrandByIdOptions, GetBrandByIdResponses } from '../types/GetBrandById'
import { client } from '../.kubb/client'

/**
 * @summary Get a brand by id
 * {@link /api/v1/catalog/brands/:brandId}
 */
export function getBrandById<ThrowOnError extends boolean = true>(options: Options<GetBrandByIdOptions, ThrowOnError>): Promise<RequestResult<GetBrandByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/catalog/brands/{brandId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetBrandByIdResponses, ThrowOnError>>
}
