/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetBillingPlansOptions, GetBillingPlansResponses } from '../types/GetBillingPlans'
import { client } from '../.kubb/client'

/**
 * @summary List billing plans
 * {@link /api/v1/billing/plans}
 */
export function getBillingPlans<ThrowOnError extends boolean = true>(options: Options<GetBillingPlansOptions, ThrowOnError>): Promise<RequestResult<GetBillingPlansResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/billing/plans', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetBillingPlansResponses, ThrowOnError>>
}
