/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetChannelByIdOptions, GetChannelByIdResponses } from '../types/GetChannelById'
import { client } from '../.kubb/client'

/**
 * @summary Get a single channel with members and unread count
 * {@link /api/v1/chat/channels/:id}
 */
export function getChannelById<ThrowOnError extends boolean = true>(options: Options<GetChannelByIdOptions, ThrowOnError>): Promise<RequestResult<GetChannelByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/chat/channels/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetChannelByIdResponses, ThrowOnError>>
}
