/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetCategoryTreeOptions, GetCategoryTreeResponses } from '../types/GetCategoryTree'
import { client } from '../.kubb/client'

/**
 * @summary Get the full category tree
 * {@link /api/v1/catalog/categories/tree}
 */
export function getCategoryTree<ThrowOnError extends boolean = true>(options: Options<GetCategoryTreeOptions, ThrowOnError> = {}): Promise<RequestResult<GetCategoryTreeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/catalog/categories/tree', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetCategoryTreeResponses, ThrowOnError>>
}
