/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetExceptionAuditsOptions, GetExceptionAuditsResponses } from '../types/GetExceptionAudits'
import { client } from '../.kubb/client'

/**
 * @description Retrieve audit events related to exceptions.
 * @summary Get exception audit events
 * {@link /api/v1/audits/exceptions}
 */
export function getExceptionAudits<ThrowOnError extends boolean = true>(options: Options<GetExceptionAuditsOptions, ThrowOnError> = {}): Promise<RequestResult<GetExceptionAuditsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/audits/exceptions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetExceptionAuditsResponses, ThrowOnError>>
}
