/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetFileDownloadUrlOptions, GetFileDownloadUrlResponses } from '../types/GetFileDownloadUrl'
import { client } from '../.kubb/client'

/**
 * @description Default disposition is attachment (click-to-save). Pass ?inline=true to get an inline disposition for browser preview (PDF viewer, image render, etc.).
 * @summary Mint a short-lived presigned download URL
 * {@link /api/v1/files/:id/url}
 */
export function getFileDownloadUrl<ThrowOnError extends boolean = true>(options: Options<GetFileDownloadUrlOptions, ThrowOnError>): Promise<RequestResult<GetFileDownloadUrlResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/files/{id}/url', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetFileDownloadUrlResponses, ThrowOnError>>
}
