/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetFileMetadataOptions, GetFileMetadataResponses } from '../types/GetFileMetadata'
import { client } from '../.kubb/client'

/**
 * @summary Get FileAsset metadata (plus a public URL if Visibility=Public)
 * {@link /api/v1/files/:id}
 */
export function getFileMetadata<ThrowOnError extends boolean = true>(options: Options<GetFileMetadataOptions, ThrowOnError>): Promise<RequestResult<GetFileMetadataResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/files/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetFileMetadataResponses, ThrowOnError>>
}
