/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetGroupByIdOptions, GetGroupByIdResponses } from '../types/GetGroupById'
import { client } from '../.kubb/client'

/**
 * @description Retrieve a specific group by its ID including roles and member count.
 * @summary Get group by ID
 * {@link /api/v1/identity/groups/:id}
 */
export function getGroupById<ThrowOnError extends boolean = true>(options: Options<GetGroupByIdOptions, ThrowOnError>): Promise<RequestResult<GetGroupByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/groups/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetGroupByIdResponses, ThrowOnError>>
}
