/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetGroupMembersOptions, GetGroupMembersResponses } from '../types/GetGroupMembers'
import { client } from '../.kubb/client'

/**
 * @description Retrieve all users that belong to a specific group.
 * @summary Get members of a group
 * {@link /api/v1/identity/groups/:groupId/members}
 */
export function getGroupMembers<ThrowOnError extends boolean = true>(options: Options<GetGroupMembersOptions, ThrowOnError>): Promise<RequestResult<GetGroupMembersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/groups/{groupId}/members', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetGroupMembersResponses, ThrowOnError>>
}
