/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetInvoicesOptions, GetInvoicesResponses } from '../types/GetInvoices'
import { client } from '../.kubb/client'

/**
 * @summary List invoices across all tenants (admin)
 * {@link /api/v1/billing/invoices}
 */
export function getInvoices<ThrowOnError extends boolean = true>(options: Options<GetInvoicesOptions, ThrowOnError>): Promise<RequestResult<GetInvoicesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/billing/invoices', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetInvoicesResponses, ThrowOnError>>
}
