/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetInvoicePdfOptions, GetInvoicePdfResponses } from '../types/GetInvoicePdf'
import { client } from '../.kubb/client'

/**
 * @summary Download an invoice as a PDF
 * {@link /api/v1/billing/invoices/:invoiceId/pdf}
 */
export function getInvoicePdf<ThrowOnError extends boolean = true>(options: Options<GetInvoicePdfOptions, ThrowOnError>): Promise<RequestResult<GetInvoicePdfResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/billing/invoices/{invoiceId}/pdf', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetInvoicePdfResponses, ThrowOnError>>
}
