/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetMySessionsOptions, GetMySessionsResponses } from '../types/GetMySessions'
import { client } from '../.kubb/client'

/**
 * @description Retrieve all active sessions for the currently authenticated user.
 * @summary Get current user's sessions
 * {@link /api/v1/identity/sessions/me}
 */
export function getMySessions<ThrowOnError extends boolean = true>(options: Options<GetMySessionsOptions, ThrowOnError> = {}): Promise<RequestResult<GetMySessionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/sessions/me', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetMySessionsResponses, ThrowOnError>>
}
