/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetMyInvoicesOptions, GetMyInvoicesResponses } from '../types/GetMyInvoices'
import { client } from '../.kubb/client'

/**
 * @summary List invoices for the current tenant
 * {@link /api/v1/billing/invoices/me}
 */
export function getMyInvoices<ThrowOnError extends boolean = true>(options: Options<GetMyInvoicesOptions, ThrowOnError>): Promise<RequestResult<GetMyInvoicesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/billing/invoices/me', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetMyInvoicesResponses, ThrowOnError>>
}
