/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetPositionByIdOptions, GetPositionByIdResponses } from '../types/GetPositionById'
import { client } from '../.kubb/client'

/**
 * @summary Get a position by reference id.
 * {@link /api/v1/organizations/positions/:positionId}
 */
export function getPositionById<ThrowOnError extends boolean = true>(options: Options<GetPositionByIdOptions, ThrowOnError>): Promise<RequestResult<GetPositionByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/organizations/positions/{positionId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetPositionByIdResponses, ThrowOnError>>
}
