/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetProductByIdOptions, GetProductByIdResponses } from '../types/GetProductById'
import { client } from '../.kubb/client'

/**
 * @summary Get a product by id
 * {@link /api/v1/catalog/products/:productId}
 */
export function getProductById<ThrowOnError extends boolean = true>(options: Options<GetProductByIdOptions, ThrowOnError>): Promise<RequestResult<GetProductByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/catalog/products/{productId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetProductByIdResponses, ThrowOnError>>
}
