/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetRoleOptions, GetRoleResponses } from '../types/GetRole'
import { client } from '../.kubb/client'

/**
 * @description Retrieve details of a specific role by its unique identifier.
 * @summary Get role by ID
 * {@link /api/v1/identity/roles/:id}
 */
export function getRole<ThrowOnError extends boolean = true>(options: Options<GetRoleOptions, ThrowOnError>): Promise<RequestResult<GetRoleResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/roles/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetRoleResponses, ThrowOnError>>
}
