/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetSubscriptionOptions, GetSubscriptionResponses } from '../types/GetSubscription'
import { client } from '../.kubb/client'

/**
 * @summary Get the active subscription for a tenant (admin) or the current tenant
 * {@link /api/v1/billing/subscriptions}
 */
export function getSubscription<ThrowOnError extends boolean = true>(options: Options<GetSubscriptionOptions, ThrowOnError> = {}): Promise<RequestResult<GetSubscriptionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/billing/subscriptions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetSubscriptionResponses, ThrowOnError>>
}
