/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetTenantProvisioningStatusOptions, GetTenantProvisioningStatusResponses } from '../types/GetTenantProvisioningStatus'
import { client } from '../.kubb/client'

/**
 * @description Get latest provisioning status for a tenant.
 * @summary Get tenant provisioning status
 * {@link /api/v1/tenants/:tenantId/provisioning}
 */
export function getTenantProvisioningStatus<ThrowOnError extends boolean = true>(options: Options<GetTenantProvisioningStatusOptions, ThrowOnError>): Promise<RequestResult<GetTenantProvisioningStatusResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/tenants/{tenantId}/provisioning', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetTenantProvisioningStatusResponses, ThrowOnError>>
}
