/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetTenantThemeOptions, GetTenantThemeResponses } from '../types/GetTenantTheme'
import { client } from '../.kubb/client'

/**
 * @description Retrieve the theme settings for the current tenant, including colors, typography, and brand assets.
 * @summary Get current tenant theme
 * {@link /api/v1/tenants/theme}
 */
export function getTenantTheme<ThrowOnError extends boolean = true>(options: Options<GetTenantThemeOptions, ThrowOnError> = {}): Promise<RequestResult<GetTenantThemeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/tenants/theme', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetTenantThemeResponses, ThrowOnError>>
}
