/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetTenantMigrationsOptions, GetTenantMigrationsResponses } from '../types/GetTenantMigrations'
import { client } from '../.kubb/client'

/**
 * @description Retrieve migration status for each tenant, including pending migrations and provider information.
 * @summary Get per-tenant migration status
 * {@link /api/v1/tenants/migrations}
 */
export function getTenantMigrations<ThrowOnError extends boolean = true>(options: Options<GetTenantMigrationsOptions, ThrowOnError> = {}): Promise<RequestResult<GetTenantMigrationsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/tenants/migrations', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetTenantMigrationsResponses, ThrowOnError>>
}
