/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetTenantStatusOptions, GetTenantStatusResponses } from '../types/GetTenantStatus'
import { client } from '../.kubb/client'

/**
 * @description Retrieve status information for a tenant, including activation, validity, and basic metadata.
 * @summary Get tenant status
 * {@link /api/v1/tenants/:id/status}
 */
export function getTenantStatus<ThrowOnError extends boolean = true>(options: Options<GetTenantStatusOptions, ThrowOnError>): Promise<RequestResult<GetTenantStatusResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/tenants/{id}/status', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetTenantStatusResponses, ThrowOnError>>
}
