/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetUsageSnapshotsOptions, GetUsageSnapshotsResponses } from '../types/GetUsageSnapshots'
import { client } from '../.kubb/client'

/**
 * @summary List captured usage snapshots
 * {@link /api/v1/billing/usage}
 */
export function getUsageSnapshots<ThrowOnError extends boolean = true>(options: Options<GetUsageSnapshotsOptions, ThrowOnError> = {}): Promise<RequestResult<GetUsageSnapshotsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/billing/usage', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetUsageSnapshotsResponses, ThrowOnError>>
}
