/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetUserSessionsOptions, GetUserSessionsResponses } from '../types/GetUserSessions'
import { client } from '../.kubb/client'

/**
 * @description Retrieve all active sessions for a specific user. Requires admin permission.
 * @summary Get user's sessions (Admin)
 * {@link /api/v1/identity/users/:userId/sessions}
 */
export function getUserSessions<ThrowOnError extends boolean = true>(options: Options<GetUserSessionsOptions, ThrowOnError>): Promise<RequestResult<GetUserSessionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/users/{userId}/sessions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetUserSessionsResponses, ThrowOnError>>
}
