/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetUserGroupsOptions, GetUserGroupsResponses } from '../types/GetUserGroups'
import { client } from '../.kubb/client'

/**
 * @description Retrieve all groups that a specific user belongs to.
 * @summary Get groups for a user
 * {@link /api/v1/identity/users/:userId/groups}
 */
export function getUserGroups<ThrowOnError extends boolean = true>(options: Options<GetUserGroupsOptions, ThrowOnError>): Promise<RequestResult<GetUserGroupsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/users/{userId}/groups', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetUserGroupsResponses, ThrowOnError>>
}
