/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetUnreadNotificationCountOptions, GetUnreadNotificationCountResponses } from '../types/GetUnreadNotificationCount'
import { client } from '../.kubb/client'

/**
 * @summary Count of caller's unread notifications (bell badge)
 * {@link /api/v1/notifications/unread-count}
 */
export function getUnreadNotificationCount<ThrowOnError extends boolean = true>(options: Options<GetUnreadNotificationCountOptions, ThrowOnError> = {}): Promise<RequestResult<GetUnreadNotificationCountResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/notifications/unread-count', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetUnreadNotificationCountResponses, ThrowOnError>>
}
