/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetWebhookSubscriptionsOptions, GetWebhookSubscriptionsResponses } from '../types/GetWebhookSubscriptions'
import { client } from '../.kubb/client'

/**
 * @summary List webhook subscriptions
 * {@link /api/v1/webhooks/subscriptions}
 */
export function getWebhookSubscriptions<ThrowOnError extends boolean = true>(options: Options<GetWebhookSubscriptionsOptions, ThrowOnError>): Promise<RequestResult<GetWebhookSubscriptionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/webhooks/subscriptions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetWebhookSubscriptionsResponses, ThrowOnError>>
}
