/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { GetWebhookDeliveriesOptions, GetWebhookDeliveriesResponses } from '../types/GetWebhookDeliveries'
import { client } from '../.kubb/client'

/**
 * @summary List webhook deliveries for a subscription
 * {@link /api/v1/webhooks/subscriptions/:subscriptionId/deliveries}
 */
export function getWebhookDeliveries<ThrowOnError extends boolean = true>(options: Options<GetWebhookDeliveriesOptions, ThrowOnError>): Promise<RequestResult<GetWebhookDeliveriesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/webhooks/subscriptions/{subscriptionId}/deliveries', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<GetWebhookDeliveriesResponses, ThrowOnError>>
}
