/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { IssueJwtTokensOptions, IssueJwtTokensResponses } from '../types/IssueJwtTokens'
import { client } from '../.kubb/client'

/**
 * @description Submit credentials to receive a JWT access token and a refresh token. Provide the 'tenant' header to select the tenant context (defaults to 'root'). The 'X-FSH-App' header (admin|dashboard) is used to enforce the SuperAdmin / dashboard boundary.
 * @summary Issue JWT access and refresh tokens
 * {@link /api/v1/identity/token/issue}
 */
export function issueJwtTokens<ThrowOnError extends boolean = true>(options: Options<IssueJwtTokensOptions, ThrowOnError>): Promise<RequestResult<IssueJwtTokensResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/token/issue', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<IssueJwtTokensResponses, ThrowOnError>>
}
