/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListGroupsOptions, ListGroupsResponses } from '../types/ListGroups'
import { client } from '../.kubb/client'

/**
 * @description Retrieve all groups for the current tenant with optional search filter.
 * @summary List all groups
 * {@link /api/v1/identity/groups}
 */
export function listGroups<ThrowOnError extends boolean = true>(options: Options<ListGroupsOptions, ThrowOnError> = {}): Promise<RequestResult<ListGroupsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/groups', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListGroupsResponses, ThrowOnError>>
}
