/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTrashedProductsOptions, ListTrashedProductsResponses } from '../types/ListTrashedProducts'
import { client } from '../.kubb/client'

/**
 * @summary List soft-deleted products
 * {@link /api/v1/catalog/products/trash}
 */
export function listTrashedProducts<ThrowOnError extends boolean = true>(options: Options<ListTrashedProductsOptions, ThrowOnError> = {}): Promise<RequestResult<ListTrashedProductsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/catalog/products/trash', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListTrashedProductsResponses, ThrowOnError>>
}
