/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTrashedBrandsOptions, ListTrashedBrandsResponses } from '../types/ListTrashedBrands'
import { client } from '../.kubb/client'

/**
 * @summary List soft-deleted brands
 * {@link /api/v1/catalog/brands/trash}
 */
export function listTrashedBrands<ThrowOnError extends boolean = true>(options: Options<ListTrashedBrandsOptions, ThrowOnError> = {}): Promise<RequestResult<ListTrashedBrandsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/catalog/brands/trash', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListTrashedBrandsResponses, ThrowOnError>>
}
