/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTenantsOptions, ListTenantsResponses } from '../types/ListTenants'
import { client } from '../.kubb/client'

/**
 * @description Retrieve tenants for the current environment with pagination and optional sorting.
 * @summary List tenants
 * {@link /api/v1/tenants}
 */
export function listTenants<ThrowOnError extends boolean = true>(options: Options<ListTenantsOptions, ThrowOnError> = {}): Promise<RequestResult<ListTenantsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/tenants', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListTenantsResponses, ThrowOnError>>
}
