/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTicketCommentsOptions, ListTicketCommentsResponses } from '../types/ListTicketComments'
import { client } from '../.kubb/client'

/**
 * @summary List the comments on a ticket
 * {@link /api/v1/tickets/:ticketId/comments}
 */
export function listTicketComments<ThrowOnError extends boolean = true>(options: Options<ListTicketCommentsOptions, ThrowOnError>): Promise<RequestResult<ListTicketCommentsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/tickets/{ticketId}/comments', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListTicketCommentsResponses, ThrowOnError>>
}
