/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTrashedCategoriesOptions, ListTrashedCategoriesResponses } from '../types/ListTrashedCategories'
import { client } from '../.kubb/client'

/**
 * @summary List soft-deleted categories
 * {@link /api/v1/catalog/categories/trash}
 */
export function listTrashedCategories<ThrowOnError extends boolean = true>(options: Options<ListTrashedCategoriesOptions, ThrowOnError> = {}): Promise<RequestResult<ListTrashedCategoriesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/catalog/categories/trash', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListTrashedCategoriesResponses, ThrowOnError>>
}
