/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListUsersOptions, ListUsersResponses } from '../types/ListUsers'
import { client } from '../.kubb/client'

/**
 * @description Retrieve a list of users for the current tenant.
 * @summary List users
 * {@link /api/v1/identity/users}
 */
export function listUsers<ThrowOnError extends boolean = true>(options: Options<ListUsersOptions, ThrowOnError> = {}): Promise<RequestResult<ListUsersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/users', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListUsersResponses, ThrowOnError>>
}
