/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListRolesOptions, ListRolesResponses } from '../types/ListRoles'
import { client } from '../.kubb/client'

/**
 * @description Retrieve roles available for the current tenant. Pageable via PageNumber/PageSize; filterable via Search (case-insensitive substring against name + description).
 * @summary List roles (paged)
 * {@link /api/v1/identity/roles}
 */
export function listRoles<ThrowOnError extends boolean = true>(options: Options<ListRolesOptions, ThrowOnError> = {}): Promise<RequestResult<ListRolesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/identity/roles', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListRolesResponses, ThrowOnError>>
}
