/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ListTrashedFilesOptions, ListTrashedFilesResponses } from '../types/ListTrashedFiles'
import { client } from '../.kubb/client'

/**
 * @summary List soft-deleted files (admin/trash view)
 * {@link /api/v1/files/trash}
 */
export function listTrashedFiles<ThrowOnError extends boolean = true>(options: Options<ListTrashedFilesOptions, ThrowOnError> = {}): Promise<RequestResult<ListTrashedFilesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/files/trash', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ListTrashedFilesResponses, ThrowOnError>>
}
