/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { LivenessOptions, LivenessResponses } from '../types/Liveness'
import { client } from '../.kubb/client'

/**
 * @description Reports if the API process is alive. Does not check dependencies.
 * @summary Quick process liveness probe.
 * {@link /health/live}
 */
export function liveness<ThrowOnError extends boolean = true>(options: Options<LivenessOptions, ThrowOnError> = {}): Promise<RequestResult<LivenessResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/health/live', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<LivenessResponses, ThrowOnError>>
}
