/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { MarkNotificationReadOptions, MarkNotificationReadResponses } from '../types/MarkNotificationRead'
import { client } from '../.kubb/client'

/**
 * @summary Mark a single notification as read
 * {@link /api/v1/notifications/:id/read}
 */
export function markNotificationRead<ThrowOnError extends boolean = true>(options: Options<MarkNotificationReadOptions, ThrowOnError>): Promise<RequestResult<MarkNotificationReadResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/notifications/{id}/read', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<MarkNotificationReadResponses, ThrowOnError>>
}
