/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { MarkAllNotificationsReadOptions, MarkAllNotificationsReadResponses } from '../types/MarkAllNotificationsRead'
import { client } from '../.kubb/client'

/**
 * @summary Mark every unread notification for the caller as read; returns the count updated
 * {@link /api/v1/notifications/read-all}
 */
export function markAllNotificationsRead<ThrowOnError extends boolean = true>(options: Options<MarkAllNotificationsReadOptions, ThrowOnError> = {}): Promise<RequestResult<MarkAllNotificationsReadResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/notifications/read-all', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<MarkAllNotificationsReadResponses, ThrowOnError>>
}
