/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { MoveOrganizationUnitToNewOrganizationOptions, MoveOrganizationUnitToNewOrganizationResponses } from '../types/MoveOrganizationUnitToNewOrganization'
import { client } from '../.kubb/client'

/**
 * @summary Move an organization unit to new organization.
 * {@link /api/v1/organizations/units/:organizationUnitId/move}
 */
export function moveOrganizationUnitToNewOrganization<ThrowOnError extends boolean = true>(options: Options<MoveOrganizationUnitToNewOrganizationOptions, ThrowOnError>): Promise<RequestResult<MoveOrganizationUnitToNewOrganizationResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/organizations/units/{organizationUnitId}/move', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<MoveOrganizationUnitToNewOrganizationResponses, ThrowOnError>>
}
