/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { PostApiV1OrganizationsPositionAllocationsAllocationidChangeOptions, PostApiV1OrganizationsPositionAllocationsAllocationidChangeResponses } from '../types/PostApiV1OrganizationsPositionAllocationsAllocationidChange'
import { client } from '../.kubb/client'

/**
 * {@link /api/v1/organizations/position-allocations/:allocationId/change}
 */
export function postApiV1OrganizationsPositionAllocationsAllocationidChange<ThrowOnError extends boolean = true>(options: Options<PostApiV1OrganizationsPositionAllocationsAllocationidChangeOptions, ThrowOnError>): Promise<RequestResult<PostApiV1OrganizationsPositionAllocationsAllocationidChangeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/organizations/position-allocations/{allocationId}/change', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<PostApiV1OrganizationsPositionAllocationsAllocationidChangeResponses, ThrowOnError>>
}
