/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsOptions, PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponses } from '../types/PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocations'
import { client } from '../.kubb/client'

/**
 * {@link /api/v1/organizations/units/:organizationUnitId/position-allocations}
 */
export function postApiV1OrganizationsUnitsOrganizationunitidPositionAllocations<ThrowOnError extends boolean = true>(options: Options<PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsOptions, ThrowOnError>): Promise<RequestResult<PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/organizations/units/{organizationUnitId}/position-allocations', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<PostApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponses, ThrowOnError>>
}
