/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ReadinessOptions, ReadinessResponses } from '../types/Readiness'
import { client } from '../.kubb/client'

/**
 * @description Returns 200 if all dependencies are healthy, otherwise 503. Body is the same shape in both cases.
 * @summary Readiness probe with database check.
 * {@link /health/ready}
 */
export function readiness<ThrowOnError extends boolean = true>(options: Options<ReadinessOptions, ThrowOnError> = {}): Promise<RequestResult<ReadinessResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/health/ready', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ReadinessResponses, ThrowOnError>>
}
