/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RefreshJwtTokensOptions, RefreshJwtTokensResponses } from '../types/RefreshJwtTokens'
import { client } from '../.kubb/client'

/**
 * @description Use a valid (possibly expired) access token together with a valid refresh token to obtain a new access token and a rotated refresh token.
 * @summary Refresh JWT access and refresh tokens
 * {@link /api/v1/identity/token/refresh}
 */
export function refreshJwtTokens<ThrowOnError extends boolean = true>(options: Options<RefreshJwtTokensOptions, ThrowOnError>): Promise<RequestResult<RefreshJwtTokensResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/token/refresh', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RefreshJwtTokensResponses, ThrowOnError>>
}
