/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RemoveProductImageOptions, RemoveProductImageResponses } from '../types/RemoveProductImage'
import { client } from '../.kubb/client'

/**
 * @summary Detach an image from a product
 * {@link /api/v1/catalog/products/:productId/images/:imageId}
 */
export function removeProductImage<ThrowOnError extends boolean = true>(options: Options<RemoveProductImageOptions, ThrowOnError>): Promise<RequestResult<RemoveProductImageResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/catalog/products/{productId}/images/{imageId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RemoveProductImageResponses, ThrowOnError>>
}
