/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RemoveUserFromGroupOptions, RemoveUserFromGroupResponses } from '../types/RemoveUserFromGroup'
import { client } from '../.kubb/client'

/**
 * @description Remove a specific user from a group.
 * @summary Remove a user from a group
 * {@link /api/v1/identity/groups/:groupId/members/:userId}
 */
export function removeUserFromGroup<ThrowOnError extends boolean = true>(options: Options<RemoveUserFromGroupOptions, ThrowOnError>): Promise<RequestResult<RemoveUserFromGroupResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/identity/groups/{groupId}/members/{userId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RemoveUserFromGroupResponses, ThrowOnError>>
}
