/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RenewTenantOptions, RenewTenantResponses } from '../types/RenewTenant'
import { client } from '../.kubb/client'

/**
 * @description Extend a tenant's validity by one plan term, optionally switching plans, and issue the term invoice.
 * @summary Renew tenant subscription
 * {@link /api/v1/tenants/:id/renew}
 */
export function renewTenant<ThrowOnError extends boolean = true>(options: Options<RenewTenantOptions, ThrowOnError>): Promise<RequestResult<RenewTenantResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tenants/{id}/renew', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RenewTenantResponses, ThrowOnError>>
}
