/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { ReorderProductImagesOptions, ReorderProductImagesResponses } from '../types/ReorderProductImages'
import { client } from '../.kubb/client'

/**
 * @summary Set the sort order of a product's images
 * {@link /api/v1/catalog/products/:productId/images/order}
 */
export function reorderProductImages<ThrowOnError extends boolean = true>(options: Options<ReorderProductImagesOptions, ThrowOnError>): Promise<RequestResult<ReorderProductImagesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/catalog/products/{productId}/images/order', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<ReorderProductImagesResponses, ThrowOnError>>
}
