/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RestoreBrandOptions, RestoreBrandResponses } from '../types/RestoreBrand'
import { client } from '../.kubb/client'

/**
 * @summary Restore a soft-deleted brand
 * {@link /api/v1/catalog/brands/:brandId/restore}
 */
export function restoreBrand<ThrowOnError extends boolean = true>(options: Options<RestoreBrandOptions, ThrowOnError>): Promise<RequestResult<RestoreBrandResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/catalog/brands/{brandId}/restore', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RestoreBrandResponses, ThrowOnError>>
}
