/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RestoreProductOptions, RestoreProductResponses } from '../types/RestoreProduct'
import { client } from '../.kubb/client'

/**
 * @summary Restore a soft-deleted product
 * {@link /api/v1/catalog/products/:productId/restore}
 */
export function restoreProduct<ThrowOnError extends boolean = true>(options: Options<RestoreProductOptions, ThrowOnError>): Promise<RequestResult<RestoreProductResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/catalog/products/{productId}/restore', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RestoreProductResponses, ThrowOnError>>
}
