/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RestoreFileOptions, RestoreFileResponses } from '../types/RestoreFile'
import { client } from '../.kubb/client'

/**
 * @summary Restore a soft-deleted file from trash (admin)
 * {@link /api/v1/files/:id/restore}
 */
export function restoreFile<ThrowOnError extends boolean = true>(options: Options<RestoreFileOptions, ThrowOnError>): Promise<RequestResult<RestoreFileResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/files/{id}/restore', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RestoreFileResponses, ThrowOnError>>
}
