/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RestoreTicketOptions, RestoreTicketResponses } from '../types/RestoreTicket'
import { client } from '../.kubb/client'

/**
 * @summary Restore a soft-deleted ticket
 * {@link /api/v1/tickets/:ticketId/restore}
 */
export function restoreTicket<ThrowOnError extends boolean = true>(options: Options<RestoreTicketOptions, ThrowOnError>): Promise<RequestResult<RestoreTicketResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tickets/{ticketId}/restore', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RestoreTicketResponses, ThrowOnError>>
}
