/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RetryTenantProvisioningOptions, RetryTenantProvisioningResponses } from '../types/RetryTenantProvisioning'
import { client } from '../.kubb/client'

/**
 * @description Retry the provisioning workflow for a tenant.
 * @summary Retry tenant provisioning
 * {@link /api/v1/tenants/:tenantId/provisioning/retry}
 */
export function retryTenantProvisioning<ThrowOnError extends boolean = true>(options: Options<RetryTenantProvisioningOptions, ThrowOnError>): Promise<RequestResult<RetryTenantProvisioningResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/tenants/{tenantId}/provisioning/retry', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RetryTenantProvisioningResponses, ThrowOnError>>
}
