/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RevokeSessionOptions, RevokeSessionResponses } from '../types/RevokeSession'
import { client } from '../.kubb/client'

/**
 * @description Revoke a specific session for the currently authenticated user.
 * @summary Revoke a session
 * {@link /api/v1/identity/sessions/:sessionId}
 */
export function revokeSession<ThrowOnError extends boolean = true>(options: Options<RevokeSessionOptions, ThrowOnError>): Promise<RequestResult<RevokeSessionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/api/v1/identity/sessions/{sessionId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RevokeSessionResponses, ThrowOnError>>
}
