/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RevokeAllSessionsOptions, RevokeAllSessionsResponses } from '../types/RevokeAllSessions'
import { client } from '../.kubb/client'

/**
 * @description Revoke all sessions for the currently authenticated user except the current one.
 * @summary Revoke all sessions
 * {@link /api/v1/identity/sessions/revoke-all}
 */
export function revokeAllSessions<ThrowOnError extends boolean = true>(options: Options<RevokeAllSessionsOptions, ThrowOnError>): Promise<RequestResult<RevokeAllSessionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/sessions/revoke-all', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RevokeAllSessionsResponses, ThrowOnError>>
}
