/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { RevokeImpersonationGrantOptions, RevokeImpersonationGrantResponses } from '../types/RevokeImpersonationGrant'
import { client } from '../.kubb/client'

/**
 * @description Marks the grant as revoked. Subsequent requests carrying the impersonation token are rejected by the JWT validation hook within ~1 second (cache TTL).
 * @summary Revoke an impersonation grant
 * {@link /api/v1/identity/impersonation/grants/:id/revoke}
 */
export function revokeImpersonationGrant<ThrowOnError extends boolean = true>(options: Options<RevokeImpersonationGrantOptions, ThrowOnError>): Promise<RequestResult<RevokeImpersonationGrantResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/identity/impersonation/grants/{id}/revoke', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<RevokeImpersonationGrantResponses, ThrowOnError>>
}
