/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SearchMessagesOptions, SearchMessagesResponses } from '../types/SearchMessages'
import { client } from '../.kubb/client'

/**
 * @summary Full-text message search scoped to channels the caller is a member of
 * {@link /api/v1/chat/search}
 */
export function searchMessages<ThrowOnError extends boolean = true>(options: Options<SearchMessagesOptions, ThrowOnError>): Promise<RequestResult<SearchMessagesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/api/v1/chat/search', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<SearchMessagesResponses, ThrowOnError>>
}
