/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SendMessageOptions, SendMessageResponses } from '../types/SendMessage'
import { client } from '../.kubb/client'

/**
 * @summary Send a message to a channel — supports replies (parentMessageId) and attachments
 * {@link /api/v1/chat/channels/:id/messages}
 */
export function sendMessage<ThrowOnError extends boolean = true>(options: Options<SendMessageOptions, ThrowOnError>): Promise<RequestResult<SendMessageResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/chat/channels/{id}/messages', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<SendMessageResponses, ThrowOnError>>
}
