/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SetProductThumbnailOptions, SetProductThumbnailResponses } from '../types/SetProductThumbnail'
import { client } from '../.kubb/client'

/**
 * @summary Promote a product image to thumbnail (cover)
 * {@link /api/v1/catalog/products/:productId/images/:imageId/thumbnail}
 */
export function setProductThumbnail<ThrowOnError extends boolean = true>(options: Options<SetProductThumbnailOptions, ThrowOnError>): Promise<RequestResult<SetProductThumbnailResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/catalog/products/{productId}/images/{imageId}/thumbnail', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<SetProductThumbnailResponses, ThrowOnError>>
}
