/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { SseTokenOptions, SseTokenResponses } from '../types/SseToken'
import { client } from '../.kubb/client'

/**
 * @summary Issue a short-lived SSE stream token
 * {@link /api/v1/sse/token}
 */
export function sseToken<ThrowOnError extends boolean = true>(options: Options<SseTokenOptions, ThrowOnError> = {}): Promise<RequestResult<SseTokenResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/sse/token', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<SseTokenResponses, ThrowOnError>>
}
