/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateTicketOptions, UpdateTicketResponses } from '../types/UpdateTicket'
import { client } from '../.kubb/client'

/**
 * @summary Edit a ticket's title, description, and priority
 * {@link /api/v1/tickets/:ticketId}
 */
export function updateTicket<ThrowOnError extends boolean = true>(options: Options<UpdateTicketOptions, ThrowOnError>): Promise<RequestResult<UpdateTicketResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/tickets/{ticketId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateTicketResponses, ThrowOnError>>
}
