/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateProductOptions, UpdateProductResponses } from '../types/UpdateProduct'
import { client } from '../.kubb/client'

/**
 * @summary Update a product
 * {@link /api/v1/catalog/products/:productId}
 */
export function updateProduct<ThrowOnError extends boolean = true>(options: Options<UpdateProductOptions, ThrowOnError>): Promise<RequestResult<UpdateProductResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/catalog/products/{productId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateProductResponses, ThrowOnError>>
}
