/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateUserProfileOptions, UpdateUserProfileResponses } from '../types/UpdateUserProfile'
import { client } from '../.kubb/client'

/**
 * @description Update profile details for the authenticated user. Any signed-in user may edit their own profile; no admin permission required.
 * @summary Update user profile
 * {@link /api/v1/identity/profile}
 */
export function updateUserProfile<ThrowOnError extends boolean = true>(options: Options<UpdateUserProfileOptions, ThrowOnError>): Promise<RequestResult<UpdateUserProfileResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/identity/profile', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateUserProfileResponses, ThrowOnError>>
}
