/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateCategoryOptions, UpdateCategoryResponses } from '../types/UpdateCategory'
import { client } from '../.kubb/client'

/**
 * @summary Update a category
 * {@link /api/v1/catalog/categories/:categoryId}
 */
export function updateCategory<ThrowOnError extends boolean = true>(options: Options<UpdateCategoryOptions, ThrowOnError>): Promise<RequestResult<UpdateCategoryResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/catalog/categories/{categoryId}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateCategoryResponses, ThrowOnError>>
}
