/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateGroupOptions, UpdateGroupResponses } from '../types/UpdateGroup'
import { client } from '../.kubb/client'

/**
 * @description Update a group's name, description, default status, and role assignments.
 * @summary Update a group
 * {@link /api/v1/identity/groups/:id}
 */
export function updateGroup<ThrowOnError extends boolean = true>(options: Options<UpdateGroupOptions, ThrowOnError>): Promise<RequestResult<UpdateGroupResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/identity/groups/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateGroupResponses, ThrowOnError>>
}
