/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateRolePermissionsOptions, UpdateRolePermissionsResponses } from '../types/UpdateRolePermissions'
import { client } from '../.kubb/client'

/**
 * @description Replace the set of permissions assigned to a role.
 * @summary Update role permissions
 * {@link /api/v1/identity/:id/permissions}
 */
export function updateRolePermissions<ThrowOnError extends boolean = true>(options: Options<UpdateRolePermissionsOptions, ThrowOnError>): Promise<RequestResult<UpdateRolePermissionsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/identity/{id}/permissions', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateRolePermissionsResponses, ThrowOnError>>
}
