/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdateMessageOptions, UpdateMessageResponses } from '../types/UpdateMessage'
import { client } from '../.kubb/client'

/**
 * @summary Edit a message — author only
 * {@link /api/v1/chat/messages/:id}
 */
export function updateMessage<ThrowOnError extends boolean = true>(options: Options<UpdateMessageOptions, ThrowOnError>): Promise<RequestResult<UpdateMessageResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'PUT', url: '/api/v1/chat/messages/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<UpdateMessageResponses, ThrowOnError>>
}
