/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { VoidInvoiceOptions, VoidInvoiceResponses } from '../types/VoidInvoice'
import { client } from '../.kubb/client'

/**
 * @summary Void an invoice
 * {@link /api/v1/billing/invoices/:invoiceId/void}
 */
export function voidInvoice<ThrowOnError extends boolean = true>(options: Options<VoidInvoiceOptions, ThrowOnError>): Promise<RequestResult<VoidInvoiceResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/api/v1/billing/invoices/{invoiceId}/void', security: [{ type: 'http', scheme: 'bearer' }], ...config }) as Promise<RequestResult<VoidInvoiceResponses, ThrowOnError>>
}
