/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ListTenantsOptions, ListTenantsStatus200, ListTenantsStatus401, ListTenantsStatus403 } from '../../types/ListTenants'
import { queryOptions } from '@tanstack/react-query'
import { listTenants } from '../../clients/listTenants'

export const listTenantsQueryKey = ({ query }: Omit<ListTenantsOptions, 'headers'> = {}) => [{ url: '/api/v1/tenants' }, ...(query ? [query] : [])] as const

type ListTenantsQueryKey = ReturnType<typeof listTenantsQueryKey>

export function listTenantsQueryOptions({ query }: ListTenantsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listTenantsQueryKey({ query })
  return queryOptions<ListTenantsStatus200, ResponseErrorConfig<ListTenantsStatus401 | ListTenantsStatus403>, ListTenantsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listTenants({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
