/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CreateGroupOptions, CreateGroupStatus201, CreateGroupStatus400, CreateGroupStatus401, CreateGroupStatus403 } from '../../types/CreateGroup'
import { mutationOptions } from '@tanstack/react-query'
import { createGroup } from '../../clients/createGroup'

export const createGroupMutationKey = () => [{ url: '/api/v1/identity/groups' }] as const

export function createGroupMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createGroupMutationKey()
  return mutationOptions<CreateGroupStatus201, ResponseErrorConfig<CreateGroupStatus400 | CreateGroupStatus401 | CreateGroupStatus403>, CreateGroupOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createGroup({ ...config, body, throwOnError: true })
      return data
    },
  })
}
