/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ChangePasswordOptions, ChangePasswordStatus200, ChangePasswordStatus400, ChangePasswordStatus401 } from '../../types/ChangePassword'
import { mutationOptions } from '@tanstack/react-query'
import { changePassword } from '../../clients/changePassword'

export const changePasswordMutationKey = () => [{ url: '/api/v1/identity/change-password' }] as const

export function changePasswordMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = changePasswordMutationKey()
  return mutationOptions<ChangePasswordStatus200, ResponseErrorConfig<ChangePasswordStatus400 | ChangePasswordStatus401>, ChangePasswordOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await changePassword({ ...config, body, throwOnError: true })
      return data
    },
  })
}
