/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetTenantSessionsOptions, GetTenantSessionsStatus200, GetTenantSessionsStatus401, GetTenantSessionsStatus403 } from '../../types/GetTenantSessions'
import { queryOptions } from '@tanstack/react-query'
import { getTenantSessions } from '../../clients/getTenantSessions'

export const getTenantSessionsQueryKey = ({ query }: Omit<GetTenantSessionsOptions, 'headers'> = {}) => [{ url: '/api/v1/identity/sessions' }, ...(query ? [query] : [])] as const

type GetTenantSessionsQueryKey = ReturnType<typeof getTenantSessionsQueryKey>

export function getTenantSessionsQueryOptions({ query }: GetTenantSessionsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getTenantSessionsQueryKey({ query })
  return queryOptions<GetTenantSessionsStatus200, ResponseErrorConfig<GetTenantSessionsStatus401 | GetTenantSessionsStatus403>, GetTenantSessionsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getTenantSessions({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
