/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetGroupMembersOptions, GetGroupMembersStatus200, GetGroupMembersStatus401, GetGroupMembersStatus403, GetGroupMembersStatus404 } from '../../types/GetGroupMembers'
import { queryOptions } from '@tanstack/react-query'
import { getGroupMembers } from '../../clients/getGroupMembers'

export const getGroupMembersQueryKey = ({ path }: Omit<GetGroupMembersOptions, 'headers'>) => [{ url: '/api/v1/identity/groups/:groupId/members', params: path }] as const

type GetGroupMembersQueryKey = ReturnType<typeof getGroupMembersQueryKey>

export function getGroupMembersQueryOptions({ path }: GetGroupMembersOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getGroupMembersQueryKey({ path })
  return queryOptions<GetGroupMembersStatus200, ResponseErrorConfig<GetGroupMembersStatus401 | GetGroupMembersStatus403 | GetGroupMembersStatus404>, GetGroupMembersStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getGroupMembers({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
