/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetCurrentUserProfileStatus200, GetCurrentUserProfileStatus401 } from '../../types/GetCurrentUserProfile'
import { queryOptions } from '@tanstack/react-query'
import { getCurrentUserProfile } from '../../clients/getCurrentUserProfile'

export const getCurrentUserProfileQueryKey = () => [{ url: '/api/v1/identity/profile' }] as const

type GetCurrentUserProfileQueryKey = ReturnType<typeof getCurrentUserProfileQueryKey>

export function getCurrentUserProfileQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getCurrentUserProfileQueryKey()
  return queryOptions<GetCurrentUserProfileStatus200, ResponseErrorConfig<GetCurrentUserProfileStatus401>, GetCurrentUserProfileStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getCurrentUserProfile({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
