/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetCurrentUserPermissionsStatus200, GetCurrentUserPermissionsStatus401 } from '../../types/GetCurrentUserPermissions'
import { queryOptions } from '@tanstack/react-query'
import { getCurrentUserPermissions } from '../../clients/getCurrentUserPermissions'

export const getCurrentUserPermissionsQueryKey = () => [{ url: '/api/v1/identity/permissions' }] as const

type GetCurrentUserPermissionsQueryKey = ReturnType<typeof getCurrentUserPermissionsQueryKey>

export function getCurrentUserPermissionsQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getCurrentUserPermissionsQueryKey()
  return queryOptions<GetCurrentUserPermissionsStatus200, ResponseErrorConfig<GetCurrentUserPermissionsStatus401>, GetCurrentUserPermissionsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getCurrentUserPermissions({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
