/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetGroupByIdOptions, GetGroupByIdStatus200 } from '../../types/GetGroupById'
import { queryOptions } from '@tanstack/react-query'
import { getGroupById } from '../../clients/getGroupById'

export const getGroupByIdQueryKey = ({ path }: Omit<GetGroupByIdOptions, 'headers'>) => [{ url: '/api/v1/identity/groups/:id', params: path }] as const

type GetGroupByIdQueryKey = ReturnType<typeof getGroupByIdQueryKey>

export function getGroupByIdQueryOptions({ path }: GetGroupByIdOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getGroupByIdQueryKey({ path })
  return queryOptions<GetGroupByIdStatus200, ResponseErrorConfig<Error>, GetGroupByIdStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getGroupById({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
