/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { RevokeAllSessionsOptions, RevokeAllSessionsStatus200, RevokeAllSessionsStatus401, RevokeAllSessionsStatus403 } from '../../types/RevokeAllSessions'
import { mutationOptions } from '@tanstack/react-query'
import { revokeAllSessions } from '../../clients/revokeAllSessions'

export const revokeAllSessionsMutationKey = () => [{ url: '/api/v1/identity/sessions/revoke-all' }] as const

export function revokeAllSessionsMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = revokeAllSessionsMutationKey()
  return mutationOptions<RevokeAllSessionsStatus200, ResponseErrorConfig<RevokeAllSessionsStatus401 | RevokeAllSessionsStatus403>, RevokeAllSessionsOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await revokeAllSessions({ ...config, body, throwOnError: true })
      return data
    },
  })
}
