/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { RequestPasswordResetOptions, RequestPasswordResetStatus200 } from '../../types/RequestPasswordReset'
import { mutationOptions } from '@tanstack/react-query'
import { requestPasswordReset } from '../../clients/requestPasswordReset'

export const requestPasswordResetMutationKey = () => [{ url: '/api/v1/identity/forgot-password' }] as const

export function requestPasswordResetMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = requestPasswordResetMutationKey()
  return mutationOptions<RequestPasswordResetStatus200, ResponseErrorConfig<Error>, RequestPasswordResetOptions, TContext>({
    mutationKey,
    mutationFn: async({ body, headers }) => {
      const { data } = await requestPasswordReset({ ...config, body, headers, throwOnError: true })
      return data
    },
  })
}
