/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { SetProfileImageOptions, SetProfileImageStatus204, SetProfileImageStatus400, SetProfileImageStatus401 } from '../../types/SetProfileImage'
import { mutationOptions } from '@tanstack/react-query'
import { setProfileImage } from '../../clients/setProfileImage'

export const setProfileImageMutationKey = () => [{ url: '/api/v1/identity/profile/image' }] as const

export function setProfileImageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = setProfileImageMutationKey()
  return mutationOptions<SetProfileImageStatus204, ResponseErrorConfig<SetProfileImageStatus400 | SetProfileImageStatus401>, SetProfileImageOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await setProfileImage({ ...config, body, throwOnError: true })
      return data
    },
  })
}
