/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { SelfRegisterUserOptions, SelfRegisterUserStatus201, SelfRegisterUserStatus400 } from '../../types/SelfRegisterUser'
import { mutationOptions } from '@tanstack/react-query'
import { selfRegisterUser } from '../../clients/selfRegisterUser'

export const selfRegisterUserMutationKey = () => [{ url: '/api/v1/identity/self-register' }] as const

export function selfRegisterUserMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = selfRegisterUserMutationKey()
  return mutationOptions<SelfRegisterUserStatus201, ResponseErrorConfig<SelfRegisterUserStatus400>, SelfRegisterUserOptions, TContext>({
    mutationKey,
    mutationFn: async({ body, headers }) => {
      const { data } = await selfRegisterUser({ ...config, body, headers, throwOnError: true })
      return data
    },
  })
}
