/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { VerifyEnrollTwoFactorOptions, VerifyEnrollTwoFactorStatus200, VerifyEnrollTwoFactorStatus400, VerifyEnrollTwoFactorStatus401 } from '../../types/VerifyEnrollTwoFactor'
import { mutationOptions } from '@tanstack/react-query'
import { verifyEnrollTwoFactor } from '../../clients/verifyEnrollTwoFactor'

export const verifyEnrollTwoFactorMutationKey = () => [{ url: '/api/v1/identity/2fa/verify' }] as const

export function verifyEnrollTwoFactorMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = verifyEnrollTwoFactorMutationKey()
  return mutationOptions<VerifyEnrollTwoFactorStatus200, ResponseErrorConfig<VerifyEnrollTwoFactorStatus400 | VerifyEnrollTwoFactorStatus401>, VerifyEnrollTwoFactorOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await verifyEnrollTwoFactor({ ...config, body, throwOnError: true })
      return data
    },
  })
}
