/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetExceptionAuditsOptions, GetExceptionAuditsStatus200, GetExceptionAuditsStatus401, GetExceptionAuditsStatus403 } from '../../types/GetExceptionAudits'
import { queryOptions } from '@tanstack/react-query'
import { getExceptionAudits } from '../../clients/getExceptionAudits'

export const getExceptionAuditsQueryKey = ({ query }: Omit<GetExceptionAuditsOptions, 'headers'> = {}) => [{ url: '/api/v1/audits/exceptions' }, ...(query ? [query] : [])] as const

type GetExceptionAuditsQueryKey = ReturnType<typeof getExceptionAuditsQueryKey>

export function getExceptionAuditsQueryOptions({ query }: GetExceptionAuditsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getExceptionAuditsQueryKey({ query })
  return queryOptions<GetExceptionAuditsStatus200, ResponseErrorConfig<GetExceptionAuditsStatus401 | GetExceptionAuditsStatus403>, GetExceptionAuditsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getExceptionAudits({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
