/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetAuditsByTraceOptions, GetAuditsByTraceStatus200, GetAuditsByTraceStatus401, GetAuditsByTraceStatus403 } from '../../types/GetAuditsByTrace'
import { queryOptions } from '@tanstack/react-query'
import { getAuditsByTrace } from '../../clients/getAuditsByTrace'

export const getAuditsByTraceQueryKey = ({ path, query }: Omit<GetAuditsByTraceOptions, 'headers'>) => [{ url: '/api/v1/audits/by-trace/:traceId', params: path }, ...(query ? [query] : [])] as const

type GetAuditsByTraceQueryKey = ReturnType<typeof getAuditsByTraceQueryKey>

export function getAuditsByTraceQueryOptions({ path, query }: GetAuditsByTraceOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAuditsByTraceQueryKey({ path, query })
  return queryOptions<GetAuditsByTraceStatus200, ResponseErrorConfig<GetAuditsByTraceStatus401 | GetAuditsByTraceStatus403>, GetAuditsByTraceStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getAuditsByTrace({ ...config, path, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
