/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { addMembersBodySchema } from './addMembersBodySchema'

export const addChannelMembersPathIdSchema = z.uuid()

export const addChannelMembersStatus200Schema = z.unknown()

export const addChannelMembersResponseSchema = addChannelMembersStatus200Schema

export const addChannelMembersBodySchema = addMembersBodySchema
