/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const addImageBodySchema = z.object({
  fileAssetId: z.uuid().nullable(),
  url: z.string(),
})
