/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { addImageBodySchema } from './addImageBodySchema'
import { productImageDtoSchema } from './productImageDtoSchema'

export const addProductImagePathProductIdSchema = z.uuid()

export const addProductImageStatus200Schema = productImageDtoSchema

export const addProductImageStatus404Schema = z.unknown()

export const addProductImageResponseSchema = addProductImageStatus200Schema

export const addProductImageErrorSchema = addProductImageStatus404Schema

export const addProductImageBodySchema = addImageBodySchema
