/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const addUsersToGroupResponseSchema = z.object({
  addedCount: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  alreadyMemberUserIds: z.array(z.string()),
})
