/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { adjustTenantValidityCommandResponseSchema } from './adjustTenantValidityCommandResponseSchema'
import { adjustTenantValidityCommandSchema } from './adjustTenantValidityCommandSchema'

export const adjustTenantValidityPathIdSchema = z.string()

export const adjustTenantValidityStatus200Schema = adjustTenantValidityCommandResponseSchema

export const adjustTenantValidityStatus400Schema = z.unknown()

export const adjustTenantValidityStatus401Schema = z.unknown()

export const adjustTenantValidityStatus403Schema = z.unknown()

export const adjustTenantValidityResponseSchema = adjustTenantValidityStatus200Schema

export const adjustTenantValidityErrorSchema = z.union([adjustTenantValidityStatus400Schema, adjustTenantValidityStatus401Schema, adjustTenantValidityStatus403Schema])

export const adjustTenantValidityBodySchema = adjustTenantValidityCommandSchema
