/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { adjustProductStockCommandSchema } from './adjustProductStockCommandSchema'

export const adjustProductStockPathProductIdSchema = z.uuid()

export const adjustProductStockStatus200Schema = z.unknown()

export const adjustProductStockResponseSchema = adjustProductStockStatus200Schema

export const adjustProductStockBodySchema = adjustProductStockCommandSchema
