/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const adminConfirmEmailPathIdSchema = z.uuid()

export const adminConfirmEmailStatus204Schema = z.unknown()

export const adminConfirmEmailStatus401Schema = z.unknown()

export const adminConfirmEmailStatus403Schema = z.unknown()

export const adminConfirmEmailStatus404Schema = z.unknown()

export const adminConfirmEmailResponseSchema = adminConfirmEmailStatus204Schema

export const adminConfirmEmailErrorSchema = z.union([adminConfirmEmailStatus401Schema, adminConfirmEmailStatus403Schema, adminConfirmEmailStatus404Schema])
