/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const allocatePositionBodySchema = z.object({
  positionId: z.string(),
  headCount: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).nullable(),
})
