/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const archiveChannelPathIdSchema = z.uuid()

export const archiveChannelStatus200Schema = z.unknown()

export const archiveChannelResponseSchema = archiveChannelStatus200Schema
