/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { assignSubscriptionCommandSchema } from './assignSubscriptionCommandSchema'

export const assignSubscriptionStatus200Schema = z.unknown()

export const assignSubscriptionResponseSchema = assignSubscriptionStatus200Schema

export const assignSubscriptionBodySchema = assignSubscriptionCommandSchema
