/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const auditSummaryAggregateDtoSchema = z.object({
  eventsByType: z.object({}).catchall(z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])).optional(),
  eventsBySeverity: z.object({}).catchall(z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])).optional(),
  eventsBySource: z.object({}).catchall(z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])).optional(),
  eventsByTenant: z.object({}).catchall(z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])).optional(),
})
