/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { auditEventTypeSchema } from './auditEventTypeSchema'
import { auditSeveritySchema } from './auditSeveritySchema'
import { auditTagSchema } from './auditTagSchema'

export const auditSummaryDtoSchema = z.object({
  id: z.uuid().optional(),
  occurredAtUtc: z.iso.datetime().optional(),
  eventType: auditEventTypeSchema.optional(),
  severity: auditSeveritySchema.optional(),
  tenantId: z.string().nullish(),
  userId: z.string().nullish(),
  userName: z.string().nullish(),
  traceId: z.string().nullish(),
  correlationId: z.string().nullish(),
  requestId: z.string().nullish(),
  source: z.string().nullish(),
  tags: auditTagSchema.optional(),
})
