/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const auditSeveritySchema = z.enum(['None', 'Trace', 'Debug', 'Information', 'Warning', 'Error', 'Critical'])
