/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { captureUsageSnapshotsCommandSchema } from './captureUsageSnapshotsCommandSchema'
import { usageSnapshotDtoSchema } from './usageSnapshotDtoSchema'

export const captureUsageSnapshotsStatus200Schema = z.array(usageSnapshotDtoSchema)

export const captureUsageSnapshotsStatus400Schema = z.unknown()

export const captureUsageSnapshotsStatus401Schema = z.unknown()

export const captureUsageSnapshotsStatus403Schema = z.unknown()

export const captureUsageSnapshotsResponseSchema = captureUsageSnapshotsStatus200Schema

export const captureUsageSnapshotsErrorSchema = z.union([captureUsageSnapshotsStatus400Schema, captureUsageSnapshotsStatus401Schema, captureUsageSnapshotsStatus403Schema])

export const captureUsageSnapshotsBodySchema = captureUsageSnapshotsCommandSchema
