/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const categoryDtoSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
  parentCategoryId: z.uuid().nullable(),
  createdAtUtc: z.iso.datetime(),
  updatedAtUtc: z.iso.datetime().nullable(),
  deletedOnUtc: z.iso.datetime().nullish(),
  deletedBy: z.string().nullish(),
})
