/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { changeProductPriceCommandSchema } from './changeProductPriceCommandSchema'

export const changeProductPricePathProductIdSchema = z.uuid()

export const changeProductPriceStatus200Schema = z.unknown()

export const changeProductPriceResponseSchema = changeProductPriceStatus200Schema

export const changeProductPriceBodySchema = changeProductPriceCommandSchema
