/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { visibilitySchema } from './visibilitySchema'

export const changeVisibilityRequestSchema = z.object({
  visibility: visibilitySchema,
})
