/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { changePasswordCommandSchema } from './changePasswordCommandSchema'

export const changePasswordStatus200Schema = z.unknown()

export const changePasswordStatus400Schema = z.unknown()

export const changePasswordStatus401Schema = z.unknown()

export const changePasswordResponseSchema = changePasswordStatus200Schema

export const changePasswordErrorSchema = z.union([changePasswordStatus400Schema, changePasswordStatus401Schema])

export const changePasswordBodySchema = changePasswordCommandSchema
