/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const closeTicketPathTicketIdSchema = z.uuid()

export const closeTicketStatus200Schema = z.unknown()

export const closeTicketResponseSchema = closeTicketStatus200Schema
