/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { createChannelCommandSchema } from './createChannelCommandSchema'

export const createChannelStatus200Schema = z.unknown()

export const createChannelResponseSchema = createChannelStatus200Schema

export const createChannelBodySchema = createChannelCommandSchema
