/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createPositionCommandSchema = z.object({
  code: z.string(),
  name: z.string(),
  description: z.string().nullish(),
  organizationId: z.string().nullish(),
})
