/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { createProductCommandSchema } from './createProductCommandSchema'

export const createProductStatus200Schema = z.unknown()

export const createProductResponseSchema = createProductStatus200Schema

export const createProductBodySchema = createProductCommandSchema
