/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { createGroupCommandSchema } from './createGroupCommandSchema'
import { groupDtoSchema } from './groupDtoSchema'

export const createGroupStatus201Schema = groupDtoSchema

export const createGroupStatus400Schema = z.unknown()

export const createGroupStatus401Schema = z.unknown()

export const createGroupStatus403Schema = z.unknown()

export const createGroupResponseSchema = createGroupStatus201Schema

export const createGroupErrorSchema = z.union([createGroupStatus400Schema, createGroupStatus401Schema, createGroupStatus403Schema])

export const createGroupBodySchema = createGroupCommandSchema
