/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createPositionCommandSchema } from './createPositionCommandSchema'
import { positionDtoSchema } from './positionDtoSchema'

export const createPositionStatus200Schema = positionDtoSchema

export const createPositionResponseSchema = createPositionStatus200Schema

export const createPositionBodySchema = createPositionCommandSchema
