/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { createTicketCommandSchema } from './createTicketCommandSchema'

export const createTicketStatus200Schema = z.unknown()

export const createTicketResponseSchema = createTicketStatus200Schema

export const createTicketBodySchema = createTicketCommandSchema
