/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { createCategoryCommandSchema } from './createCategoryCommandSchema'

export const createCategoryStatus200Schema = z.unknown()

export const createCategoryResponseSchema = createCategoryStatus200Schema

export const createCategoryBodySchema = createCategoryCommandSchema
