/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createTenantCommandSchema = z.object({
  id: z.string(),
  name: z.string(),
  connectionString: z.string().nullable(),
  adminEmail: z.string(),
  adminPassword: z.string(),
  issuer: z.string().nullable(),
  planKey: z.string().nullish(),
})
