/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createGroupCommandSchema = z.object({
  name: z.string(),
  description: z.string().nullable(),
  isDefault: z.boolean(),
  roleIds: z.array(z.string()).nullable(),
})
