/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createProductCommandSchema = z.object({
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  brandId: z.uuid(),
  categoryId: z.uuid(),
  priceAmount: z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)]),
  priceCurrency: z.string(),
  stock: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
})
