/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { planIntervalSchema } from './planIntervalSchema'

export const createPlanCommandSchema = z.object({
  key: z.string(),
  name: z.string(),
  currency: z.string(),
  monthlyBasePrice: z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)]),
  overageRates: z.object({}).catchall(z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)])).nullish(),
  interval: planIntervalSchema.optional(),
  annualPrice: z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)]).nullish(),
})
