/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createTenantCommandResponseSchema = z.object({
  id: z.string(),
  provisioningCorrelationId: z.string(),
  status: z.string(),
})
