/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteWebhookSubscriptionPathIdSchema = z.uuid()

export const deleteWebhookSubscriptionStatus204Schema = z.unknown()

export const deleteWebhookSubscriptionResponseSchema = deleteWebhookSubscriptionStatus204Schema
