/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteBrandPathBrandIdSchema = z.uuid()

export const deleteBrandStatus200Schema = z.unknown()

export const deleteBrandResponseSchema = deleteBrandStatus200Schema
