/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteCategoryPathCategoryIdSchema = z.uuid()

export const deleteCategoryStatus200Schema = z.unknown()

export const deleteCategoryResponseSchema = deleteCategoryStatus200Schema
