/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteMessagePathIdSchema = z.uuid()

export const deleteMessageStatus200Schema = z.unknown()

export const deleteMessageResponseSchema = deleteMessageStatus200Schema
