/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteUserPathIdSchema = z.uuid()

export const deleteUserStatus204Schema = z.unknown()

export const deleteUserStatus401Schema = z.unknown()

export const deleteUserStatus403Schema = z.unknown()

export const deleteUserResponseSchema = deleteUserStatus204Schema

export const deleteUserErrorSchema = z.union([deleteUserStatus401Schema, deleteUserStatus403Schema])
