/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteRolePathIdSchema = z.uuid()

export const deleteRoleStatus204Schema = z.unknown()

export const deleteRoleStatus401Schema = z.unknown()

export const deleteRoleStatus403Schema = z.unknown()

export const deleteRoleResponseSchema = deleteRoleStatus204Schema

export const deleteRoleErrorSchema = z.union([deleteRoleStatus401Schema, deleteRoleStatus403Schema])
