/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const deleteProductPathProductIdSchema = z.uuid()

export const deleteProductStatus200Schema = z.unknown()

export const deleteProductResponseSchema = deleteProductStatus200Schema
