/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { organizationUnitDtoSchema } from './organizationUnitDtoSchema'

export const deleteOrganizationUnitPathOrganizationUnitIdSchema = z.string().min(11).max(11)

export const deleteOrganizationUnitStatus200Schema = z.lazy(() => organizationUnitDtoSchema)

export const deleteOrganizationUnitResponseSchema = deleteOrganizationUnitStatus200Schema
