/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { disableTwoFactorCommandSchema } from './disableTwoFactorCommandSchema'

export const disableTwoFactorStatus200Schema = z.unknown()

export const disableTwoFactorStatus400Schema = z.unknown()

export const disableTwoFactorStatus401Schema = z.unknown()

export const disableTwoFactorResponseSchema = disableTwoFactorStatus200Schema

export const disableTwoFactorErrorSchema = z.union([disableTwoFactorStatus400Schema, disableTwoFactorStatus401Schema])

export const disableTwoFactorBodySchema = disableTwoFactorCommandSchema
