/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const fileUploadRequestSchema = z.object({
  fileName: z.string().optional(),
  contentType: z.string().optional(),
  data: z.array(z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])).optional(),
}).describe('Represents a file upload request with filename, content type, and data.')
