/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const finalizeFileUploadPathIdSchema = z.uuid()

export const finalizeFileUploadStatus200Schema = z.unknown()

export const finalizeFileUploadResponseSchema = finalizeFileUploadStatus200Schema
