/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { findOrCreateDmCommandSchema } from './findOrCreateDmCommandSchema'

export const findOrCreateDmStatus200Schema = z.unknown()

export const findOrCreateDmResponseSchema = findOrCreateDmStatus200Schema

export const findOrCreateDmBodySchema = findOrCreateDmCommandSchema
