/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const generateInvoicesCommandSchema = z.object({
  periodYear: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  periodMonth: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
})
