/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { organizationUnitPositionAllocationDtoSchema } from './organizationUnitPositionAllocationDtoSchema'

export const getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsPathOrganizationUnitIdSchema = z.string().min(11).max(11)

export const getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200Schema = z.array(organizationUnitPositionAllocationDtoSchema)

export const getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponseSchema = getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200Schema
