/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { auditSummaryAggregateDtoSchema } from './auditSummaryAggregateDtoSchema'

export const getAuditSummaryQueryFromUtcSchema = z.iso.datetime().optional()

export const getAuditSummaryQueryToUtcSchema = z.iso.datetime().optional()

export const getAuditSummaryQueryTenantIdSchema = z.string().optional()

export const getAuditSummaryStatus200Schema = auditSummaryAggregateDtoSchema

export const getAuditSummaryStatus401Schema = z.unknown()

export const getAuditSummaryStatus403Schema = z.unknown()

export const getAuditSummaryResponseSchema = getAuditSummaryStatus200Schema

export const getAuditSummaryErrorSchema = z.union([getAuditSummaryStatus401Schema, getAuditSummaryStatus403Schema])
