/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { organizationUnitDtoSchema } from './organizationUnitDtoSchema'

export const getAllOrganizationUnitPathOrganizationIdSchema = z.string().min(11).max(11)

export const getAllOrganizationUnitStatus200Schema = z.array(z.lazy(() => organizationUnitDtoSchema))

export const getAllOrganizationUnitResponseSchema = getAllOrganizationUnitStatus200Schema
