/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { auditEventTypeSchema } from './auditEventTypeSchema'
import { auditSeveritySchema } from './auditSeveritySchema'
import { auditTagSchema } from './auditTagSchema'
import { pagedResponseOfAuditSummaryDtoSchema } from './pagedResponseOfAuditSummaryDtoSchema'

export const getAuditsQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const getAuditsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const getAuditsQuerySortSchema = z.string().optional()

export const getAuditsQueryFromUtcSchema = z.iso.datetime().optional()

export const getAuditsQueryToUtcSchema = z.iso.datetime().optional()

export const getAuditsQueryTenantIdSchema = z.string().optional()

export const getAuditsQueryUserIdSchema = z.string().optional()

export const getAuditsQueryEventTypeSchema = auditEventTypeSchema.optional()

export const getAuditsQueryExcludeEventTypeSchema = auditEventTypeSchema.optional()

export const getAuditsQuerySeveritySchema = auditSeveritySchema.optional()

export const getAuditsQueryTagsSchema = auditTagSchema.optional()

export const getAuditsQuerySourceSchema = z.string().optional()

export const getAuditsQueryCorrelationIdSchema = z.string().optional()

export const getAuditsQueryTraceIdSchema = z.string().optional()

export const getAuditsQuerySearchSchema = z.string().optional()

export const getAuditsStatus200Schema = pagedResponseOfAuditSummaryDtoSchema

export const getAuditsStatus401Schema = z.unknown()

export const getAuditsStatus403Schema = z.unknown()

export const getAuditsResponseSchema = getAuditsStatus200Schema

export const getAuditsErrorSchema = z.union([getAuditsStatus401Schema, getAuditsStatus403Schema])
