/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { organizationUnitDtoSchema } from './organizationUnitDtoSchema'

export const getAllOrganizationsStatus200Schema = z.array(z.lazy(() => organizationUnitDtoSchema))

export const getAllOrganizationsResponseSchema = getAllOrganizationsStatus200Schema
