/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { auditDetailDtoSchema } from './auditDetailDtoSchema'

export const getAuditByIdPathIdSchema = z.uuid()

export const getAuditByIdStatus200Schema = auditDetailDtoSchema

export const getAuditByIdStatus401Schema = z.unknown()

export const getAuditByIdStatus403Schema = z.unknown()

export const getAuditByIdStatus404Schema = z.unknown()

export const getAuditByIdResponseSchema = getAuditByIdStatus200Schema

export const getAuditByIdErrorSchema = z.union([getAuditByIdStatus401Schema, getAuditByIdStatus403Schema, getAuditByIdStatus404Schema])
