/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { auditSummaryDtoSchema } from './auditSummaryDtoSchema'

export const getAuditsByTracePathTraceIdSchema = z.string()

export const getAuditsByTraceQueryFromUtcSchema = z.iso.datetime().optional()

export const getAuditsByTraceQueryToUtcSchema = z.iso.datetime().optional()

export const getAuditsByTraceStatus200Schema = z.array(auditSummaryDtoSchema)

export const getAuditsByTraceStatus401Schema = z.unknown()

export const getAuditsByTraceStatus403Schema = z.unknown()

export const getAuditsByTraceResponseSchema = getAuditsByTraceStatus200Schema

export const getAuditsByTraceErrorSchema = z.union([getAuditsByTraceStatus401Schema, getAuditsByTraceStatus403Schema])
