/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { organizationUnitPositionAllocationDtoSchema } from './organizationUnitPositionAllocationDtoSchema'

export const getApiV1OrganizationsUnitsOrganizationunitidPositionsPositionidAllocationHistoryPathOrganizationUnitIdSchema = z.string().min(11).max(11)

export const getApiV1OrganizationsUnitsOrganizationunitidPositionsPositionidAllocationHistoryPathPositionIdSchema = z.string().min(11).max(11)

export const getApiV1OrganizationsUnitsOrganizationunitidPositionsPositionidAllocationHistoryStatus200Schema = z.array(organizationUnitPositionAllocationDtoSchema)

export const getApiV1OrganizationsUnitsOrganizationunitidPositionsPositionidAllocationHistoryResponseSchema = getApiV1OrganizationsUnitsOrganizationunitidPositionsPositionidAllocationHistoryStatus200Schema
