/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { brandDtoSchema } from './brandDtoSchema'

export const getBrandByIdPathBrandIdSchema = z.uuid()

export const getBrandByIdStatus200Schema = brandDtoSchema

export const getBrandByIdResponseSchema = getBrandByIdStatus200Schema
