/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getChannelByIdPathIdSchema = z.uuid()

export const getChannelByIdStatus200Schema = z.unknown()

export const getChannelByIdResponseSchema = getChannelByIdStatus200Schema
