/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getFileMetadataPathIdSchema = z.uuid()

export const getFileMetadataStatus200Schema = z.unknown()

export const getFileMetadataResponseSchema = getFileMetadataStatus200Schema
