/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getFileDownloadUrlPathIdSchema = z.uuid()

export const getFileDownloadUrlQueryInlineSchema = z.boolean().optional()

export const getFileDownloadUrlStatus200Schema = z.unknown()

export const getFileDownloadUrlResponseSchema = getFileDownloadUrlStatus200Schema
