/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { groupMemberDtoSchema } from './groupMemberDtoSchema'

export const getGroupMembersPathGroupIdSchema = z.uuid()

export const getGroupMembersStatus200Schema = z.array(groupMemberDtoSchema)

export const getGroupMembersStatus401Schema = z.unknown()

export const getGroupMembersStatus403Schema = z.unknown()

export const getGroupMembersStatus404Schema = z.unknown()

export const getGroupMembersResponseSchema = getGroupMembersStatus200Schema

export const getGroupMembersErrorSchema = z.union([getGroupMembersStatus401Schema, getGroupMembersStatus403Schema, getGroupMembersStatus404Schema])
