/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { groupDtoSchema } from './groupDtoSchema'

export const getGroupByIdPathIdSchema = z.uuid()

export const getGroupByIdStatus200Schema = groupDtoSchema

export const getGroupByIdResponseSchema = getGroupByIdStatus200Schema
