/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getInvoicePdfPathInvoiceIdSchema = z.uuid()

export const getInvoicePdfStatus200Schema = z.unknown()

export const getInvoicePdfStatus404Schema = z.unknown()

export const getInvoicePdfResponseSchema = getInvoicePdfStatus200Schema

export const getInvoicePdfErrorSchema = getInvoicePdfStatus404Schema
