/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { invoiceStatusSchema } from './invoiceStatusSchema'
import { pagedResponseOfInvoiceDtoSchema } from './pagedResponseOfInvoiceDtoSchema'

export const getInvoicesQueryTenantIdSchema = z.string().optional()

export const getInvoicesQueryStatusSchema = invoiceStatusSchema.optional()

export const getInvoicesQueryPeriodYearSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const getInvoicesQueryPeriodMonthSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const getInvoicesQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])

export const getInvoicesQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])

export const getInvoicesStatus200Schema = pagedResponseOfInvoiceDtoSchema

export const getInvoicesResponseSchema = getInvoicesStatus200Schema
