/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { impersonationGrantDtoSchema } from './impersonationGrantDtoSchema'
import { impersonationGrantStatusSchema } from './impersonationGrantStatusSchema'

export const getImpersonationGrantsQueryStatusSchema = impersonationGrantStatusSchema.optional()

export const getImpersonationGrantsQueryImpersonatedTenantIdSchema = z.string().optional()

export const getImpersonationGrantsQueryActorUserIdSchema = z.string().optional()

export const getImpersonationGrantsQueryTakeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional().default(100)

export const getImpersonationGrantsStatus200Schema = z.array(impersonationGrantDtoSchema)

export const getImpersonationGrantsStatus401Schema = z.unknown()

export const getImpersonationGrantsStatus403Schema = z.unknown()

export const getImpersonationGrantsResponseSchema = getImpersonationGrantsStatus200Schema

export const getImpersonationGrantsErrorSchema = z.union([getImpersonationGrantsStatus401Schema, getImpersonationGrantsStatus403Schema])
