/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { invoiceDtoSchema } from './invoiceDtoSchema'

export const getInvoiceByIdPathInvoiceIdSchema = z.uuid()

export const getInvoiceByIdStatus200Schema = invoiceDtoSchema

export const getInvoiceByIdResponseSchema = getInvoiceByIdStatus200Schema
