/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { permissionCatalogEntryDtoSchema } from './permissionCatalogEntryDtoSchema'

export const getPermissionCatalogStatus200Schema = z.array(permissionCatalogEntryDtoSchema)

export const getPermissionCatalogStatus401Schema = z.unknown()

export const getPermissionCatalogStatus403Schema = z.unknown()

export const getPermissionCatalogResponseSchema = getPermissionCatalogStatus200Schema

export const getPermissionCatalogErrorSchema = z.union([getPermissionCatalogStatus401Schema, getPermissionCatalogStatus403Schema])
