/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { roleDtoSchema } from './roleDtoSchema'

export const getRolePermissionsPathIdSchema = z.uuid()

export const getRolePermissionsStatus200Schema = roleDtoSchema

export const getRolePermissionsStatus401Schema = z.unknown()

export const getRolePermissionsStatus403Schema = z.unknown()

export const getRolePermissionsStatus404Schema = z.unknown()

export const getRolePermissionsResponseSchema = getRolePermissionsStatus200Schema

export const getRolePermissionsErrorSchema = z.union([getRolePermissionsStatus401Schema, getRolePermissionsStatus403Schema, getRolePermissionsStatus404Schema])
