/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { auditSummaryDtoSchema } from './auditSummaryDtoSchema'
import { securityActionSchema } from './securityActionSchema'

export const getSecurityAuditsQueryActionSchema = securityActionSchema.nullish()

export const getSecurityAuditsQueryUserIdSchema = z.string().optional()

export const getSecurityAuditsQueryTenantIdSchema = z.string().optional()

export const getSecurityAuditsQueryFromUtcSchema = z.iso.datetime().optional()

export const getSecurityAuditsQueryToUtcSchema = z.iso.datetime().optional()

export const getSecurityAuditsStatus200Schema = z.array(auditSummaryDtoSchema)

export const getSecurityAuditsStatus401Schema = z.unknown()

export const getSecurityAuditsStatus403Schema = z.unknown()

export const getSecurityAuditsResponseSchema = getSecurityAuditsStatus200Schema

export const getSecurityAuditsErrorSchema = z.union([getSecurityAuditsStatus401Schema, getSecurityAuditsStatus403Schema])
