/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { subscriptionDtoSchema } from './subscriptionDtoSchema'

export const getSubscriptionQueryTenantIdSchema = z.string().optional()

export const getSubscriptionStatus200Schema = subscriptionDtoSchema

export const getSubscriptionResponseSchema = getSubscriptionStatus200Schema
