/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { pagedResponseOfUserSessionDtoSchema } from './pagedResponseOfUserSessionDtoSchema'

export const getTenantSessionsQueryIncludeInactiveSchema = z.boolean().optional()

export const getTenantSessionsQuerySearchSchema = z.string().optional()

export const getTenantSessionsQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const getTenantSessionsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const getTenantSessionsStatus200Schema = pagedResponseOfUserSessionDtoSchema

export const getTenantSessionsStatus401Schema = z.unknown()

export const getTenantSessionsStatus403Schema = z.unknown()

export const getTenantSessionsResponseSchema = getTenantSessionsStatus200Schema

export const getTenantSessionsErrorSchema = z.union([getTenantSessionsStatus401Schema, getTenantSessionsStatus403Schema])
