/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { tenantMigrationStatusDtoSchema } from './tenantMigrationStatusDtoSchema'

export const getTenantMigrationsStatus200Schema = z.array(tenantMigrationStatusDtoSchema)

export const getTenantMigrationsStatus401Schema = z.unknown()

export const getTenantMigrationsStatus403Schema = z.unknown()

export const getTenantMigrationsResponseSchema = getTenantMigrationsStatus200Schema

export const getTenantMigrationsErrorSchema = z.union([getTenantMigrationsStatus401Schema, getTenantMigrationsStatus403Schema])
