/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { tenantStatusDtoSchema } from './tenantStatusDtoSchema'

export const getTenantStatusPathIdSchema = z.string()

export const getTenantStatusStatus200Schema = tenantStatusDtoSchema

export const getTenantStatusStatus401Schema = z.unknown()

export const getTenantStatusStatus403Schema = z.unknown()

export const getTenantStatusStatus404Schema = z.unknown()

export const getTenantStatusResponseSchema = getTenantStatusStatus200Schema

export const getTenantStatusErrorSchema = z.union([getTenantStatusStatus401Schema, getTenantStatusStatus403Schema, getTenantStatusStatus404Schema])
