/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { userSessionDtoSchema } from './userSessionDtoSchema'

export const getUserSessionsPathUserIdSchema = z.uuid()

export const getUserSessionsStatus200Schema = z.array(userSessionDtoSchema)

export const getUserSessionsStatus401Schema = z.unknown()

export const getUserSessionsStatus403Schema = z.unknown()

export const getUserSessionsStatus404Schema = z.unknown()

export const getUserSessionsResponseSchema = getUserSessionsStatus200Schema

export const getUserSessionsErrorSchema = z.union([getUserSessionsStatus401Schema, getUserSessionsStatus403Schema, getUserSessionsStatus404Schema])
