/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { userRoleDtoSchema } from './userRoleDtoSchema'

export const getUserRolesPathIdSchema = z.uuid()

export const getUserRolesStatus200Schema = z.array(userRoleDtoSchema)

export const getUserRolesStatus401Schema = z.unknown()

export const getUserRolesStatus403Schema = z.unknown()

export const getUserRolesStatus404Schema = z.unknown()

export const getUserRolesResponseSchema = getUserRolesStatus200Schema

export const getUserRolesErrorSchema = z.union([getUserRolesStatus401Schema, getUserRolesStatus403Schema, getUserRolesStatus404Schema])
