/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { userDtoSchema } from './userDtoSchema'

export const getUserPathIdSchema = z.uuid()

export const getUserStatus200Schema = userDtoSchema

export const getUserStatus401Schema = z.unknown()

export const getUserStatus403Schema = z.unknown()

export const getUserStatus404Schema = z.unknown()

export const getUserResponseSchema = getUserStatus200Schema

export const getUserErrorSchema = z.union([getUserStatus401Schema, getUserStatus403Schema, getUserStatus404Schema])
