/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getUnreadNotificationCountStatus200Schema = z.unknown()

export const getUnreadNotificationCountResponseSchema = getUnreadNotificationCountStatus200Schema
