/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { healthEntrySchema } from './healthEntrySchema'

export const healthResultSchema = z.object({
  status: z.string(),
  results: z.array(healthEntrySchema),
})
