/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const impersonationResponseSchema = z.object({
  accessToken: z.string(),
  accessTokenExpiresAt: z.iso.datetime(),
  actorUserId: z.string(),
  actorTenantId: z.string(),
  impersonatedUserId: z.string(),
  impersonatedTenantId: z.string(),
})
