/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { invoiceLineItemKindSchema } from './invoiceLineItemKindSchema'
import { quotaResourceSchema } from './quotaResourceSchema'

export const invoiceLineItemDtoSchema = z.object({
  id: z.uuid(),
  kind: invoiceLineItemKindSchema,
  resource: z.union([z.null(), quotaResourceSchema]),
  description: z.string(),
  quantity: z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)]),
  unitPrice: z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)]),
  amount: z.union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)]),
})
