/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { generateTokenCommandSchema } from './generateTokenCommandSchema'
import { tokenResponseSchema } from './tokenResponseSchema'

export const issueJwtTokensHeaderTenantSchema = z.string().default('root')

export const issueJwtTokensHeaderXFSHAppSchema = z.string().optional()

export const issueJwtTokensStatus200Schema = tokenResponseSchema

export const issueJwtTokensStatus400Schema = z.unknown()

export const issueJwtTokensStatus401Schema = z.unknown()

export const issueJwtTokensStatus403Schema = z.unknown()

export const issueJwtTokensStatus500Schema = z.unknown()

export const issueJwtTokensResponseSchema = issueJwtTokensStatus200Schema

export const issueJwtTokensErrorSchema = z.union([issueJwtTokensStatus400Schema, issueJwtTokensStatus401Schema, issueJwtTokensStatus403Schema, issueJwtTokensStatus500Schema])

export const issueJwtTokensBodySchema = generateTokenCommandSchema
