/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const issueInvoicePathInvoiceIdSchema = z.uuid()

export const issueInvoiceStatus200Schema = z.unknown()

export const issueInvoiceResponseSchema = issueInvoiceStatus200Schema

export const issueInvoiceBodySchema = z.union([z.null(), issueInvoiceBodySchema.strict()]).optional()
