/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { groupDtoSchema } from './groupDtoSchema'

export const listGroupsQuerySearchSchema = z.string().optional()

export const listGroupsStatus200Schema = z.array(groupDtoSchema)

export const listGroupsResponseSchema = listGroupsStatus200Schema
