/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listPinnedMessagesPathIdSchema = z.uuid()

export const listPinnedMessagesStatus200Schema = z.unknown()

export const listPinnedMessagesResponseSchema = listPinnedMessagesStatus200Schema
