/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listTrashedBrandsQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listTrashedBrandsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listTrashedBrandsStatus200Schema = z.unknown()

export const listTrashedBrandsResponseSchema = listTrashedBrandsStatus200Schema
