/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listTrashedTicketsQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listTrashedTicketsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listTrashedTicketsStatus200Schema = z.unknown()

export const listTrashedTicketsResponseSchema = listTrashedTicketsStatus200Schema
