/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { pagedResponseOfRoleDtoSchema } from './pagedResponseOfRoleDtoSchema'

export const listRolesQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listRolesQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listRolesQuerySortSchema = z.string().optional()

export const listRolesQuerySearchSchema = z.string().optional()

export const listRolesStatus200Schema = pagedResponseOfRoleDtoSchema

export const listRolesStatus401Schema = z.unknown()

export const listRolesStatus403Schema = z.unknown()

export const listRolesResponseSchema = listRolesStatus200Schema

export const listRolesErrorSchema = z.union([listRolesStatus401Schema, listRolesStatus403Schema])
