/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listMyFilesQueryPageSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listMyFilesQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listMyFilesStatus200Schema = z.unknown()

export const listMyFilesResponseSchema = listMyFilesStatus200Schema
