/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listNotificationsQueryUnreadOnlySchema = z.boolean().optional()

export const listNotificationsQueryPageSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listNotificationsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listNotificationsStatus200Schema = z.unknown()

export const listNotificationsResponseSchema = listNotificationsStatus200Schema
