/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listMessageRepliesPathIdSchema = z.uuid()

export const listMessageRepliesQueryBeforeSchema = z.uuid().optional()

export const listMessageRepliesQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const listMessageRepliesStatus200Schema = z.unknown()

export const listMessageRepliesResponseSchema = listMessageRepliesStatus200Schema
