/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { healthResultSchema } from './healthResultSchema'

export const livenessStatus200Schema = healthResultSchema

export const livenessResponseSchema = livenessStatus200Schema
