/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const markChannelReadPathIdSchema = z.uuid()

export const markChannelReadStatus200Schema = z.unknown()

export const markChannelReadResponseSchema = markChannelReadStatus200Schema

export const markChannelReadBodySchema = markChannelReadBodySchema
