/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const markInvoicePaidPathInvoiceIdSchema = z.uuid()

export const markInvoicePaidStatus200Schema = z.unknown()

export const markInvoicePaidResponseSchema = markInvoicePaidStatus200Schema
