/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const markAllNotificationsReadStatus200Schema = z.unknown()

export const markAllNotificationsReadResponseSchema = markAllNotificationsReadStatus200Schema
