/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { positionDtoSchema } from './positionDtoSchema'

export const organizationUnitPositionAllocationDtoSchema = z.object({
  id: z.uuid().optional(),
  organizationUnitReferenceId: z.string().optional(),
  position: positionDtoSchema.optional(),
  headCount: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).nullish(),
  effectiveFrom: z.iso.datetime().optional(),
  effectiveTo: z.iso.datetime().nullish(),
})
