/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { invoiceDtoSchema } from './invoiceDtoSchema'

export const pagedResponseOfInvoiceDtoSchema = z.object({
  items: z.array(invoiceDtoSchema).optional(),
  pageNumber: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional(),
  pageSize: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional(),
  totalCount: z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional(),
  totalPages: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional(),
  hasNext: z.boolean().optional(),
  hasPrevious: z.boolean().optional(),
})
