/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const positionDtoSchema = z.object({
  referenceId: z.string().optional(),
  name: z.string().optional(),
  code: z.string().optional(),
  description: z.string().nullish(),
  createdOnUtc: z.iso.datetime().optional(),
  createdBy: z.string().nullish(),
  lastModifiedOnUtc: z.iso.datetime().nullish(),
  lastModifiedBy: z.string().nullish(),
  isDeleted: z.boolean().optional(),
  deletedOnUtc: z.iso.datetime().nullish(),
  deletedBy: z.string().nullish(),
})
