/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { allocatePositionBodySchema } from './allocatePositionBodySchema'
import { organizationUnitPositionAllocationDtoSchema } from './organizationUnitPositionAllocationDtoSchema'

export const postApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsPathOrganizationUnitIdSchema = z.string().min(11).max(11)

export const postApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200Schema = organizationUnitPositionAllocationDtoSchema

export const postApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsResponseSchema = postApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200Schema

export const postApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsBodySchema = allocatePositionBodySchema
