/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { organizationUnitPositionAllocationDtoSchema } from './organizationUnitPositionAllocationDtoSchema'

export const postApiV1OrganizationsPositionAllocationsAllocationidEndPathAllocationIdSchema = z.uuid()

export const postApiV1OrganizationsPositionAllocationsAllocationidEndStatus200Schema = organizationUnitPositionAllocationDtoSchema

export const postApiV1OrganizationsPositionAllocationsAllocationidEndResponseSchema = postApiV1OrganizationsPositionAllocationsAllocationidEndStatus200Schema
