/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const productImageDtoSchema = z.object({
  id: z.uuid(),
  fileAssetId: z.uuid().nullable(),
  url: z.string(),
  isThumbnail: z.boolean(),
  sortOrder: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  createdAtUtc: z.iso.datetime(),
})
