/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { refreshTokenCommandResponseSchema } from './refreshTokenCommandResponseSchema'
import { refreshTokenCommandSchema } from './refreshTokenCommandSchema'

export const refreshJwtTokensHeaderTenantSchema = z.string()

export const refreshJwtTokensStatus200Schema = refreshTokenCommandResponseSchema

export const refreshJwtTokensStatus400Schema = z.unknown()

export const refreshJwtTokensStatus401Schema = z.unknown()

export const refreshJwtTokensStatus500Schema = z.unknown()

export const refreshJwtTokensResponseSchema = refreshJwtTokensStatus200Schema

export const refreshJwtTokensErrorSchema = z.union([refreshJwtTokensStatus400Schema, refreshJwtTokensStatus401Schema, refreshJwtTokensStatus500Schema])

export const refreshJwtTokensBodySchema = refreshTokenCommandSchema
