/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const refreshTokenCommandResponseSchema = z.object({
  token: z.string(),
  refreshToken: z.string(),
  refreshTokenExpiryTime: z.iso.datetime(),
})
