/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const registerUserCommandSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
  userName: z.string().optional(),
  password: z.string().optional(),
  confirmPassword: z.string().optional(),
  phoneNumber: z.string().nullish(),
})
