/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { registerUserCommandSchema } from './registerUserCommandSchema'
import { registerUserResponseSchema } from './registerUserResponseSchema'

export const registerUserStatus201Schema = registerUserResponseSchema

export const registerUserStatus400Schema = z.unknown()

export const registerUserStatus401Schema = z.unknown()

export const registerUserStatus403Schema = z.unknown()

export const registerUserErrorSchema = z.union([registerUserStatus400Schema, registerUserStatus401Schema, registerUserStatus403Schema])

export const registerUserBodySchema = registerUserCommandSchema
