/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const removeReactionPathIdSchema = z.uuid()

export const removeReactionPathEmojiSchema = z.string()

export const removeReactionStatus200Schema = z.unknown()

export const removeReactionResponseSchema = removeReactionStatus200Schema
