/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const removeProductImagePathProductIdSchema = z.uuid()

export const removeProductImagePathImageIdSchema = z.uuid()

export const removeProductImageStatus204Schema = z.unknown()

export const removeProductImageStatus404Schema = z.unknown()

export const removeProductImageResponseSchema = removeProductImageStatus204Schema

export const removeProductImageErrorSchema = removeProductImageStatus404Schema
