/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const removeChannelMemberPathIdSchema = z.uuid()

export const removeChannelMemberPathUserIdSchema = z.string()

export const removeChannelMemberStatus200Schema = z.unknown()

export const removeChannelMemberResponseSchema = removeChannelMemberStatus200Schema
