/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const renewTenantCommandSchema = z.object({
  tenantId: z.string(),
  planKey: z.string().nullish(),
})
