/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { renewTenantCommandResponseSchema } from './renewTenantCommandResponseSchema'
import { renewTenantCommandSchema } from './renewTenantCommandSchema'

export const renewTenantPathIdSchema = z.string()

export const renewTenantStatus200Schema = renewTenantCommandResponseSchema

export const renewTenantStatus400Schema = z.unknown()

export const renewTenantStatus401Schema = z.unknown()

export const renewTenantStatus403Schema = z.unknown()

export const renewTenantResponseSchema = renewTenantStatus200Schema

export const renewTenantErrorSchema = z.union([renewTenantStatus400Schema, renewTenantStatus401Schema, renewTenantStatus403Schema])

export const renewTenantBodySchema = renewTenantCommandSchema
