/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { reorderBodySchema } from './reorderBodySchema'

export const reorderProductImagesPathProductIdSchema = z.uuid()

export const reorderProductImagesStatus204Schema = z.unknown()

export const reorderProductImagesStatus404Schema = z.unknown()

export const reorderProductImagesResponseSchema = reorderProductImagesStatus204Schema

export const reorderProductImagesErrorSchema = reorderProductImagesStatus404Schema

export const reorderProductImagesBodySchema = reorderBodySchema
