/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { requestUploadUrlCommandSchema } from './requestUploadUrlCommandSchema'

export const requestFileUploadUrlStatus200Schema = z.unknown()

export const requestFileUploadUrlResponseSchema = requestFileUploadUrlStatus200Schema

export const requestFileUploadUrlBodySchema = requestUploadUrlCommandSchema
