/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { forgotPasswordCommandSchema } from './forgotPasswordCommandSchema'

export const requestPasswordResetHeaderTenantSchema = z.string()

export const requestPasswordResetStatus200Schema = z.unknown()

export const requestPasswordResetResponseSchema = requestPasswordResetStatus200Schema

export const requestPasswordResetBodySchema = forgotPasswordCommandSchema
