/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { resetPasswordCommandSchema } from './resetPasswordCommandSchema'

export const resetPasswordHeaderTenantSchema = z.string()

export const resetPasswordStatus200Schema = z.unknown()

export const resetPasswordResponseSchema = resetPasswordStatus200Schema

export const resetPasswordBodySchema = resetPasswordCommandSchema
