/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const resetTenantThemeStatus204Schema = z.unknown()

export const resetTenantThemeStatus401Schema = z.unknown()

export const resetTenantThemeStatus403Schema = z.unknown()

export const resetTenantThemeResponseSchema = resetTenantThemeStatus204Schema

export const resetTenantThemeErrorSchema = z.union([resetTenantThemeStatus401Schema, resetTenantThemeStatus403Schema])
