/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const restoreProductPathProductIdSchema = z.uuid()

export const restoreProductStatus200Schema = z.unknown()

export const restoreProductResponseSchema = restoreProductStatus200Schema
