/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const restoreCategoryPathCategoryIdSchema = z.uuid()

export const restoreCategoryStatus200Schema = z.unknown()

export const restoreCategoryResponseSchema = restoreCategoryStatus200Schema
