/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const restoreFilePathIdSchema = z.uuid()

export const restoreFileStatus200Schema = z.unknown()

export const restoreFileResponseSchema = restoreFileStatus200Schema
