/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { tenantProvisioningStatusDtoSchema } from './tenantProvisioningStatusDtoSchema'

export const retryTenantProvisioningPathTenantIdSchema = z.string()

export const retryTenantProvisioningStatus200Schema = tenantProvisioningStatusDtoSchema

export const retryTenantProvisioningStatus401Schema = z.unknown()

export const retryTenantProvisioningStatus403Schema = z.unknown()

export const retryTenantProvisioningStatus404Schema = z.unknown()

export const retryTenantProvisioningResponseSchema = retryTenantProvisioningStatus200Schema

export const retryTenantProvisioningErrorSchema = z.union([retryTenantProvisioningStatus401Schema, retryTenantProvisioningStatus403Schema, retryTenantProvisioningStatus404Schema])
