/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { bodySchema } from './bodySchema'
import { impersonationGrantDtoSchema } from './impersonationGrantDtoSchema'

export const revokeImpersonationGrantPathIdSchema = z.uuid()

export const revokeImpersonationGrantStatus200Schema = impersonationGrantDtoSchema

export const revokeImpersonationGrantStatus401Schema = z.unknown()

export const revokeImpersonationGrantStatus403Schema = z.unknown()

export const revokeImpersonationGrantStatus404Schema = z.unknown()

export const revokeImpersonationGrantResponseSchema = revokeImpersonationGrantStatus200Schema

export const revokeImpersonationGrantErrorSchema = z.union([revokeImpersonationGrantStatus401Schema, revokeImpersonationGrantStatus403Schema, revokeImpersonationGrantStatus404Schema])

export const revokeImpersonationGrantBodySchema = z.union([z.null(), bodySchema.strict()]).optional()
