/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { revokeAllSessionsCommandSchema } from './revokeAllSessionsCommandSchema'

export const revokeAllSessionsStatus200Schema = z.unknown()

export const revokeAllSessionsStatus401Schema = z.unknown()

export const revokeAllSessionsStatus403Schema = z.unknown()

export const revokeAllSessionsResponseSchema = revokeAllSessionsStatus200Schema

export const revokeAllSessionsErrorSchema = z.union([revokeAllSessionsStatus401Schema, revokeAllSessionsStatus403Schema])

export const revokeAllSessionsBodySchema = z.union([z.null(), revokeAllSessionsCommandSchema.strict()]).optional()
