/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const roleDtoSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().nullish(),
  permissions: z.array(z.string()).nullish(),
})
