/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { ticketPrioritySchema } from './ticketPrioritySchema'
import { ticketStatusSchema } from './ticketStatusSchema'

export const searchTicketsQuerySearchSchema = z.string().optional()

export const searchTicketsQueryStatusSchema = ticketStatusSchema.nullish()

export const searchTicketsQueryPrioritySchema = ticketPrioritySchema.optional().default('Medium')

export const searchTicketsQueryAssignedToUserIdSchema = z.uuid().optional()

export const searchTicketsQueryReporterUserIdSchema = z.uuid().optional()

export const searchTicketsQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const searchTicketsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const searchTicketsQuerySortBySchema = z.string().optional()

export const searchTicketsQuerySortDirSchema = z.string().optional()

export const searchTicketsStatus200Schema = z.unknown()

export const searchTicketsResponseSchema = searchTicketsStatus200Schema
