/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { pagedResponseOfCategoryDtoSchema } from './pagedResponseOfCategoryDtoSchema'

export const searchCategoriesQuerySearchSchema = z.string().optional()

export const searchCategoriesQueryParentCategoryIdSchema = z.uuid().optional()

export const searchCategoriesQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])

export const searchCategoriesQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])

export const searchCategoriesQuerySortBySchema = z.string().optional()

export const searchCategoriesQuerySortDirSchema = z.string().optional()

export const searchCategoriesStatus200Schema = pagedResponseOfCategoryDtoSchema

export const searchCategoriesResponseSchema = searchCategoriesStatus200Schema
