/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { pagedResponseOfProductDtoSchema } from './pagedResponseOfProductDtoSchema'

export const searchProductsQuerySearchSchema = z.string().optional()

export const searchProductsQueryBrandIdSchema = z.uuid().optional()

export const searchProductsQueryCategoryIdSchema = z.uuid().optional()

export const searchProductsQueryIsActiveSchema = z.boolean().optional()

export const searchProductsQueryPageNumberSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])

export const searchProductsQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])

export const searchProductsQuerySortBySchema = z.string().optional()

export const searchProductsQuerySortDirSchema = z.string().optional()

export const searchProductsStatus200Schema = pagedResponseOfProductDtoSchema

export const searchProductsResponseSchema = searchProductsStatus200Schema
