/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const searchMessagesQueryQSchema = z.string()

export const searchMessagesQueryChannelIdSchema = z.uuid().optional()

export const searchMessagesQueryPageSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const searchMessagesQueryPageSizeSchema = z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).optional()

export const searchMessagesStatus200Schema = z.unknown()

export const searchMessagesResponseSchema = searchMessagesStatus200Schema
