/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const securityActionSchema = z.enum(['None', 'LoginSucceeded', 'LoginFailed', 'TokenIssued', 'TokenRevoked', 'PasswordChanged', 'RoleAssigned', 'RoleRevoked', 'PermissionDenied', 'PolicyFailed', 'ImpersonationStarted', 'ImpersonationEnded']).nullable()
