/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { registerUserCommandSchema } from './registerUserCommandSchema'
import { registerUserResponseSchema } from './registerUserResponseSchema'

export const selfRegisterUserHeaderTenantSchema = z.string()

export const selfRegisterUserStatus201Schema = registerUserResponseSchema

export const selfRegisterUserStatus400Schema = z.unknown()

export const selfRegisterUserResponseSchema = selfRegisterUserStatus201Schema

export const selfRegisterUserErrorSchema = selfRegisterUserStatus400Schema

export const selfRegisterUserBodySchema = registerUserCommandSchema
