/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const sendMessagePathIdSchema = z.uuid()

export const sendMessageStatus200Schema = z.unknown()

export const sendMessageResponseSchema = sendMessageStatus200Schema

export const sendMessageBodySchema = sendMessageBodySchema
