/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const sendMessageAttachmentInputSchema = z.object({
  fileAssetId: z.uuid().nullable(),
  url: z.string(),
  contentType: z.string(),
  fileName: z.string(),
  sizeBytes: z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
})
