/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const setProductThumbnailPathProductIdSchema = z.uuid()

export const setProductThumbnailPathImageIdSchema = z.uuid()

export const setProductThumbnailStatus204Schema = z.unknown()

export const setProductThumbnailStatus404Schema = z.unknown()

export const setProductThumbnailResponseSchema = setProductThumbnailStatus204Schema

export const setProductThumbnailErrorSchema = setProductThumbnailStatus404Schema
