/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const sseTokenStatus200Schema = z.unknown()

export const sseTokenResponseSchema = sseTokenStatus200Schema
