/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const startImpersonationCommandSchema = z.object({
  targetUserId: z.string(),
  targetTenantId: z.string(),
  reason: z.string().nullable(),
  durationMinutes: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).nullish(),
})
