/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { subscriptionStatusSchema } from './subscriptionStatusSchema'

export const subscriptionDtoSchema = z.object({
  id: z.uuid(),
  tenantId: z.string(),
  planId: z.uuid(),
  planKey: z.string(),
  startUtc: z.iso.datetime(),
  endUtc: z.iso.datetime().nullable(),
  status: subscriptionStatusSchema,
})
