/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const tenantMigrationStatusDtoSchema = z.object({
  tenantId: z.string().optional(),
  name: z.string().optional(),
  isActive: z.boolean().optional(),
  validUpto: z.iso.datetime().nullish(),
  hasPendingMigrations: z.boolean().optional(),
  provider: z.string().nullish(),
  lastAppliedMigration: z.string().nullish(),
  pendingMigrations: z.array(z.string()).optional(),
  error: z.string().nullish(),
})
