/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const tenantStatusDtoSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  isActive: z.boolean().optional(),
  validUpto: z.iso.datetime().optional(),
  hasConnectionString: z.boolean().optional(),
  adminEmail: z.string().optional(),
  issuer: z.string().nullish(),
  plan: z.string().nullish(),
  expiryState: z.string().optional(),
  graceEndsUtc: z.iso.datetime().optional(),
})
