/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { tenantProvisioningStepDtoSchema } from './tenantProvisioningStepDtoSchema'

export const tenantProvisioningStatusDtoSchema = z.object({
  tenantId: z.string(),
  status: z.string(),
  correlationId: z.string(),
  currentStep: z.string().nullable(),
  error: z.string().nullable(),
  createdUtc: z.iso.datetime(),
  startedUtc: z.iso.datetime().nullable(),
  completedUtc: z.iso.datetime().nullable(),
  steps: z.array(tenantProvisioningStepDtoSchema),
})
