/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const tenantLifecycleResultDtoSchema = z.object({
  tenantId: z.string().optional(),
  isActive: z.boolean().optional(),
  validUpto: z.iso.datetime().nullish(),
  message: z.string().optional(),
})
