/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const toggleUserStatusCommandSchema = z.object({
  activateUser: z.boolean().optional(),
  userId: z.string().nullish(),
})
