/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const unpinMessagePathIdSchema = z.uuid()

export const unpinMessageStatus200Schema = z.unknown()

export const unpinMessageResponseSchema = unpinMessageStatus200Schema
