/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { editMessageBodySchema } from './editMessageBodySchema'

export const updateMessagePathIdSchema = z.uuid()

export const updateMessageStatus200Schema = z.unknown()

export const updateMessageResponseSchema = updateMessageStatus200Schema

export const updateMessageBodySchema = editMessageBodySchema
