/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updatePermissionsCommandSchema = z.object({
  roleId: z.string().optional(),
  permissions: z.array(z.string()).optional(),
})
