/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateProductCommandSchema = z.object({
  productId: z.uuid(),
  name: z.string(),
  description: z.string().nullable(),
  brandId: z.uuid(),
  categoryId: z.uuid(),
  isActive: z.boolean(),
})
