/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { groupDtoSchema } from './groupDtoSchema'
import { updateGroupRequestSchema } from './updateGroupRequestSchema'

export const updateGroupPathIdSchema = z.uuid()

export const updateGroupStatus200Schema = groupDtoSchema

export const updateGroupStatus400Schema = z.unknown()

export const updateGroupStatus401Schema = z.unknown()

export const updateGroupStatus403Schema = z.unknown()

export const updateGroupStatus404Schema = z.unknown()

export const updateGroupResponseSchema = updateGroupStatus200Schema

export const updateGroupErrorSchema = z.union([updateGroupStatus400Schema, updateGroupStatus401Schema, updateGroupStatus403Schema, updateGroupStatus404Schema])

export const updateGroupBodySchema = updateGroupRequestSchema
