/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateBrandCommandSchema = z.object({
  brandId: z.uuid(),
  name: z.string(),
  description: z.string().nullish(),
  logoUrl: z.string().nullish(),
})
