/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { fileUploadRequestSchema } from './fileUploadRequestSchema'

export const updateUserCommandSchema = z.object({
  id: z.string().optional(),
  firstName: z.string().nullish(),
  lastName: z.string().nullish(),
  phoneNumber: z.string().nullish(),
  email: z.string().nullish(),
  image: z.union([z.null(), fileUploadRequestSchema.strict()]).optional(),
  deleteCurrentImage: z.boolean().optional(),
})
