/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { updateUserCommandSchema } from './updateUserCommandSchema'

export const updateUserProfileStatus200Schema = z.unknown()

export const updateUserProfileStatus400Schema = z.unknown()

export const updateUserProfileStatus401Schema = z.unknown()

export const updateUserProfileResponseSchema = updateUserProfileStatus200Schema

export const updateUserProfileErrorSchema = z.union([updateUserProfileStatus400Schema, updateUserProfileStatus401Schema])

export const updateUserProfileBodySchema = updateUserCommandSchema
