/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { updateProductCommandSchema } from './updateProductCommandSchema'

export const updateProductPathProductIdSchema = z.uuid()

export const updateProductStatus200Schema = z.unknown()

export const updateProductResponseSchema = updateProductStatus200Schema

export const updateProductBodySchema = updateProductCommandSchema
