/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updateCategoryCommandSchema = z.object({
  categoryId: z.uuid(),
  name: z.string(),
  description: z.string().nullish(),
  parentCategoryId: z.uuid().nullish(),
})
