/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const updatePositionBodySchema = z.object({
  code: z.string(),
  name: z.string(),
  description: z.string().nullable(),
})
