/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { updatePermissionsCommandSchema } from './updatePermissionsCommandSchema'

export const updateRolePermissionsPathIdSchema = z.string()

export const updateRolePermissionsStatus200Schema = z.string()

export const updateRolePermissionsStatus400Schema = z.unknown()

export const updateRolePermissionsStatus401Schema = z.unknown()

export const updateRolePermissionsStatus403Schema = z.unknown()

export const updateRolePermissionsStatus404Schema = z.unknown()

export const updateRolePermissionsResponseSchema = updateRolePermissionsStatus200Schema

export const updateRolePermissionsErrorSchema = z.union([updateRolePermissionsStatus400Schema, updateRolePermissionsStatus401Schema, updateRolePermissionsStatus403Schema, updateRolePermissionsStatus404Schema])

export const updateRolePermissionsBodySchema = updatePermissionsCommandSchema
