/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { updateTicketRequestSchema } from './updateTicketRequestSchema'

export const updateTicketPathTicketIdSchema = z.uuid()

export const updateTicketStatus200Schema = z.unknown()

export const updateTicketResponseSchema = updateTicketStatus200Schema

export const updateTicketBodySchema = updateTicketRequestSchema
