/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { tenantThemeDtoSchema } from './tenantThemeDtoSchema'

export const updateTenantThemeStatus204Schema = z.unknown()

export const updateTenantThemeStatus400Schema = z.unknown()

export const updateTenantThemeStatus401Schema = z.unknown()

export const updateTenantThemeStatus403Schema = z.unknown()

export const updateTenantThemeResponseSchema = updateTenantThemeStatus204Schema

export const updateTenantThemeErrorSchema = z.union([updateTenantThemeStatus400Schema, updateTenantThemeStatus401Schema, updateTenantThemeStatus403Schema])

export const updateTenantThemeBodySchema = tenantThemeDtoSchema
