/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { quotaResourceSchema } from './quotaResourceSchema'

export const usageSnapshotDtoSchema = z.object({
  id: z.uuid(),
  tenantId: z.string(),
  periodYear: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  periodMonth: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  resource: quotaResourceSchema.nullable(),
  usedUnits: z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  limitUnits: z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  overage: z.union([z.bigint(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  capturedAtUtc: z.iso.datetime(),
})
