/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const userSessionDtoSchema = z.object({
  id: z.uuid().optional(),
  userId: z.string().nullish(),
  userName: z.string().nullish(),
  userEmail: z.string().nullish(),
  ipAddress: z.string().nullish(),
  deviceType: z.string().nullish(),
  browser: z.string().nullish(),
  browserVersion: z.string().nullish(),
  operatingSystem: z.string().nullish(),
  osVersion: z.string().nullish(),
  createdAt: z.iso.datetime().optional(),
  lastActivityAt: z.iso.datetime().optional(),
  expiresAt: z.iso.datetime().optional(),
  isActive: z.boolean().optional(),
  isCurrentSession: z.boolean().optional(),
})
