/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CreateOrganizationUnitOptions, CreateOrganizationUnitStatus200 } from '../../types/CreateOrganizationUnit'
import { mutationOptions } from '@tanstack/react-query'
import { createOrganizationUnit } from '../../clients/createOrganizationUnit'

export const createOrganizationUnitMutationKey = () => [{ url: '/api/v1/organizations/units' }] as const

export function createOrganizationUnitMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createOrganizationUnitMutationKey()
  return mutationOptions<CreateOrganizationUnitStatus200, ResponseErrorConfig<Error>, CreateOrganizationUnitOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createOrganizationUnit({ ...config, body, throwOnError: true })
      return data
    },
  })
}
