/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CreatePositionOptions, CreatePositionStatus200 } from '../../types/CreatePosition'
import { mutationOptions } from '@tanstack/react-query'
import { createPosition } from '../../clients/createPosition'

export const createPositionMutationKey = () => [{ url: '/api/v1/organizations/positions' }] as const

export function createPositionMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createPositionMutationKey()
  return mutationOptions<CreatePositionStatus200, ResponseErrorConfig<Error>, CreatePositionOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createPosition({ ...config, body, throwOnError: true })
      return data
    },
  })
}
