/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { DeleteOrganizationUnitOptions, DeleteOrganizationUnitStatus200 } from '../../types/DeleteOrganizationUnit'
import { mutationOptions } from '@tanstack/react-query'
import { deleteOrganizationUnit } from '../../clients/deleteOrganizationUnit'

export const deleteOrganizationUnitMutationKey = () => [{ url: '/api/v1/organizations/units/:organizationUnitId' }] as const

export function deleteOrganizationUnitMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteOrganizationUnitMutationKey()
  return mutationOptions<DeleteOrganizationUnitStatus200, ResponseErrorConfig<Error>, DeleteOrganizationUnitOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteOrganizationUnit({ ...config, path, throwOnError: true })
      return data
    },
  })
}
