/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetAllOrganizationUnitOptions, GetAllOrganizationUnitStatus200 } from '../../types/GetAllOrganizationUnit'
import { queryOptions } from '@tanstack/react-query'
import { getAllOrganizationUnit } from '../../clients/getAllOrganizationUnit'

export const getAllOrganizationUnitQueryKey = ({ path }: Omit<GetAllOrganizationUnitOptions, 'headers'>) => [{ url: '/api/v1/organizations/:organizationId/units', params: path }] as const

type GetAllOrganizationUnitQueryKey = ReturnType<typeof getAllOrganizationUnitQueryKey>

export function getAllOrganizationUnitQueryOptions({ path }: GetAllOrganizationUnitOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAllOrganizationUnitQueryKey({ path })
  return queryOptions<GetAllOrganizationUnitStatus200, ResponseErrorConfig<Error>, GetAllOrganizationUnitStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getAllOrganizationUnit({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
