/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetAllDefaultOrganizationUnitStatus200 } from '../../types/GetAllDefaultOrganizationUnit'
import { queryOptions } from '@tanstack/react-query'
import { getAllDefaultOrganizationUnit } from '../../clients/getAllDefaultOrganizationUnit'

export const getAllDefaultOrganizationUnitQueryKey = () => [{ url: '/api/v1/organizations/units' }] as const

type GetAllDefaultOrganizationUnitQueryKey = ReturnType<typeof getAllDefaultOrganizationUnitQueryKey>

export function getAllDefaultOrganizationUnitQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAllDefaultOrganizationUnitQueryKey()
  return queryOptions<GetAllDefaultOrganizationUnitStatus200, ResponseErrorConfig<Error>, GetAllDefaultOrganizationUnitStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getAllDefaultOrganizationUnit({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
