/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { PostApiV1OrganizationsPositionAllocationsAllocationidEndOptions, PostApiV1OrganizationsPositionAllocationsAllocationidEndStatus200 } from '../../types/PostApiV1OrganizationsPositionAllocationsAllocationidEnd'
import { mutationOptions } from '@tanstack/react-query'
import { postApiV1OrganizationsPositionAllocationsAllocationidEnd } from '../../clients/postApiV1OrganizationsPositionAllocationsAllocationidEnd'

export const postApiV1OrganizationsPositionAllocationsAllocationidEndMutationKey = () => [{ url: '/api/v1/organizations/position-allocations/:allocationId/end' }] as const

export function postApiV1OrganizationsPositionAllocationsAllocationidEndMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = postApiV1OrganizationsPositionAllocationsAllocationidEndMutationKey()
  return mutationOptions<PostApiV1OrganizationsPositionAllocationsAllocationidEndStatus200, ResponseErrorConfig<Error>, PostApiV1OrganizationsPositionAllocationsAllocationidEndOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await postApiV1OrganizationsPositionAllocationsAllocationidEnd({ ...config, path, throwOnError: true })
      return data
    },
  })
}
