/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { PostApiV1OrganizationsPositionAllocationsAllocationidChangeOptions, PostApiV1OrganizationsPositionAllocationsAllocationidChangeStatus200 } from '../../types/PostApiV1OrganizationsPositionAllocationsAllocationidChange'
import { mutationOptions } from '@tanstack/react-query'
import { postApiV1OrganizationsPositionAllocationsAllocationidChange } from '../../clients/postApiV1OrganizationsPositionAllocationsAllocationidChange'

export const postApiV1OrganizationsPositionAllocationsAllocationidChangeMutationKey = () => [{ url: '/api/v1/organizations/position-allocations/:allocationId/change' }] as const

export function postApiV1OrganizationsPositionAllocationsAllocationidChangeMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = postApiV1OrganizationsPositionAllocationsAllocationidChangeMutationKey()
  return mutationOptions<PostApiV1OrganizationsPositionAllocationsAllocationidChangeStatus200, ResponseErrorConfig<Error>, PostApiV1OrganizationsPositionAllocationsAllocationidChangeOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await postApiV1OrganizationsPositionAllocationsAllocationidChange({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
