/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { UpdateOrganizationUnitOptions, UpdateOrganizationUnitStatus200 } from '../../types/UpdateOrganizationUnit'
import { mutationOptions } from '@tanstack/react-query'
import { updateOrganizationUnit } from '../../clients/updateOrganizationUnit'

export const updateOrganizationUnitMutationKey = () => [{ url: '/api/v1/organizations/units/:organizationUnitId' }] as const

export function updateOrganizationUnitMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateOrganizationUnitMutationKey()
  return mutationOptions<UpdateOrganizationUnitStatus200, ResponseErrorConfig<Error>, UpdateOrganizationUnitOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateOrganizationUnit({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
