/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { AdjustProductStockOptions, AdjustProductStockStatus200 } from '../types/AdjustProductStock'
import { mutationOptions } from '@tanstack/react-query'
import { adjustProductStock } from '../clients/adjustProductStock'

export const adjustProductStockMutationKey = () => [{ url: '/api/v1/catalog/products/:productId/stock' }] as const

export function adjustProductStockMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = adjustProductStockMutationKey()
  return mutationOptions<AdjustProductStockStatus200, ResponseErrorConfig<Error>, AdjustProductStockOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await adjustProductStock({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
