/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { AddUsersToGroupOptions, AddUsersToGroupStatus200, AddUsersToGroupStatus400, AddUsersToGroupStatus401, AddUsersToGroupStatus403, AddUsersToGroupStatus404 } from '../types/AddUsersToGroup'
import { mutationOptions } from '@tanstack/react-query'
import { addUsersToGroup } from '../clients/addUsersToGroup'

export const addUsersToGroupMutationKey = () => [{ url: '/api/v1/identity/groups/:groupId/members' }] as const

export function addUsersToGroupMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = addUsersToGroupMutationKey()
  return mutationOptions<AddUsersToGroupStatus200, ResponseErrorConfig<AddUsersToGroupStatus400 | AddUsersToGroupStatus401 | AddUsersToGroupStatus403 | AddUsersToGroupStatus404>, AddUsersToGroupOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await addUsersToGroup({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
