/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ArchiveChannelOptions, ArchiveChannelStatus200 } from '../types/ArchiveChannel'
import { mutationOptions } from '@tanstack/react-query'
import { archiveChannel } from '../clients/archiveChannel'

export const archiveChannelMutationKey = () => [{ url: '/api/v1/chat/channels/:id' }] as const

export function archiveChannelMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = archiveChannelMutationKey()
  return mutationOptions<ArchiveChannelStatus200, ResponseErrorConfig<Error>, ArchiveChannelOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await archiveChannel({ ...config, path, throwOnError: true })
      return data
    },
  })
}
