/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { AssignUserRolesOptions, AssignUserRolesStatus200, AssignUserRolesStatus400, AssignUserRolesStatus401, AssignUserRolesStatus403 } from '../types/AssignUserRoles'
import { mutationOptions } from '@tanstack/react-query'
import { assignUserRoles } from '../clients/assignUserRoles'

export const assignUserRolesMutationKey = () => [{ url: '/api/v1/identity/users/:id/roles' }] as const

export function assignUserRolesMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = assignUserRolesMutationKey()
  return mutationOptions<AssignUserRolesStatus200, ResponseErrorConfig<AssignUserRolesStatus400 | AssignUserRolesStatus401 | AssignUserRolesStatus403>, AssignUserRolesOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await assignUserRoles({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
