/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateOrUpdateRoleOptions, CreateOrUpdateRoleStatus200, CreateOrUpdateRoleStatus401, CreateOrUpdateRoleStatus403 } from '../types/CreateOrUpdateRole'
import { mutationOptions } from '@tanstack/react-query'
import { createOrUpdateRole } from '../clients/createOrUpdateRole'

export const createOrUpdateRoleMutationKey = () => [{ url: '/api/v1/identity/roles' }] as const

export function createOrUpdateRoleMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createOrUpdateRoleMutationKey()
  return mutationOptions<CreateOrUpdateRoleStatus200, ResponseErrorConfig<CreateOrUpdateRoleStatus401 | CreateOrUpdateRoleStatus403>, CreateOrUpdateRoleOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createOrUpdateRole({ ...config, body, throwOnError: true })
      return data
    },
  })
}
