/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateChannelOptions, CreateChannelStatus200 } from '../types/CreateChannel'
import { mutationOptions } from '@tanstack/react-query'
import { createChannel } from '../clients/createChannel'

export const createChannelMutationKey = () => [{ url: '/api/v1/chat/channels' }] as const

export function createChannelMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createChannelMutationKey()
  return mutationOptions<CreateChannelStatus200, ResponseErrorConfig<Error>, CreateChannelOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createChannel({ ...config, body, throwOnError: true })
      return data
    },
  })
}
