/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteTicketOptions, DeleteTicketStatus200 } from '../types/DeleteTicket'
import { mutationOptions } from '@tanstack/react-query'
import { deleteTicket } from '../clients/deleteTicket'

export const deleteTicketMutationKey = () => [{ url: '/api/v1/tickets/:ticketId' }] as const

export function deleteTicketMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteTicketMutationKey()
  return mutationOptions<DeleteTicketStatus200, ResponseErrorConfig<Error>, DeleteTicketOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteTicket({ ...config, path, throwOnError: true })
      return data
    },
  })
}
