/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DisableTwoFactorOptions, DisableTwoFactorStatus200, DisableTwoFactorStatus400, DisableTwoFactorStatus401 } from '../types/DisableTwoFactor'
import { mutationOptions } from '@tanstack/react-query'
import { disableTwoFactor } from '../clients/disableTwoFactor'

export const disableTwoFactorMutationKey = () => [{ url: '/api/v1/identity/2fa/disable' }] as const

export function disableTwoFactorMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = disableTwoFactorMutationKey()
  return mutationOptions<DisableTwoFactorStatus200, ResponseErrorConfig<DisableTwoFactorStatus400 | DisableTwoFactorStatus401>, DisableTwoFactorOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await disableTwoFactor({ ...config, body, throwOnError: true })
      return data
    },
  })
}
