/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteGroupOptions, DeleteGroupStatus204, DeleteGroupStatus401, DeleteGroupStatus403 } from '../types/DeleteGroup'
import { mutationOptions } from '@tanstack/react-query'
import { deleteGroup } from '../clients/deleteGroup'

export const deleteGroupMutationKey = () => [{ url: '/api/v1/identity/groups/:id' }] as const

export function deleteGroupMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteGroupMutationKey()
  return mutationOptions<DeleteGroupStatus204, ResponseErrorConfig<DeleteGroupStatus401 | DeleteGroupStatus403>, DeleteGroupOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteGroup({ ...config, path, throwOnError: true })
      return data
    },
  })
}
