/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeletePositionOptions, DeletePositionStatus200 } from '../types/DeletePosition'
import { mutationOptions } from '@tanstack/react-query'
import { deletePosition } from '../clients/deletePosition'

export const deletePositionMutationKey = () => [{ url: '/api/v1/organizations/positions/:positionId' }] as const

export function deletePositionMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deletePositionMutationKey()
  return mutationOptions<DeletePositionStatus200, ResponseErrorConfig<Error>, DeletePositionOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deletePosition({ ...config, path, throwOnError: true })
      return data
    },
  })
}
