/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteProductOptions, DeleteProductStatus200 } from '../types/DeleteProduct'
import { mutationOptions } from '@tanstack/react-query'
import { deleteProduct } from '../clients/deleteProduct'

export const deleteProductMutationKey = () => [{ url: '/api/v1/catalog/products/:productId' }] as const

export function deleteProductMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteProductMutationKey()
  return mutationOptions<DeleteProductStatus200, ResponseErrorConfig<Error>, DeleteProductOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteProduct({ ...config, path, throwOnError: true })
      return data
    },
  })
}
