/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { EnrollTwoFactorStatus200, EnrollTwoFactorStatus401 } from '../types/EnrollTwoFactor'
import { mutationOptions } from '@tanstack/react-query'
import { enrollTwoFactor } from '../clients/enrollTwoFactor'

export const enrollTwoFactorMutationKey = () => [{ url: '/api/v1/identity/2fa/enroll' }] as const

export function enrollTwoFactorMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = enrollTwoFactorMutationKey()
  return mutationOptions<EnrollTwoFactorStatus200, ResponseErrorConfig<EnrollTwoFactorStatus401>, undefined, TContext>({
    mutationKey,
    mutationFn: async(_) => {
      const { data } = await enrollTwoFactor({ ...config, throwOnError: true })
      return data
    },
  })
}
