/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { FinalizeFileUploadOptions, FinalizeFileUploadStatus200 } from '../types/FinalizeFileUpload'
import { mutationOptions } from '@tanstack/react-query'
import { finalizeFileUpload } from '../clients/finalizeFileUpload'

export const finalizeFileUploadMutationKey = () => [{ url: '/api/v1/files/:id/finalize' }] as const

export function finalizeFileUploadMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = finalizeFileUploadMutationKey()
  return mutationOptions<FinalizeFileUploadStatus200, ResponseErrorConfig<Error>, FinalizeFileUploadOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await finalizeFileUpload({ ...config, path, throwOnError: true })
      return data
    },
  })
}
