/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsOptions, GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200 } from '../types/GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocations'
import { queryOptions } from '@tanstack/react-query'
import { getApiV1OrganizationsUnitsOrganizationunitidPositionAllocations } from '../clients/getApiV1OrganizationsUnitsOrganizationunitidPositionAllocations'

export const getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsQueryKey = ({ path }: Omit<GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsOptions, 'headers'>) => [{ url: '/api/v1/organizations/units/:organizationUnitId/position-allocations', params: path }] as const

type GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsQueryKey = ReturnType<typeof getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsQueryKey>

export function getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsQueryOptions({ path }: GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsQueryKey({ path })
  return queryOptions<GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200, ResponseErrorConfig<Error>, GetApiV1OrganizationsUnitsOrganizationunitidPositionAllocationsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getApiV1OrganizationsUnitsOrganizationunitidPositionAllocations({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
