/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetInvoiceByIdOptions, GetInvoiceByIdStatus200 } from '../types/GetInvoiceById'
import { queryOptions } from '@tanstack/react-query'
import { getInvoiceById } from '../clients/getInvoiceById'

export const getInvoiceByIdQueryKey = ({ path }: Omit<GetInvoiceByIdOptions, 'headers'>) => [{ url: '/api/v1/billing/invoices/:invoiceId', params: path }] as const

type GetInvoiceByIdQueryKey = ReturnType<typeof getInvoiceByIdQueryKey>

export function getInvoiceByIdQueryOptions({ path }: GetInvoiceByIdOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getInvoiceByIdQueryKey({ path })
  return queryOptions<GetInvoiceByIdStatus200, ResponseErrorConfig<Error>, GetInvoiceByIdStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getInvoiceById({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
