/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetRolePermissionsOptions, GetRolePermissionsStatus200, GetRolePermissionsStatus401, GetRolePermissionsStatus403, GetRolePermissionsStatus404 } from '../types/GetRolePermissions'
import { queryOptions } from '@tanstack/react-query'
import { getRolePermissions } from '../clients/getRolePermissions'

export const getRolePermissionsQueryKey = ({ path }: Omit<GetRolePermissionsOptions, 'headers'>) => [{ url: '/api/v1/identity/:id/permissions', params: path }] as const

type GetRolePermissionsQueryKey = ReturnType<typeof getRolePermissionsQueryKey>

export function getRolePermissionsQueryOptions({ path }: GetRolePermissionsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getRolePermissionsQueryKey({ path })
  return queryOptions<GetRolePermissionsStatus200, ResponseErrorConfig<GetRolePermissionsStatus401 | GetRolePermissionsStatus403 | GetRolePermissionsStatus404>, GetRolePermissionsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getRolePermissions({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
