/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetWebhookSubscriptionsOptions, GetWebhookSubscriptionsStatus200 } from '../types/GetWebhookSubscriptions'
import { queryOptions } from '@tanstack/react-query'
import { getWebhookSubscriptions } from '../clients/getWebhookSubscriptions'

export const getWebhookSubscriptionsQueryKey = ({ query }: Omit<GetWebhookSubscriptionsOptions, 'headers'>) => [{ url: '/api/v1/webhooks/subscriptions' }, ...(query ? [query] : [])] as const

type GetWebhookSubscriptionsQueryKey = ReturnType<typeof getWebhookSubscriptionsQueryKey>

export function getWebhookSubscriptionsQueryOptions({ query }: GetWebhookSubscriptionsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getWebhookSubscriptionsQueryKey({ query })
  return queryOptions<GetWebhookSubscriptionsStatus200, ResponseErrorConfig<Error>, GetWebhookSubscriptionsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getWebhookSubscriptions({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
