/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetPermissionCatalogStatus200, GetPermissionCatalogStatus401, GetPermissionCatalogStatus403 } from '../types/GetPermissionCatalog'
import { queryOptions } from '@tanstack/react-query'
import { getPermissionCatalog } from '../clients/getPermissionCatalog'

export const getPermissionCatalogQueryKey = () => [{ url: '/api/v1/identity/permissions/catalog' }] as const

type GetPermissionCatalogQueryKey = ReturnType<typeof getPermissionCatalogQueryKey>

export function getPermissionCatalogQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getPermissionCatalogQueryKey()
  return queryOptions<GetPermissionCatalogStatus200, ResponseErrorConfig<GetPermissionCatalogStatus401 | GetPermissionCatalogStatus403>, GetPermissionCatalogStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getPermissionCatalog({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
