/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetStatus200 } from '../types/Get'
import { queryOptions } from '@tanstack/react-query'
import { get } from '../clients/get'

export const getQueryKey = () => [{ url: '/' }] as const

type GetQueryKey = ReturnType<typeof getQueryKey>

export function getQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getQueryKey()
  return queryOptions<GetStatus200, ResponseErrorConfig<Error>, GetStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await get({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
