/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetImpersonationGrantsOptions, GetImpersonationGrantsStatus200, GetImpersonationGrantsStatus401, GetImpersonationGrantsStatus403 } from '../types/GetImpersonationGrants'
import { queryOptions } from '@tanstack/react-query'
import { getImpersonationGrants } from '../clients/getImpersonationGrants'

export const getImpersonationGrantsQueryKey = ({ query }: Omit<GetImpersonationGrantsOptions, 'headers'> = {}) => [{ url: '/api/v1/identity/impersonation/grants' }, ...(query ? [query] : [])] as const

type GetImpersonationGrantsQueryKey = ReturnType<typeof getImpersonationGrantsQueryKey>

export function getImpersonationGrantsQueryOptions({ query }: GetImpersonationGrantsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getImpersonationGrantsQueryKey({ query })
  return queryOptions<GetImpersonationGrantsStatus200, ResponseErrorConfig<GetImpersonationGrantsStatus401 | GetImpersonationGrantsStatus403>, GetImpersonationGrantsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getImpersonationGrants({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
