/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetAllPositionsOptions, GetAllPositionsStatus200 } from '../types/GetAllPositions'
import { queryOptions } from '@tanstack/react-query'
import { getAllPositions } from '../clients/getAllPositions'

export const getAllPositionsQueryKey = ({ path }: Omit<GetAllPositionsOptions, 'headers'>) => [{ url: '/api/v1/organizations/:organizationId/positions', params: path }] as const

type GetAllPositionsQueryKey = ReturnType<typeof getAllPositionsQueryKey>

export function getAllPositionsQueryOptions({ path }: GetAllPositionsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAllPositionsQueryKey({ path })
  return queryOptions<GetAllPositionsStatus200, ResponseErrorConfig<Error>, GetAllPositionsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getAllPositions({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
