/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetTenantMigrationsStatus200, GetTenantMigrationsStatus401, GetTenantMigrationsStatus403 } from '../types/GetTenantMigrations'
import { queryOptions } from '@tanstack/react-query'
import { getTenantMigrations } from '../clients/getTenantMigrations'

export const getTenantMigrationsQueryKey = () => [{ url: '/api/v1/tenants/migrations' }] as const

type GetTenantMigrationsQueryKey = ReturnType<typeof getTenantMigrationsQueryKey>

export function getTenantMigrationsQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getTenantMigrationsQueryKey()
  return queryOptions<GetTenantMigrationsStatus200, ResponseErrorConfig<GetTenantMigrationsStatus401 | GetTenantMigrationsStatus403>, GetTenantMigrationsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getTenantMigrations({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
