/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetInvoicesOptions, GetInvoicesStatus200 } from '../types/GetInvoices'
import { queryOptions } from '@tanstack/react-query'
import { getInvoices } from '../clients/getInvoices'

export const getInvoicesQueryKey = ({ query }: Omit<GetInvoicesOptions, 'headers'>) => [{ url: '/api/v1/billing/invoices' }, ...(query ? [query] : [])] as const

type GetInvoicesQueryKey = ReturnType<typeof getInvoicesQueryKey>

export function getInvoicesQueryOptions({ query }: GetInvoicesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getInvoicesQueryKey({ query })
  return queryOptions<GetInvoicesStatus200, ResponseErrorConfig<Error>, GetInvoicesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getInvoices({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
