/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetAuditsOptions, GetAuditsStatus200, GetAuditsStatus401, GetAuditsStatus403 } from '../types/GetAudits'
import { queryOptions } from '@tanstack/react-query'
import { getAudits } from '../clients/getAudits'

export const getAuditsQueryKey = ({ query }: Omit<GetAuditsOptions, 'headers'> = {}) => [{ url: '/api/v1/audits' }, ...(query ? [query] : [])] as const

type GetAuditsQueryKey = ReturnType<typeof getAuditsQueryKey>

export function getAuditsQueryOptions({ query }: GetAuditsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAuditsQueryKey({ query })
  return queryOptions<GetAuditsStatus200, ResponseErrorConfig<GetAuditsStatus401 | GetAuditsStatus403>, GetAuditsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getAudits({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
