/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetCategoryByIdOptions, GetCategoryByIdStatus200 } from '../types/GetCategoryById'
import { queryOptions } from '@tanstack/react-query'
import { getCategoryById } from '../clients/getCategoryById'

export const getCategoryByIdQueryKey = ({ path }: Omit<GetCategoryByIdOptions, 'headers'>) => [{ url: '/api/v1/catalog/categories/:categoryId', params: path }] as const

type GetCategoryByIdQueryKey = ReturnType<typeof getCategoryByIdQueryKey>

export function getCategoryByIdQueryOptions({ path }: GetCategoryByIdOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getCategoryByIdQueryKey({ path })
  return queryOptions<GetCategoryByIdStatus200, ResponseErrorConfig<Error>, GetCategoryByIdStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getCategoryById({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
