/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetSecurityAuditsOptions, GetSecurityAuditsStatus200, GetSecurityAuditsStatus401, GetSecurityAuditsStatus403 } from '../types/GetSecurityAudits'
import { queryOptions } from '@tanstack/react-query'
import { getSecurityAudits } from '../clients/getSecurityAudits'

export const getSecurityAuditsQueryKey = ({ query }: Omit<GetSecurityAuditsOptions, 'headers'> = {}) => [{ url: '/api/v1/audits/security' }, ...(query ? [query] : [])] as const

type GetSecurityAuditsQueryKey = ReturnType<typeof getSecurityAuditsQueryKey>

export function getSecurityAuditsQueryOptions({ query }: GetSecurityAuditsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getSecurityAuditsQueryKey({ query })
  return queryOptions<GetSecurityAuditsStatus200, ResponseErrorConfig<GetSecurityAuditsStatus401 | GetSecurityAuditsStatus403>, GetSecurityAuditsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getSecurityAudits({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
