/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetMyTenantStatusStatus200, GetMyTenantStatusStatus401 } from '../types/GetMyTenantStatus'
import { queryOptions } from '@tanstack/react-query'
import { getMyTenantStatus } from '../clients/getMyTenantStatus'

export const getMyTenantStatusQueryKey = () => [{ url: '/api/v1/tenants/me/status' }] as const

type GetMyTenantStatusQueryKey = ReturnType<typeof getMyTenantStatusQueryKey>

export function getMyTenantStatusQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMyTenantStatusQueryKey()
  return queryOptions<GetMyTenantStatusStatus200, ResponseErrorConfig<GetMyTenantStatusStatus401>, GetMyTenantStatusStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getMyTenantStatus({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
