/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetMyInvoicesOptions, GetMyInvoicesStatus200 } from '../types/GetMyInvoices'
import { queryOptions } from '@tanstack/react-query'
import { getMyInvoices } from '../clients/getMyInvoices'

export const getMyInvoicesQueryKey = ({ query }: Omit<GetMyInvoicesOptions, 'headers'>) => [{ url: '/api/v1/billing/invoices/me' }, ...(query ? [query] : [])] as const

type GetMyInvoicesQueryKey = ReturnType<typeof getMyInvoicesQueryKey>

export function getMyInvoicesQueryOptions({ query }: GetMyInvoicesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMyInvoicesQueryKey({ query })
  return queryOptions<GetMyInvoicesStatus200, ResponseErrorConfig<Error>, GetMyInvoicesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getMyInvoices({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
