/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetUserOptions, GetUserStatus200, GetUserStatus401, GetUserStatus403, GetUserStatus404 } from '../types/GetUser'
import { queryOptions } from '@tanstack/react-query'
import { getUser } from '../clients/getUser'

export const getUserQueryKey = ({ path }: Omit<GetUserOptions, 'headers'>) => [{ url: '/api/v1/identity/users/:id', params: path }] as const

type GetUserQueryKey = ReturnType<typeof getUserQueryKey>

export function getUserQueryOptions({ path }: GetUserOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getUserQueryKey({ path })
  return queryOptions<GetUserStatus200, ResponseErrorConfig<GetUserStatus401 | GetUserStatus403 | GetUserStatus404>, GetUserStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getUser({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
