/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetChannelByIdOptions, GetChannelByIdStatus200 } from '../types/GetChannelById'
import { queryOptions } from '@tanstack/react-query'
import { getChannelById } from '../clients/getChannelById'

export const getChannelByIdQueryKey = ({ path }: Omit<GetChannelByIdOptions, 'headers'>) => [{ url: '/api/v1/chat/channels/:id', params: path }] as const

type GetChannelByIdQueryKey = ReturnType<typeof getChannelByIdQueryKey>

export function getChannelByIdQueryOptions({ path }: GetChannelByIdOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getChannelByIdQueryKey({ path })
  return queryOptions<GetChannelByIdStatus200, ResponseErrorConfig<Error>, GetChannelByIdStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getChannelById({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
