/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { IssueJwtTokensOptions, IssueJwtTokensStatus200, IssueJwtTokensStatus400, IssueJwtTokensStatus401, IssueJwtTokensStatus403, IssueJwtTokensStatus500 } from '../types/IssueJwtTokens'
import { mutationOptions } from '@tanstack/react-query'
import { issueJwtTokens } from '../clients/issueJwtTokens'

export const issueJwtTokensMutationKey = () => [{ url: '/api/v1/identity/token/issue' }] as const

export function issueJwtTokensMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = issueJwtTokensMutationKey()
  return mutationOptions<IssueJwtTokensStatus200, ResponseErrorConfig<IssueJwtTokensStatus400 | IssueJwtTokensStatus401 | IssueJwtTokensStatus403 | IssueJwtTokensStatus500>, IssueJwtTokensOptions, TContext>({
    mutationKey,
    mutationFn: async({ body, headers }) => {
      const { data } = await issueJwtTokens({ ...config, body, headers, throwOnError: true })
      return data
    },
  })
}
