/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListChannelMessagesOptions, ListChannelMessagesStatus200 } from '../types/ListChannelMessages'
import { queryOptions } from '@tanstack/react-query'
import { listChannelMessages } from '../clients/listChannelMessages'

export const listChannelMessagesQueryKey = ({ path, query }: Omit<ListChannelMessagesOptions, 'headers'>) => [{ url: '/api/v1/chat/channels/:id/messages', params: path }, ...(query ? [query] : [])] as const

type ListChannelMessagesQueryKey = ReturnType<typeof listChannelMessagesQueryKey>

export function listChannelMessagesQueryOptions({ path, query }: ListChannelMessagesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listChannelMessagesQueryKey({ path, query })
  return queryOptions<ListChannelMessagesStatus200, ResponseErrorConfig<Error>, ListChannelMessagesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listChannelMessages({ ...config, path, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
