/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListNotificationsOptions, ListNotificationsStatus200 } from '../types/ListNotifications'
import { queryOptions } from '@tanstack/react-query'
import { listNotifications } from '../clients/listNotifications'

export const listNotificationsQueryKey = ({ query }: Omit<ListNotificationsOptions, 'headers'> = {}) => [{ url: '/api/v1/notifications' }, ...(query ? [query] : [])] as const

type ListNotificationsQueryKey = ReturnType<typeof listNotificationsQueryKey>

export function listNotificationsQueryOptions({ query }: ListNotificationsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listNotificationsQueryKey({ query })
  return queryOptions<ListNotificationsStatus200, ResponseErrorConfig<Error>, ListNotificationsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listNotifications({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
