/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListPinnedMessagesOptions, ListPinnedMessagesStatus200 } from '../types/ListPinnedMessages'
import { queryOptions } from '@tanstack/react-query'
import { listPinnedMessages } from '../clients/listPinnedMessages'

export const listPinnedMessagesQueryKey = ({ path }: Omit<ListPinnedMessagesOptions, 'headers'>) => [{ url: '/api/v1/chat/channels/:id/pinned', params: path }] as const

type ListPinnedMessagesQueryKey = ReturnType<typeof listPinnedMessagesQueryKey>

export function listPinnedMessagesQueryOptions({ path }: ListPinnedMessagesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listPinnedMessagesQueryKey({ path })
  return queryOptions<ListPinnedMessagesStatus200, ResponseErrorConfig<Error>, ListPinnedMessagesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listPinnedMessages({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
