/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListGroupsOptions, ListGroupsStatus200 } from '../types/ListGroups'
import { queryOptions } from '@tanstack/react-query'
import { listGroups } from '../clients/listGroups'

export const listGroupsQueryKey = ({ query }: Omit<ListGroupsOptions, 'headers'> = {}) => [{ url: '/api/v1/identity/groups' }, ...(query ? [query] : [])] as const

type ListGroupsQueryKey = ReturnType<typeof listGroupsQueryKey>

export function listGroupsQueryOptions({ query }: ListGroupsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listGroupsQueryKey({ query })
  return queryOptions<ListGroupsStatus200, ResponseErrorConfig<Error>, ListGroupsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listGroups({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
