/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { MoveOrganizationUnitToNewOrganizationOptions, MoveOrganizationUnitToNewOrganizationStatus200 } from '../types/MoveOrganizationUnitToNewOrganization'
import { mutationOptions } from '@tanstack/react-query'
import { moveOrganizationUnitToNewOrganization } from '../clients/moveOrganizationUnitToNewOrganization'

export const moveOrganizationUnitToNewOrganizationMutationKey = () => [{ url: '/api/v1/organizations/units/:organizationUnitId/move' }] as const

export function moveOrganizationUnitToNewOrganizationMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = moveOrganizationUnitToNewOrganizationMutationKey()
  return mutationOptions<MoveOrganizationUnitToNewOrganizationStatus200, ResponseErrorConfig<Error>, MoveOrganizationUnitToNewOrganizationOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await moveOrganizationUnitToNewOrganization({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
