/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { MarkInvoicePaidOptions, MarkInvoicePaidStatus200 } from '../types/MarkInvoicePaid'
import { mutationOptions } from '@tanstack/react-query'
import { markInvoicePaid } from '../clients/markInvoicePaid'

export const markInvoicePaidMutationKey = () => [{ url: '/api/v1/billing/invoices/:invoiceId/pay' }] as const

export function markInvoicePaidMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = markInvoicePaidMutationKey()
  return mutationOptions<MarkInvoicePaidStatus200, ResponseErrorConfig<Error>, MarkInvoicePaidOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await markInvoicePaid({ ...config, path, throwOnError: true })
      return data
    },
  })
}
