/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PinMessageOptions, PinMessageStatus200 } from '../types/PinMessage'
import { mutationOptions } from '@tanstack/react-query'
import { pinMessage } from '../clients/pinMessage'

export const pinMessageMutationKey = () => [{ url: '/api/v1/chat/messages/:id/pin' }] as const

export function pinMessageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = pinMessageMutationKey()
  return mutationOptions<PinMessageStatus200, ResponseErrorConfig<Error>, PinMessageOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await pinMessage({ ...config, path, throwOnError: true })
      return data
    },
  })
}
