/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { RegisterUserOptions, RegisterUserStatus201, RegisterUserStatus400, RegisterUserStatus401, RegisterUserStatus403 } from '../types/RegisterUser'
import { mutationOptions } from '@tanstack/react-query'
import { registerUser } from '../clients/registerUser'

export const registerUserMutationKey = () => [{ url: '/api/v1/identity/register' }] as const

export function registerUserMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = registerUserMutationKey()
  return mutationOptions<RegisterUserStatus201, ResponseErrorConfig<RegisterUserStatus400 | RegisterUserStatus401 | RegisterUserStatus403>, RegisterUserOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await registerUser({ ...config, body, throwOnError: true })
      return data
    },
  })
}
