/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { RenewTenantOptions, RenewTenantStatus200, RenewTenantStatus400, RenewTenantStatus401, RenewTenantStatus403 } from '../types/RenewTenant'
import { mutationOptions } from '@tanstack/react-query'
import { renewTenant } from '../clients/renewTenant'

export const renewTenantMutationKey = () => [{ url: '/api/v1/tenants/:id/renew' }] as const

export function renewTenantMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = renewTenantMutationKey()
  return mutationOptions<RenewTenantStatus200, ResponseErrorConfig<RenewTenantStatus400 | RenewTenantStatus401 | RenewTenantStatus403>, RenewTenantOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await renewTenant({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
