/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ResendConfirmationEmailOptions, ResendConfirmationEmailStatus204, ResendConfirmationEmailStatus401, ResendConfirmationEmailStatus403, ResendConfirmationEmailStatus404 } from '../types/ResendConfirmationEmail'
import { mutationOptions } from '@tanstack/react-query'
import { resendConfirmationEmail } from '../clients/resendConfirmationEmail'

export const resendConfirmationEmailMutationKey = () => [{ url: '/api/v1/identity/users/:id/resend-confirmation-email' }] as const

export function resendConfirmationEmailMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = resendConfirmationEmailMutationKey()
  return mutationOptions<ResendConfirmationEmailStatus204, ResponseErrorConfig<ResendConfirmationEmailStatus401 | ResendConfirmationEmailStatus403 | ResendConfirmationEmailStatus404>, ResendConfirmationEmailOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await resendConfirmationEmail({ ...config, path, throwOnError: true })
      return data
    },
  })
}
