/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { RestoreCategoryOptions, RestoreCategoryStatus200 } from '../types/RestoreCategory'
import { mutationOptions } from '@tanstack/react-query'
import { restoreCategory } from '../clients/restoreCategory'

export const restoreCategoryMutationKey = () => [{ url: '/api/v1/catalog/categories/:categoryId/restore' }] as const

export function restoreCategoryMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = restoreCategoryMutationKey()
  return mutationOptions<RestoreCategoryStatus200, ResponseErrorConfig<Error>, RestoreCategoryOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await restoreCategory({ ...config, path, throwOnError: true })
      return data
    },
  })
}
