/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ResetTenantThemeStatus204, ResetTenantThemeStatus401, ResetTenantThemeStatus403 } from '../types/ResetTenantTheme'
import { mutationOptions } from '@tanstack/react-query'
import { resetTenantTheme } from '../clients/resetTenantTheme'

export const resetTenantThemeMutationKey = () => [{ url: '/api/v1/tenants/theme/reset' }] as const

export function resetTenantThemeMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = resetTenantThemeMutationKey()
  return mutationOptions<ResetTenantThemeStatus204, ResponseErrorConfig<ResetTenantThemeStatus401 | ResetTenantThemeStatus403>, undefined, TContext>({
    mutationKey,
    mutationFn: async(_) => {
      const { data } = await resetTenantTheme({ ...config, throwOnError: true })
      return data
    },
  })
}
