/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { RefreshJwtTokensOptions, RefreshJwtTokensStatus200, RefreshJwtTokensStatus400, RefreshJwtTokensStatus401, RefreshJwtTokensStatus500 } from '../types/RefreshJwtTokens'
import { mutationOptions } from '@tanstack/react-query'
import { refreshJwtTokens } from '../clients/refreshJwtTokens'

export const refreshJwtTokensMutationKey = () => [{ url: '/api/v1/identity/token/refresh' }] as const

export function refreshJwtTokensMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = refreshJwtTokensMutationKey()
  return mutationOptions<RefreshJwtTokensStatus200, ResponseErrorConfig<RefreshJwtTokensStatus400 | RefreshJwtTokensStatus401 | RefreshJwtTokensStatus500>, RefreshJwtTokensOptions, TContext>({
    mutationKey,
    mutationFn: async({ body, headers }) => {
      const { data } = await refreshJwtTokens({ ...config, body, headers, throwOnError: true })
      return data
    },
  })
}
