/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { RestoreChannelOptions, RestoreChannelStatus200 } from '../types/RestoreChannel'
import { mutationOptions } from '@tanstack/react-query'
import { restoreChannel } from '../clients/restoreChannel'

export const restoreChannelMutationKey = () => [{ url: '/api/v1/chat/channels/:id/restore' }] as const

export function restoreChannelMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = restoreChannelMutationKey()
  return mutationOptions<RestoreChannelStatus200, ResponseErrorConfig<Error>, RestoreChannelOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await restoreChannel({ ...config, path, throwOnError: true })
      return data
    },
  })
}
