/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { SearchCategoriesOptions, SearchCategoriesStatus200 } from '../types/SearchCategories'
import { queryOptions } from '@tanstack/react-query'
import { searchCategories } from '../clients/searchCategories'

export const searchCategoriesQueryKey = ({ query }: Omit<SearchCategoriesOptions, 'headers'>) => [{ url: '/api/v1/catalog/categories' }, ...(query ? [query] : [])] as const

type SearchCategoriesQueryKey = ReturnType<typeof searchCategoriesQueryKey>

export function searchCategoriesQueryOptions({ query }: SearchCategoriesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = searchCategoriesQueryKey({ query })
  return queryOptions<SearchCategoriesStatus200, ResponseErrorConfig<Error>, SearchCategoriesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await searchCategories({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
