/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { SearchMessagesOptions, SearchMessagesStatus200 } from '../types/SearchMessages'
import { queryOptions } from '@tanstack/react-query'
import { searchMessages } from '../clients/searchMessages'

export const searchMessagesQueryKey = ({ query }: Omit<SearchMessagesOptions, 'headers'>) => [{ url: '/api/v1/chat/search' }, ...(query ? [query] : [])] as const

type SearchMessagesQueryKey = ReturnType<typeof searchMessagesQueryKey>

export function searchMessagesQueryOptions({ query }: SearchMessagesOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = searchMessagesQueryKey({ query })
  return queryOptions<SearchMessagesStatus200, ResponseErrorConfig<Error>, SearchMessagesStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await searchMessages({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
