/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { StartImpersonationOptions, StartImpersonationStatus200, StartImpersonationStatus400, StartImpersonationStatus401, StartImpersonationStatus403, StartImpersonationStatus404 } from '../types/StartImpersonation'
import { mutationOptions } from '@tanstack/react-query'
import { startImpersonation } from '../clients/startImpersonation'

export const startImpersonationMutationKey = () => [{ url: '/api/v1/identity/impersonation/start' }] as const

export function startImpersonationMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = startImpersonationMutationKey()
  return mutationOptions<StartImpersonationStatus200, ResponseErrorConfig<StartImpersonationStatus400 | StartImpersonationStatus401 | StartImpersonationStatus403 | StartImpersonationStatus404>, StartImpersonationOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await startImpersonation({ ...config, body, throwOnError: true })
      return data
    },
  })
}
