/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { SendMessageOptions, SendMessageStatus200 } from '../types/SendMessage'
import { mutationOptions } from '@tanstack/react-query'
import { sendMessage } from '../clients/sendMessage'

export const sendMessageMutationKey = () => [{ url: '/api/v1/chat/channels/:id/messages' }] as const

export function sendMessageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = sendMessageMutationKey()
  return mutationOptions<SendMessageStatus200, ResponseErrorConfig<Error>, SendMessageOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await sendMessage({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
