/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { SseTokenStatus200 } from '../types/SseToken'
import { mutationOptions } from '@tanstack/react-query'
import { sseToken } from '../clients/sseToken'

export const sseTokenMutationKey = () => [{ url: '/api/v1/sse/token' }] as const

export function sseTokenMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = sseTokenMutationKey()
  return mutationOptions<SseTokenStatus200, ResponseErrorConfig<Error>, undefined, TContext>({
    mutationKey,
    mutationFn: async(_) => {
      const { data } = await sseToken({ ...config, throwOnError: true })
      return data
    },
  })
}
