/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateTicketOptions, UpdateTicketStatus200 } from '../types/UpdateTicket'
import { mutationOptions } from '@tanstack/react-query'
import { updateTicket } from '../clients/updateTicket'

export const updateTicketMutationKey = () => [{ url: '/api/v1/tickets/:ticketId' }] as const

export function updateTicketMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateTicketMutationKey()
  return mutationOptions<UpdateTicketStatus200, ResponseErrorConfig<Error>, UpdateTicketOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateTicket({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
