/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateTenantThemeOptions, UpdateTenantThemeStatus204, UpdateTenantThemeStatus400, UpdateTenantThemeStatus401, UpdateTenantThemeStatus403 } from '../types/UpdateTenantTheme'
import { mutationOptions } from '@tanstack/react-query'
import { updateTenantTheme } from '../clients/updateTenantTheme'

export const updateTenantThemeMutationKey = () => [{ url: '/api/v1/tenants/theme' }] as const

export function updateTenantThemeMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateTenantThemeMutationKey()
  return mutationOptions<UpdateTenantThemeStatus204, ResponseErrorConfig<UpdateTenantThemeStatus400 | UpdateTenantThemeStatus401 | UpdateTenantThemeStatus403>, UpdateTenantThemeOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await updateTenantTheme({ ...config, body, throwOnError: true })
      return data
    },
  })
}
