/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UnpinMessageOptions, UnpinMessageStatus200 } from '../types/UnpinMessage'
import { mutationOptions } from '@tanstack/react-query'
import { unpinMessage } from '../clients/unpinMessage'

export const unpinMessageMutationKey = () => [{ url: '/api/v1/chat/messages/:id/pin' }] as const

export function unpinMessageMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = unpinMessageMutationKey()
  return mutationOptions<UnpinMessageStatus200, ResponseErrorConfig<Error>, UnpinMessageOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await unpinMessage({ ...config, path, throwOnError: true })
      return data
    },
  })
}
