/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdateUserProfileOptions, UpdateUserProfileStatus200, UpdateUserProfileStatus400, UpdateUserProfileStatus401 } from '../types/UpdateUserProfile'
import { mutationOptions } from '@tanstack/react-query'
import { updateUserProfile } from '../clients/updateUserProfile'

export const updateUserProfileMutationKey = () => [{ url: '/api/v1/identity/profile' }] as const

export function updateUserProfileMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateUserProfileMutationKey()
  return mutationOptions<UpdateUserProfileStatus200, ResponseErrorConfig<UpdateUserProfileStatus400 | UpdateUserProfileStatus401>, UpdateUserProfileOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await updateUserProfile({ ...config, body, throwOnError: true })
      return data
    },
  })
}
