/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { UpdatePositionOptions, UpdatePositionStatus200 } from '../types/UpdatePosition'
import { mutationOptions } from '@tanstack/react-query'
import { updatePosition } from '../clients/updatePosition'

export const updatePositionMutationKey = () => [{ url: '/api/v1/organizations/positions/:positionId' }] as const

export function updatePositionMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updatePositionMutationKey()
  return mutationOptions<UpdatePositionStatus200, ResponseErrorConfig<Error>, UpdatePositionOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updatePosition({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
