/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { AddTicketCommentOptions, AddTicketCommentStatus200 } from '../../types/AddTicketComment'
import { mutationOptions } from '@tanstack/react-query'
import { addTicketComment } from '../../clients/addTicketComment'

export const addTicketCommentMutationKey = () => [{ url: '/api/v1/tickets/:ticketId/comments' }] as const

export function addTicketCommentMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = addTicketCommentMutationKey()
  return mutationOptions<AddTicketCommentStatus200, ResponseErrorConfig<Error>, AddTicketCommentOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await addTicketComment({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
