/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CloseTicketOptions, CloseTicketStatus200 } from '../../types/CloseTicket'
import { mutationOptions } from '@tanstack/react-query'
import { closeTicket } from '../../clients/closeTicket'

export const closeTicketMutationKey = () => [{ url: '/api/v1/tickets/:ticketId/close' }] as const

export function closeTicketMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = closeTicketMutationKey()
  return mutationOptions<CloseTicketStatus200, ResponseErrorConfig<Error>, CloseTicketOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await closeTicket({ ...config, path, throwOnError: true })
      return data
    },
  })
}
