/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CreateTicketOptions, CreateTicketStatus200 } from '../../types/CreateTicket'
import { mutationOptions } from '@tanstack/react-query'
import { createTicket } from '../../clients/createTicket'

export const createTicketMutationKey = () => [{ url: '/api/v1/tickets' }] as const

export function createTicketMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createTicketMutationKey()
  return mutationOptions<CreateTicketStatus200, ResponseErrorConfig<Error>, CreateTicketOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createTicket({ ...config, body, throwOnError: true })
      return data
    },
  })
}
