/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ListTicketCommentsOptions, ListTicketCommentsStatus200 } from '../../types/ListTicketComments'
import { queryOptions } from '@tanstack/react-query'
import { listTicketComments } from '../../clients/listTicketComments'

export const listTicketCommentsQueryKey = ({ path }: Omit<ListTicketCommentsOptions, 'headers'>) => [{ url: '/api/v1/tickets/:ticketId/comments', params: path }] as const

type ListTicketCommentsQueryKey = ReturnType<typeof listTicketCommentsQueryKey>

export function listTicketCommentsQueryOptions({ path }: ListTicketCommentsOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listTicketCommentsQueryKey({ path })
  return queryOptions<ListTicketCommentsStatus200, ResponseErrorConfig<Error>, ListTicketCommentsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await listTicketComments({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
