/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { ResolveTicketOptions, ResolveTicketStatus200 } from '../../types/ResolveTicket'
import { mutationOptions } from '@tanstack/react-query'
import { resolveTicket } from '../../clients/resolveTicket'

export const resolveTicketMutationKey = () => [{ url: '/api/v1/tickets/:ticketId/resolve' }] as const

export function resolveTicketMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = resolveTicketMutationKey()
  return mutationOptions<ResolveTicketStatus200, ResponseErrorConfig<Error>, ResolveTicketOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await resolveTicket({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
