/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { DeleteFileOptions, DeleteFileStatus200 } from '../../types/DeleteFile'
import { mutationOptions } from '@tanstack/react-query'
import { deleteFile } from '../../clients/deleteFile'

export const deleteFileMutationKey = () => [{ url: '/api/v1/files/:id' }] as const

export function deleteFileMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = deleteFileMutationKey()
  return mutationOptions<DeleteFileStatus200, ResponseErrorConfig<Error>, DeleteFileOptions, TContext>({
    mutationKey,
    mutationFn: async({ path }) => {
      const { data } = await deleteFile({ ...config, path, throwOnError: true })
      return data
    },
  })
}
