/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { RequestFileUploadUrlOptions, RequestFileUploadUrlStatus200 } from '../../types/RequestFileUploadUrl'
import { mutationOptions } from '@tanstack/react-query'
import { requestFileUploadUrl } from '../../clients/requestFileUploadUrl'

export const requestFileUploadUrlMutationKey = () => [{ url: '/api/v1/files/upload-url' }] as const

export function requestFileUploadUrlMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = requestFileUploadUrlMutationKey()
  return mutationOptions<RequestFileUploadUrlStatus200, ResponseErrorConfig<Error>, RequestFileUploadUrlOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await requestFileUploadUrl({ ...config, body, throwOnError: true })
      return data
    },
  })
}
