/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetPresenceOptions, GetPresenceStatus200 } from '../../types/GetPresence'
import { queryOptions } from '@tanstack/react-query'
import { getPresence } from '../../clients/getPresence'

export const getPresenceQueryKey = ({ query }: Omit<GetPresenceOptions, 'headers'>) => [{ url: '/api/v1/realtime/presence' }, ...(query ? [query] : [])] as const

type GetPresenceQueryKey = ReturnType<typeof getPresenceQueryKey>

export function getPresenceQueryOptions({ query }: GetPresenceOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getPresenceQueryKey({ query })
  return queryOptions<GetPresenceStatus200, ResponseErrorConfig<Error>, GetPresenceStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getPresence({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
