/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CreateBillingPlanOptions, CreateBillingPlanStatus200 } from '../../types/CreateBillingPlan'
import { mutationOptions } from '@tanstack/react-query'
import { createBillingPlan } from '../../clients/createBillingPlan'

export const createBillingPlanMutationKey = () => [{ url: '/api/v1/billing/plans' }] as const

export function createBillingPlanMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createBillingPlanMutationKey()
  return mutationOptions<CreateBillingPlanStatus200, ResponseErrorConfig<Error>, CreateBillingPlanOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await createBillingPlan({ ...config, body, throwOnError: true })
      return data
    },
  })
}
