/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { CaptureUsageSnapshotsOptions, CaptureUsageSnapshotsStatus200, CaptureUsageSnapshotsStatus400, CaptureUsageSnapshotsStatus401, CaptureUsageSnapshotsStatus403 } from '../../types/CaptureUsageSnapshots'
import { mutationOptions } from '@tanstack/react-query'
import { captureUsageSnapshots } from '../../clients/captureUsageSnapshots'

export const captureUsageSnapshotsMutationKey = () => [{ url: '/api/v1/billing/usage/snapshots/capture' }] as const

export function captureUsageSnapshotsMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = captureUsageSnapshotsMutationKey()
  return mutationOptions<CaptureUsageSnapshotsStatus200, ResponseErrorConfig<CaptureUsageSnapshotsStatus400 | CaptureUsageSnapshotsStatus401 | CaptureUsageSnapshotsStatus403>, CaptureUsageSnapshotsOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      const { data } = await captureUsageSnapshots({ ...config, body, throwOnError: true })
      return data
    },
  })
}
