/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetMySubscriptionStatus200 } from '../../types/GetMySubscription'
import { queryOptions } from '@tanstack/react-query'
import { getMySubscription } from '../../clients/getMySubscription'

export const getMySubscriptionQueryKey = () => [{ url: '/api/v1/billing/subscriptions/me' }] as const

type GetMySubscriptionQueryKey = ReturnType<typeof getMySubscriptionQueryKey>

export function getMySubscriptionQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMySubscriptionQueryKey()
  return queryOptions<GetMySubscriptionStatus200, ResponseErrorConfig<Error>, GetMySubscriptionStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getMySubscription({ ...config, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
