/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetInvoicePdfOptions, GetInvoicePdfStatus200, GetInvoicePdfStatus404 } from '../../types/GetInvoicePdf'
import { queryOptions } from '@tanstack/react-query'
import { getInvoicePdf } from '../../clients/getInvoicePdf'

export const getInvoicePdfQueryKey = ({ path }: Omit<GetInvoicePdfOptions, 'headers'>) => [{ url: '/api/v1/billing/invoices/:invoiceId/pdf', params: path }] as const

type GetInvoicePdfQueryKey = ReturnType<typeof getInvoicePdfQueryKey>

export function getInvoicePdfQueryOptions({ path }: GetInvoicePdfOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getInvoicePdfQueryKey({ path })
  return queryOptions<GetInvoicePdfStatus200, ResponseErrorConfig<GetInvoicePdfStatus404>, GetInvoicePdfStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getInvoicePdf({ ...config, path, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
