/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetBillingPlansOptions, GetBillingPlansStatus200 } from '../../types/GetBillingPlans'
import { queryOptions } from '@tanstack/react-query'
import { getBillingPlans } from '../../clients/getBillingPlans'

export const getBillingPlansQueryKey = ({ query }: Omit<GetBillingPlansOptions, 'headers'>) => [{ url: '/api/v1/billing/plans' }, ...(query ? [query] : [])] as const

type GetBillingPlansQueryKey = ReturnType<typeof getBillingPlansQueryKey>

export function getBillingPlansQueryOptions({ query }: GetBillingPlansOptions, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getBillingPlansQueryKey({ query })
  return queryOptions<GetBillingPlansStatus200, ResponseErrorConfig<Error>, GetBillingPlansStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getBillingPlans({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
