/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { GetUsageSnapshotsOptions, GetUsageSnapshotsStatus200 } from '../../types/GetUsageSnapshots'
import { queryOptions } from '@tanstack/react-query'
import { getUsageSnapshots } from '../../clients/getUsageSnapshots'

export const getUsageSnapshotsQueryKey = ({ query }: Omit<GetUsageSnapshotsOptions, 'headers'> = {}) => [{ url: '/api/v1/billing/usage' }, ...(query ? [query] : [])] as const

type GetUsageSnapshotsQueryKey = ReturnType<typeof getUsageSnapshotsQueryKey>

export function getUsageSnapshotsQueryOptions({ query }: GetUsageSnapshotsOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getUsageSnapshotsQueryKey({ query })
  return queryOptions<GetUsageSnapshotsStatus200, ResponseErrorConfig<Error>, GetUsageSnapshotsStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      const { data } = await getUsageSnapshots({ ...config, query, signal: config.signal ?? signal, throwOnError: true })
      return data
   },
  })
}
