/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../../.kubb/client'
import type { UpdateBillingPlanOptions, UpdateBillingPlanStatus200 } from '../../types/UpdateBillingPlan'
import { mutationOptions } from '@tanstack/react-query'
import { updateBillingPlan } from '../../clients/updateBillingPlan'

export const updateBillingPlanMutationKey = () => [{ url: '/api/v1/billing/plans/:planId' }] as const

export function updateBillingPlanMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = updateBillingPlanMutationKey()
  return mutationOptions<UpdateBillingPlanStatus200, ResponseErrorConfig<Error>, UpdateBillingPlanOptions, TContext>({
    mutationKey,
    mutationFn: async({ path, body }) => {
      const { data } = await updateBillingPlan({ ...config, path, body, throwOnError: true })
      return data
    },
  })
}
